- sp_BlitzCache.sql
This only applies to BlitzCache, and the changes I made to look for various expensive things.
> Erik blitzcache kl

- sp_BlitzCache.sql
If @Reanalyze = 0. This way we don’t get results from the last pass.
> #303 - sp_BlitzCache now truncates ##bou_BlitzCacheResults

- sp_Blitz.sql
sp_Blitz fixing supported list of SQL Server versions. Pesky equals signs. Was <=, should be <.
> #344 sp_Blitz fixing current supported versions of SQL Server

- sp_BlitzIndex.sql
Was 100k benefit per day, but was filtering out a lot of indexes on
servers with high uptime (months).
> #338 sp_BlitzIndex lowering missing index threshold

- sp_BlitzFirst.sql
This ended up being a bit of an overhaul, but its been tested across all
relevant AWS instances
1. Checks product versions the same way sp_Blitz does
2. Remove support for 2005 -- it won't compile with the new OFFSET data
type -- nothing will run there anyway
3. For 2008 and 2008R2, runs a stripped down version of a 'more
interesting' what is running query that for some reason wasn't used the
first time
4. for versions of 2012 and 2014 that don't have the new columns for:
mem grants etc, a case expression takes them out of the dynamic sql
5. for versions that do support it, they're included
Testing was good on this. Works across all versions, with confidence,
since our 2014 instance in AWS isn't patched to SP2, but my local is,
and the minor version of our 2016 instance is pre-RTM, and …
> Update what is running queries to reflect new columns

- CONTRIBUTING.md
- README.md
Closes #365 - now at sqlcommunity.slack.com.
> #365 contributing and readme - update Slack location

- sp_BlitzIndex.sql
When the Version and Date parameters are updated, there where 2 places
where it has to be mannually updated as well, now when the Version and Date parameters are updated, it use uniform output of Script Version and Date.
It was confusing that the output was 4.0 and the real version is 4.1.
> Make consistent output of Script Version and Date - sp_BlitzIndex

- sp_Blitz.sql
Closes #412. Added this to the WHERE clause on the free RAM check:
AND CAST(cTotal.cntr_value AS BIGINT) > 4000
> #412 sp_Blitz reporting too much free memory on small boxes

- sp_Blitz.sql
#402 
#403 
Tested in AWS lab 2008-2012
Locally on 2014 and 2016
To repro: set up affinity masking to take some CPUs offline.
Possible problems: Not tested on a machine with > 1 socket
If anyone can out there can test that portion, I'd be really grateful.
> Blitz erik 402

- sp_Blitz.sql
Adding support for outputting results of sp_Blitz to table on Linked server along with some error checking for @OutputDatabaseName.
I have tested on all supported instances of SQL Server except 2014 and 2016. Help with testing would be appreciated.
> #293 Support for @OutputServerName in sp_Blitz

- sp_Blitz.sql
Code provided by JulieOKC
Looks like it works correctly, and agrees with startup time from
PowerShell
Get-CimInstance -ClassName win32_operatingsystem | select csname,
lastbootuptime
Also, I remember the last time I restarted. So that helps.
> Add server last restart time to Informational

- sp_foreachdb.sql
I added an exclude_list parameter to Aaron's sp_foreachdb because I had a use case where I needed to run a script against multiple databases on a server but had to skip specific databases.
> Issue 58 aaron bertrand

- sp_Blitz.sql
Amazon RDS doesn’t allow access to maintenance plan tables. Skips
checks 180 and 181. Closes #409.
> #409 sp_Blitz skip maintenance plan checks in RDS

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Warn if sys.dm_os_cluster_nodes doesn’t have any ready-to-go failover
partners. Closes #449.
> #449 sp_Blitz add check 184 for cluster health

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Adds check 185 to compare tempdb’s creation date vs the total length of
wait time for sqltrace_incremental_flush_sleep, with a 10% fudge
factor. If they’re different, check 185 is fired, plus the wait times
per hour are reset. Closes #84.
> #84 - check when wait stats were last cleared

- sp_BlitzFirst.sql
#503 
Ready for testing anew
Was originally tested on 2008-2016
Details:
Duplicate lines for the same SPID would show up on 2014+. Believe the issue is a missing join condition.
RE: #503 
Session vs Request details are now noted in column names.
> Fix join conditions and column names

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Do a select top 1 * from msdb.dbo.backupset order by 1, and if they
don't have backup history going back at least 48 hours, advise that
they're purging out backupset too frequently. Also tuned check 3
(unpurged history) while I was in there. Closes #269.
> #269 sp_Blitz add check 186 for missing backup history

- sp_Blitz.sql
Rather than listing them out in a where clause in two separate queries.
Closes #453.
> #453 sp_Blitz now uses temp table list of ignorable waits

- sp_Blitz.sql
If a database was restored in the last 14 days, ignore it when we check
which backups are being written to the same place where databases live.
Closes #417.
> #417 sp_Blitz ignore backup warning for restored databases

- sp_BlitzIndex.sql
Depending on version, there are two possible syntax blocks. They both
populate a temp table called #Statistics, and so far I've added two
checks. One for outdated stats, and one for stats with a low sample
rate.
Tested in the lab on
2008
2008R2
2012
2014
Tested locally
2016
Ready for more testing!
> BlitzIndex now checks for some potential statistics issues

- sp_BlitzIndex.sql
This was some code that should have been pulled, but doesn't break
anything because it's so old, it was before I started paying attention
to temp table name formatting.
> Stop double populating compression information temp tables

- sp_foreachdb.sql
Fixes # .
- Added exclude_list parameter so that user can provide a list of databases that sp_foreachdb should skip on a server.
- 
- 
- Execute sp_foreachdb with a list of databases to be skipped and confirm results are correct.
- 
- 
Added exclude_list so that a user can provide a list of databases that
sp_foreachdb should skip on a server.
> sp_foreachdb with exclude_list

- sp_Blitz.sql
Instead of * 60000, do * 60000.0. Closes #526.
> #526 sp_Blitz fixing arithmetic overflow in waits check

- sp_Blitz.sql
Filter used to catch LCK_M_S_LOW_PRIORITY. Switched it to specifically
list the waits instead. Closes #546.
> #546 sp_Blitz refine poison wait list for serializable locking

- sp_BlitzIndex.sql
Fixes # .
- Adds a COLLATE statement to the query that fails when running the procedure over a 'contained' database. Used the DATABASE_DEFAULT collation to be as safe as possible.
- 
- 
- set the database containment to 'Partial'
`USE [master]`
`GO`
`ALTER DATABASE [YourDBNameHere] SET CONTAINMENT = PARTIAL WITH NO_WAIT`
`GO`
`exec sp_BlitzIndex`
- SQL Server 2016 SP1, AlwaysOn
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/607
> ISSUE-607-Collation-Error-in-Contained-Databases

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Fixes #603 
- New alert to check if max server memory = min server memory
- Change server memory to the same as max memory and run the script.
- Test with different settings to confirm it doesn't show
Added two new parameters and then a block of code that will warn if min memory is the same as max.
> sp_Blitz Check if Min Server Memory = Max Server Memory

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Fixes #591  .
- Check if customer is on SQL Server 2016 Standard but does not have SP1 installed. Prompts that additional features now available.
- Run on SQL 2016 Standard Edition without SP1
- SQL Server 2016 Developer (with standard edition check excluded)
> sp_Blitz 2016 but not SP1

- sp_Blitz.sql
New to gitflow, sorry for any mistakes...
Fixes # .
- Allow sp_Blitz to be created / modified on case-sensitive server
- Case-sensitive SQL Server instance - YES
- SQL Server 2012 - YES
- SQL Server 2014 - YES
- Amazon RDS
- Azure SQL DB
> typo fix for case-sensistive servers

- sp_BlitzIndex.sql
Fixes #615 
- Added a check to see if columnstore indexes are in use alongside trace flag 834
- Find a server with columnstore indexes and flag 834 switched on (or make one) and run to ensure it flags.
- Test on servers with either and both switched off to ensure it doesn't show.
- SQL Server 2016 Developer (with and without trace flags)
(couldn't test on earlier versions as the servers are currently in use and it requires a reboot for flag 834)
Inserts into mode = 0 if columnstore indexes exist and the trace flag 834 is switched on. Currently set to a 150 priority error under 'Abnormal Psychology'. 
#TraceStatus table and data insert logic taken from sp_Blitz for consistency.
> sp_BlitzIndex - Flag if using columnstore indexes & trace 834

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Check sys.master_files vs tempdb.sys.database_files, new check 191. Closes #582.
> #582 sp_Blitz add warning for number of TempDB files

- sp_Blitz.sql
This value can be either 0 or 60 depending on a bunch of SQL and SSMS
bugs, so hard-coding those two values as acceptable. Closes #616.
> #616 sp_Blitz change default target_recovery_time

- sp_Blitz.sql
Use new sys.dm_os_sys_info field sql_memory_model to augment the LPIM
check. Closes #592.
> #592 sp_Blitz - check LPIM in SQL 2016 SP1 DMV

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
The existing IFI check had a duplicate check ID, so gave it a new one
(193). Added sys.dm_server_services check 192 for SQL 2016 SP1. Closes
#593.
> #593 sp_Blitz better Instant File Init checks

- sp_BlitzCache.sql
Closes #228
I think this does what you want when I read through the article. The only time we run a query like the one that throws an error in the article is when someone supplies @DatabaseName
```
Select *
From sys.dm_exec_cached_plans CP
CROSS APPLY sys.dm_exec_query_plan(CP.plan_handle) QP
Where QP.dbid = DB_ID('TwoTBDatabase')
```
> Skip offline databases

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Checks for database-level maxdop, legacy_cardinality_estimation,
parameter_sniffing, query_optimizer_hotfixes. Closes #598.
> #598 sp_Blitz add checks for database_scoped_configurations

- sp_BlitzFirst.sql
- sp_BlitzWho.sql
Fixes #576  .
- Alter sp_BlitzWho to allow for a paramater to show sleeping SPIDs
- Also alter sp_BlitzFirst to allow for this parameter to be used when it calls sp_BlitzWho
- For sp_BlitzWho run with and without new parameter to see that sleeping SPIDs appear when using it;
EXEC sp_BlitzWho @ShowSleepingSPIDs = 1
- For sp_BlitzFirst it requires expert mode to call sp_BlitzWho. Run with and without both of the parameters below. Also check when one is set to 1 and the other to zero
EXEC sp_Blitzfirst @ExpertMode = 1, @ShowSleepingSPIDs = 1
- SQL Server 2012 Enterprise (11.0.6020.0) 
- SQL Server 2014 Enterprise (12.0.4213.0)
- SQL Server 2016 Developer (13.0.4001.0)
Note: …
> sp_BlitzFirst & sp_BlitzWho - Allow for sleeping SPIDs

- sp_BlitzFirst.sql
Fixes #552  .
- Removed request_owner_type from check 3 - Priority 1 (Restore Running)
- Run a database restore (code below from Brent's original bug report), while it's running EXEC sp_BlitzFirst. You should get a Priority 1 error (see screenshot) about backups currently running.
USE msdb;
GO
ALTER DATABASE [StackOverflow] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [StackOverflow] FROM  DISK = N'M:\MSSQL\Backup\StackOverflow.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 5
ALTER DATABASE [StackOverflow] SET MULTI_USER
GO
Has been tested on:
- SQL Server 2012 Enterprise (11.0.6020.0)
- SQL Server 2014 Enterprise (12.0.4213.0)
- SQL Server 2016 Developer (13.0.4001.0)
> sp_BlitzFirst - Check 3 Fix

- Documentation/sp_BlitzFirst Checks by Priority.md
- sp_BlitzFirst.sql
Fixes #444  .
- Add check 28 to see if CPU is over 25% for non SQL Server processes.
- Add check to documentation
- Run a CPU intensive process on the SQL Server box and check in task manager that it's using over 25% of the available CPU. Then run sp_BlitzFirst with @seconds < 30 and this should appear as a level 50 error
- Alternatively, change the threshold down to 1% (on line 977) to show the issue appearing as per below;
- SQL Server 2012 Enterprise (11.0.6020.0)
- SQL Server 2014 Enterprise (12.0.4213.0)
- SQL Server 2016 Developer (13.0.4001.0)
> sp_BlitzFirst - Check if CPU >= 25% for non SQL Server processes

- sp_BlitzIndex.sql
To catch named instances of Reporting Server.
> #671 sp_BlitzIndex now ignores more ReportServer% databases

- sp_Blitz.sql
Closes three issues:
#628: useless version checks
#650: Wording for EE feature checks
#677: Insufficient checks for broken QS cleanup
> sp_Blitz 628

- sp_BlitzFirst.sql
If @SinceStartup = 1 or @Seconds = 0, was using local time (TempDB
creation date/time) for @StartSampleTime variable, but comparing it to
UTC. Changed @StartSampleTime to UTC. Closes #425.
> sp_BlitzFirst #425 fixing startup time

- sp_BlitzFirst.sql
Only fire checks 11 & 12 if your storage is actually causing WRITELOG
or PAGEIOLATCH%. Closes #565.
> sp_BlitzFirst #565 - tying file speeds to wait types

- sp_BlitzCache.sql
- Corrected a casing issue in the message for 'Many Indexes Modified'
-  Run against a database with Write queries hitting >- 5 indexes
-  Validate the casing on the Details column in the output
> Minor casing fix to 'Many Indexes Modified' message

- sp_Blitz.sql
Before, we were only looking at SQLTRACE_INCREMENTAL_FLUSH_SLEEP, but
that came back as 0 on some servers. Now we take the max of several
system wait types. Closes #712.
> #712 sp_Blitz - improved check for cleared waits

- sp_BlitzTrace.sql
Fixes #743 for sp_BlitzTrace.
- switching to "create if not exists and then alter procedure" pattern instead of drop/create
- Tested in an scenario where the procedure doesn't exist yet and then also when it already does.
> sp_BlitzTrace - create + alter procedure pattern

- sp_foreachdb.sql
Fixes #743 for sp_foreachdb.
switching to "create if not exists and then alter procedure" pattern instead of drop/create
Tested in an scenario where the procedure doesn't exist yet and then also when it already does.
SQL Server 2008 R2
> sp_foreachdb - create + alter procedure pattern

- sp_BlitzIndex.sql
Before, was producing duplicate results across databases. Closes #732.
Whispers sweet nothings to #711 but doesn’t fix it yet.
> #732 sp_BlitzIndex heaps queries now join on database_id

- sp_BlitzFirst.sql
If you use OutputDatabaseName, OutputSchemaName, OutputTableName, the
resulting tables have a CheckDate field with datatype DATETIMEOFFSET.
In previous versions of sp_BlitzFirst, this was UTC time with no time
zone. Now it’s the correct time and time zone offset. Closes #735.
> #735 sp_BlitzFirst fixing time zone formats in table results

- sp_BlitzIndex.sql
In previous versions, if you looked at the “Create TSQL” column that
has definitions for indexes, it had brackets around the DESC keyword.
That wasn’t valid T-SQL. Removed the brackets. Closes #726.
> #726 sp_BlitzIndex removing brackets around DESC

- Documentation/sp_BlitzFirst Checks by Priority.md
- sp_BlitzFirst.sql
Check the sql text to make sure it’s not a fragmentation level check.
Closes #740.
> #740 sp_BlitzFirst avoiding checkdb false positives

- sp_BlitzFirst.sql
Added info about sp_BlitzCache’s sort order for ‘recent compilations’
to the high compiles/sec and recompiles/sec checks. Closes #168.
> #168 sp_BlitzFirst explaining how to handle high compilations

- Documentation/sp_BlitzFirst Checks by Priority.md
- sp_BlitzFirst.sql
Also modifies check 6 to include poison waits in the wait stats section
even if they’re not in the top 10. Closes #748.
> #748 sp_BlitzFirst adding poison wait check ID 30

- DatabaseRestore.sql
- Add double-quotes around file names when passing to xp_cmdshell
- Execute dbo.DatabaseRestore against a path with a space in it
It's a small initial change... I hope to have another coming soon. :smile:
> Quote file paths to avoid problems when paths have spaces

- DatabaseRestore.sql
Fixes #764 (DatabaseRestore - Large LSNs cause CAST errors).
-  Changed variables for storing LSNs to numeric(25,0) instead of bigint
- Use the DatabaseRestore procedure against a database backup with large LSNs (greater than the max value of bigint). It should now work.
> Changed variables for storing LSNs to numeric(25,0) instead of bigint

- DatabaseRestore.sql
Fixes #766 (DatabaseRestore - Restores fail when using @MoveFiles=1 with long paths / multiple files).
- Remove 4 unused variables
- Change @MoveOption variable to nvarchar(MAX)
- Backup up a database to multiple files (i.e. 8) to a directory with a relatively long path (i.e. C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Backup). Then attempt to restore using @MoveFiles=1. This should now work.
> Issue 766/movefiles fails with long paths

- sp_BlitzCache.sql
query plan info should have been joining on query hash
removed unparameterized warning from stored proc summary
Closes #807
Closes #808
> Fixes for 807 and 808

- sp_Blitz.sql
Specific builds of 2008R2 have a bug that crashes when you query the
memory dumps DMV. Closes #762.
> sp_Blitz #762 - skip memory dumps query on 2008R2

- sp_Blitz.sql
Closes #805
Makes sure files are at least 1GB different in size before warning.
> tempdb size  warning

- sp_DatabaseRestore.sql
Fixes #814 
added ContinueDiff bit parameter to signal that the procedure should
check for diffs
added LastDiffBackup variable and moved the BackupFile and
BackupDateTime variables to be global so that they can be used across
the full and diff functions
cut n pasted the full restore feature, modified it to handle diffs and
set conditional logic so that the most recent diff date is checked
against the full backup date, this will hopefully prevent a situation
where there are no diffs or diffs older than the full.
EXEC dbo.sp_DatabaseRestore 
@Database = 'YourDBName', 
@BackupPathFull = '\\YourPath\FULL\', 
@BackupPathDiff = '\\YourPath\DIFF\',
@BackupPathLog = '\\YourPath\LOG\', 
@RestoreDiff = 1,
@ContinueLogs = 0, 
@RunRecovery …
> Issue 814 - Added Differential Restore Feature to sp_DatabaseRestore 

- Documentation/Development/Test sp_DatabaseRestore.sql
- sp_DatabaseRestore.sql
Fixes #871 
- Added @StopAt parameter for stopping at a specified date/time.  This is date/time from the filename string
- Squashed some bugs that were not correctly parsing the date strings which resulted in comparing dates with hyphens mathematically :(
- Added a script for testing this stuff.  You specify the database name you want to backup and restore and specify the root folder for the ola hallengren backups.  the root folder in this case is the folder above the level for the database name
- Open the "Test sp_DatabaseRestore.sql" script
- Specify the Database name you want to test with
- Specify the folder that is one level above the database name folder in your ola hallengren backup path. 
Has been tested on (remove any …
> sp_DatabaseRestore issue 871

- sp_BlitzBackups.sql
Was failing when run outside of msdb. Closes #898.
> #898 sp_BlitzBackups fixing missing db name prefix

- sp_BlitzBackups.sql
Fix dynamic SQL looking for encrypted backups
Fix product version variable population
Fix check for encrypted backups to only run on 2014+
Fix dynamic SQL to add the encryptor_type column to the fake msdb table if it doesn't already exist (fun fact: try/catch doesn't work with alter table)
Fix dynamic SQL in data mover to exclude the encryptor_type column based on production version
> Sp blitzbackups 906

- sp_DatabaseRestore.sql
After reviewing it seems like I missed quite a few places where this
should have gone.  Fixed them and now debug 0 executes, debug 1 prints
commands for the doubtful dba and debug 2 prints the other stuff one
might use during development
Fixes #923 
Reworked dem debug statements so they actually work 
You can test via the automated test script in the SQL-Server-First-Responder-Kit\Documentation\Development folder
> Fixes Issue #923

- sp_BlitzIndex.sql
This changes the logic of the missing index filter to take into account
table creation time. If a table or partition was created more recently
than the last server reboot, we shouldn't judge missing index benefit
going that far back. For example, if someone uses partitioned views and
they have daily or weekly tables, etc.
> Closes #937

- sp_AllNightLog_Setup.sql
Oops, forgot to set a non-zero severity level when we exit. Using 16.
For #1010.
> #1010 sp_AllNightLog_Setup exit w/severity if fails to stop jobs

- sp_Blitz.sql
Closes #1008
--Print only CheckIds
`EXEC dbo.sp_Blitz @CheckUserDatabaseObjects = 1, @CheckServerInfo = 1, @Debug = 1`
--Print CheckIds and any dynamic SQL used in a variable. Some of these are not printed because they're passed in as strings to MS_foreachdb.
`EXEC dbo.sp_Blitz @CheckUserDatabaseObjects = 1, @CheckServerInfo = 1, @Debug = 2`
> Adds debug modes to sp_Blitz

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Fixes #962  .
- Added in a new temp table #fnTraceGettable so that we're not pulling data multiple times from sys.fn_trace_gettable
- Also added @TraceFileIssue for error checking
- Added a try/catch block to insert data into #fnTraceGettable from sys.fn_trace_gettable using default trace file. If this succeedes then set @TraceFileIssue = 0, if it fails set @TraceFileIssue = 1
- Checks that used to use sys.fn_trace_gettable now use #fnTraceGettable.
- Skip any checks that depend on #fnTraceGettable if @TraceFileIssue = 1
- On line 242 where we set @base_tracefilename, break the file name (e.g. change "+ '\log.trc' ;" to "+ '\log. trc' ;") by adding a space
- Once that trace file name is broken then execute sp_Blitz, you should …
> sp_Blitz - Fix for #962 - Failure of sys.fn_trace_gettable

- sp_Blitz.sql
I think principal_id should always be 1 for SA (even if they’ve renamed
SA.) Closes #1043.
> #1043 sp_Blitz don't warn on SA-owned endpoints

- sp_BlitzIndex.sql
nchar and varchar fields were reporting the wrong data type lengths.
Closes #1068.
> #1068 sp_BlitzIndex - fixing field length bug

- sp_Blitz.sql
Ignores SQLPERF LOGSPACE and a few other normal events. Closes #1062,
#1074, #1075.
> #1062 sp_Blitz ignore normal DBCC events

- sp_foreachdb.sql
Fixes #1077
- Don't automatically pre-pend and post-pend `%` to the supplied `@name_pattern` (and leave it to the user to decide)
- Install `sp_foreachdb`
- Create databases with names `C12345`, `ABC12345`, and `C12345DEF`
- Execute `sp_foreachdb` with a `@name_pattern` parameter `'C[0-9][0-9][0-9][0-9][0-9]'`
+ Verify only `C12345` is matched
- Execute `sp_foreachdb` with a `@name_pattern` parameter `'C[0-9][0-9][0-9][0-9][0-9]%'`
+ Verify only `C12345`, and `C12345DEF` are matched
- Execute `sp_foreachdb` with a `@name_pattern` parameter `'%C[0-9][0-9][0-9][0-9][0-9]'`
+ Verify only `C12345`, and `ABC12345` are matched
- Execute `sp_foreachdb` without a `@name_pattern` parameter
+ Verify all three databases are matched
- Drop …
> Support prefix or suffix database selection by pattern

- Documentation/sp_BlitzFirst Checks by Priority.md
- sp_BlitzFirst.sql
If max server memory > 1.5 * target memory, either max memory is too
high, or the server is under external memory pressure. Closes #1092.
> #1092 sp_BlitzFirst warn on low target memory

- sp_AllNightLog.sql
- sp_AllNightLog_Setup.sql
By default, we now use DatabaseBackup.@ChangeBackupType = ‘MSDB’, which
does a full backup if one isn’t in msdb backup history. Closes #1005.
> #1005 sp_AllNightLog - make ChangeBackupType db-driven

- sp_DatabaseRestore.sql
Raise access denied error instead of failing silently.
Show the path in the error.
> Add access denied check to sp_DatabaseRestore.sp_DatabaseRestore

- sp_BlitzIndex.sql
> #1160 sp_BlitzIndex skip non-readable AG secondary databases

- sp_BlitzFirst.sql
A few of the checks were using SYSDATETIMEOFFSET instead of
SYSDATETIME. Closes #1106.
> #1106 sp_BlitzFirst a few checks shouldn't use SYSDATETIMEOFFSET

- sp_BlitzFirst.sql
Ignores monitoring gaps over 60 minutes, file & wait stat data that
decreases instead of increases in one pass. Closes #1154.
> #1154 sp_BlitzFirst delta views skip inaccurate data

- sp_BlitzFirst.sql
If someone set max memory higher than the box actually has, ignore it.
Closes #1212.
> #1212 sp_BlitzFirst fixing false alarm on low target memory

- sp_Blitz.sql
Fixes #1207  .
Updated 'Last good DBCC CHECKDB over 2 weeks old' to exclude read only databases.
- Run against an instance that contains a read only database which has been in this state for > 2 weeks and check it doesn't appear on the list.
- Run against an instance that hasn't had a successful DBCC CHECKDB for at least 2 weeks, ensure it displays an error.
> Read only databases incorrectly listed as not having had a DBCC CHECKDB - #1207

- sp_AllNightLog.sql
Would make it look like there was nothing to restore if there were no errors.
Fixes #1243
Remove where clause that prevented restores
Hopefully you won't have to
Offloading testing to client facing issue.
> Remove faulty where clause

- sp_AllNightLog_Setup.sql
This lets you set all databases added to the backup_worker table to get a full or diff before a log first
Fixes #1244 
Adds two BIT variables to setup: `@FirstFullBackup` and `@FirstDiffBackup`, both set to 0 by default. 
If you change them to 1, the DEFAULT orientation of `full_backup_required` and/or  `diff_backup_required` in `dbo.backup_worker` are set to 1.
Run setup with new variables.
```
EXEC master.dbo.sp_AllNightLog_Setup @RPOSeconds = 30,
@RTOSeconds = 30,
@BackupPath = N'F:\Backup',
@RestorePath = N'F:\Backup',
@Jobs = 1,
@RunSetup = 1,
@EnableBackupJobs = 0,
@EnableRestoreJobs = 0,
@FirstFullBackup = 1,
@FirstDiffBackup = 1,
@Debug = 1;
```
- Case-sensitive SQL …
> Adds configurable first full and diff params

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Closes #1253
- Check correct column in warnings rollup
> Fixes spool check

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Closes #1256
- Changes index mod check join to query hash from sql handle
> Fixed index mod query

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Fixes #1261 
Adds missing index details to sp_BlitzCache and sp_BlitzQueryStore.
Run a query with am missing index that has an impact >70%, you should see a new clickable column with the request.
Supports queries with multiple requests, and puts the highest impact queries first.
> Issue 1261

- sp_DatabaseRestore.sql
The following parameters are used to restore databases in standby mode.
@StandbyMode = 1
@StandbyUndoPath = 'PathToWriteUndoFileTo'
Generate a Full backup with Ola Hallengrens scripts. Restore that backup with the following:
EXEC dbo.sp_DatabaseRestore 
@Database = ''LogShipMe'', 
@BackupPathFull = ''\\StorageServer\LogShipMe\FULL\'', 
@BackupPathLog = ''\\StorageServer\LogShipMe\LOG\'',
@StandbyMode = 1,
@StandbyUndoPath = ''D:\Data\'',
@ContinueLogs = 0, 
@RunRecovery = 0,
@Debug = 0;
Generate some log backups with Ola Hallengrens scripts. Restore the log backups with:
EXEC dbo.sp_DatabaseRestore 
@Database = ''LogShipMe'', 
@BackupPathFull = ''\\StorageServer\LogShipMe\FULL\'', 
@BackupPathLog = …
> Add standby mode for log restores to sp_DatabaseRestore

- sp_BlitzQueryStore.sql
Also wraps schema and proc names in quotename because i like brackets
Fixes #1210 
Adds schema prefix to proc name column
Run BQS where it detects a stored proc and it should also correctly identify the schema.
BQS is 2016+ only
> Adds schema prefix

- sp_BlitzLock.sql
Can hit a specific XE session file that captures deadlocks.
Fixes #1275 
Enables parameter to hit a specific XE session file that contains deadlock information.
Start an XE session that captures deadlocks, capture some deadlocks, point proc to the file holding the session data, ex. `'c:\temp\deadlocks*.xel'` 
> Adds path parameter

- sp_BlitzIndex.sql
We were raising it with severity 0, but now do 16 to make it clear that
data won’t be complete. Closes #1187.
> #1187 sp_BlitzIndex raise error for >100 partitions

- sp_BlitzIndex.sql
Was only counting the number of indexes with lock waits. Closes #1138.
> #1138 sp_BlitzIndex correcting number of NCLs on blocked indexes

- sp_BlitzLock.sql
Fix default param for @EventSessionPath
Change display column ordering
Fixes #1289 
- Fix default param for @EventSessionPath
- Change display column ordering
- Adds object level deadlock wait times
- Should hit system health session by default now
> Fixes #1289

- sp_BlitzLock.sql
Fixes #1294 
When we pull then out of XML, the length should be 1000 to be safe (db + schema + proc name)
When we give the more info query for BC, we need to remove db + schema
We should add a line for BQS to be fair
We should report on the number of times each stored proc has been involved in a deadlock
- Call proc on a server where stored procs are involved in deadlocks
> Issue 1294

- sp_Blitz.sql
When deadlocks are recorded since startup. Closes #1295.
> #1295 sp_Blitz tells you to run sp_BlitzLock

- sp_Blitz.sql
Converts stuff to BIGINT to avoid the overflow error.
Fixes #1310
- Adds `(CONVERT(BIGINT, f.size * 8)` to avoid overflow.
- Run code on a server with big data files, it seems.
> Fixes #1310

- sp_BlitzIndex.sql
For forwarded fetches warning. Closes #1311.
> #1311 sp_BlitzIndex add ALTER TABLE REBUILD command for heaps

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Fixes #1316
- Tidies up implicit conversion/compile value code
- Call either one where stored procs that have compiled values are in cache, the clickable column should be populated for all of them.
> Issue 1316

- sp_Blitz.sql
This will take care of the large file size overflow error.
Fixes #1310 
- Do division instead of multiplication, format the results a little
- Be @CferMN
> Fix and format

- sp_BlitzCache.sql
Replaces text added to QueryType in second insert.
Fixes #1327
- Add replace to second insert to #stored_proc_info
- Don't be a dummy like me.
> Fixes #1327

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Removes variable name predicates from NOT EXISTS clause.
Fixes #1329
- Stop matching on variable name, insert everything.
- Requires running in Debug mode to validate correct inserts.
B
> Fixes #1329

- sp_BlitzIndex.sql
Fixes # 1337
- added DATA_Compression = ? to output of create index statements
- 
- 
- execute sp_BlitzIndex
- 
- 
> issues_1337/Jason

- sp_Blitz.sql
Add Windows version
Fixes #1341 
- Add new Windows version to case expression
- Run on Windows Server 2016
> Fixes #1341

- sp_BlitzIndex.sql
Adds check for indexes with bad read:write ratio
Also using this PR to make sure everything has an approproate semi-colon. It's not fun to write code that errors our because one is missing.
Fixes #1344 
- Adds check for NC indexes with 10x write:read ratio
- Properly terminates all statements with a semicolon
- Run against a database that has indexes which are heavily written to, but not heavily reads from:
> Fixes #1344

- sp_BlitzFirst.sql
Closes #1367
- Adds `CXCONSUMER` to known waits
- Run this doggy on a a server that registers CXCONSUMER waits
> Add CXCONSUMER to known waits

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
First stab at detecting power plans. Will likely need some attention down the line.
Also updates the blitz priority checks doc.
Fixes #1359 
- Adds check for power plans
- Update checks foc
- Run with `@CheckServerInfo = 1`
> Adds power info

- sp_BlitzCache.sql
Fixes #1366 
- This makes a metric butt detritus of changes to sort by the new tempdb spill columns available in SQL Server 2017
- It also probably breaks logging to table horribly. Sorry.
- Be on 2017
- Have tempdb spills
> Issue 1366

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Fixes #1382  .
- Added check 212 that checks for multiple instances of SQL Server running on one box
- Updated documentation on sp_Blitz
- Install sp_Blitz on a machine with more than one instance of SQL Server running
- EXEC sp_Blitz @CheckServerInfo = 1
- You should see a priority 250 check for instance stacking
- SQL Server 2016 SP1 (13.0.4001.0) - it's the only one i could find with multiple instances
> sp_Blitz - Check for Instance Stacking - Fixes #1382

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Closes #1386
- Adds a check for dynamic cursors, which can inhibit parallelism
- Write code with some awful cursors.
- Note that there's a difference between request and actual cursor types in the xml. Even if you're asking for a `FORWARD_ONLY` cursor, you may end up with keyset or something else.
> Adds check for dynamic cursors

- sp_BlitzCache.sql
Closes #1380
Removes crack pipe.
- Fix spill math to divide total spills by executions
- 
- 
- Run on some spilly queries
> Fix spill math

- sp_BlitzCache.sql
Fixes #1379
- Add tempdb spill analysis 
- Add spill columns to help output
- Run when a query has spilled on average >500 mb
> Issue 1379

- sp_Blitz.sql
Fixes #1393  .
- correct name of default XE session
- start one XE session
- verify single non-default XE session is running by executing` SELECT name FROM sys.dm_xe_sessions`
- run sp_Blitz
- look for CheckID 176 (it should not be there)
- start one additional XE session
- verify there are two XE sessions running
- run sp_Blitz
- verify that CheckId 176 is present with Priority 200
> Issue 1393 corrected name of default XE session

- sp_BlitzLock.sql
I added a proc level recompile, and I had missed a couple recompile hints on updates and deletes. Fixes #1398
I also added check level filtering for all the variables in the proc. Not every table has all of the possible filtering elements, so counts will look a little bit off. I suppose I could look into making a "wide" table to work off of, but I'm okay with this for now. Fixes #1395
- Add recompile hints
- Add filtering to checks
- 
- Have some gnarly deadlocks
> Adds filtering and recompiling

- sp_BlitzCache.sql
This was incomplete, missing 2017.
Fixes #1402
- Memory grant columns should be present in 2017
- Run on 2017, sort by memory grants
> Memory grant version check

- sp_Blitz.sql
sp_Blitz was written to check the oldest Backup Start Date, but the informational messages displayed were using the lowest Backup Set ID, which is not necessarily the oldest backup.
- ORDER BY backup_start_date, not backup_set_id
- clear all backup history up to 59 days ago
- restore a database with backup history older than 60 days ago
- look at the backup_set_IDs and marvel at the fact the newest IDs actually have the oldest dates
> sp_Blitz - Fix Oldest Backup Set Date and ID assumptions

- sp_Blitz.sql
Thought I'd attempt a proto-cleanup of the sp_Blitz.
I know that whitespace styles are hotly debated and up to each person's preference, but guessed I could get rid of the worst offenders that most people tend to agree on: trailing spaces and extra newlines.
Let's see how this goes down... :-)
- Remove trailing spaces
- find places with 3 or more CR/LFs in a row and cut them down to 2
- run it to replace normal sp_Blitz
- carry out as many different runs of sp_Blitz as human-machinely possible
> sp_Blitz: Remove trailing spaces and surplus CR/LFs (newlines)

- sp_Blitz.sql
In a number of places, we were losing Unicode precision in database names. It was first reported for a check on Query Store being disabled, but I found it in other places, too.
Definitely a flaw since we have database name as Unicode in other spots. Reported by @ktaranov
Fixes #1416 
- Case database name as Unicode string in a bunch of places that we weren't doing it already to retain characters. 
- `CREATE DATABASE ಠ_ಠ`
- Run `EXEC dbo.sp_Blitz @CheckUserDatabaseObjects = 1,                
@CheckServerInfo = 1`
> Fixes #1416

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Fixes #1421
- Correct math for index spool check
- Index spools should now have more accurate cost and row counts
> Fix for index spool stuff

- CONTRIBUTING.md
- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Enhancement #1407.
- Check if the owner of a database is an existing user
Sometimes if you execute sp_helpdb you see databases which have no current database owner.
Mostly because the owner of the database was an administrator which has left the company, eg:
name | db_size | owner
--------- | --------- | ---------
dbname | 2284.13 MB | \~~ UNKNOWN ~~
This check reports those databases so you can give the database a proper owner like the 'sa' user.
- Create a new Windows account. 
- Create a new SQL account for this Windows account. 
- Create a test database with this SQL account as owner of the test database.
- Delete the new SQL account.
- Delete the new Windows account.
- Execute sp_helpdb to see that the owner is Unknown.
- …
> Check for database with Unknown owners

- sp_Blitz.sql
For Sophos stuff with 8.3 names. Closes #1424.
> #1424 sp_Blitz - catch another dangerous DLL name

- sp_BlitzFirst.sql
If timing is really close between end-of-pass checks. Closes #1429.
> #1429 sp_BlitzFirst gets stuck waiting

- sp_Blitz.sql
Added 2016 pre-SP1 and 2017 pre-RTM. Closes #1441.
> #1441 sp_Blitz update unsupported builds list

- sp_BlitzFirst.sql
Fixes #1412 
- Use INFORMATION_SCHEMA.TABLES instead of INFORMATION_SCHEMA.SCHEMATA to check BlitzCache output table exists before querying it
- Use QUOTENAME() on the table name when deleting BlitzCache history (this doesn't get applied to the variable as sp_BlitzCache applies it)
- In a clean database (or one where the specified BlitzCache table does not exist) run sp_BlitzFirst with output table parameters.
- Specify a value for @outputtablenameblitzcache with non-standard characters (i.e. spaces - [Blitz Cache]
NB: Second attempt at the pull request, branched from dev & merging to dev so hopefully this one looks ok.
> sp_BlitzFirst - BlitzCache Ouput Table Checks - Fix #1412

- sp_BlitzIndex.sql
Makes the `details` column a MAX.
Fixes #1449
- Changes the details column to nvarchar(max) to get around longer computed column definitions. 
- write some absurdly long computed column definitions  
> Widen table definition

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Your mom
Fixes #1445
New code will check plans for the following ickies:
- Where clauses that call an intrinsic (system) function, or contain an IF branch
- Joins that contain an expression [Expr____]
- LIKE operators that lead with a wildcard
```
USE StackOverflow
SELECT COUNT(*)
FROM dbo.Users AS u
WHERE LEN(u.DisplayName) > 30;
GO 
SELECT COUNT(*)
FROM dbo.Users AS u
WHERE DATEDIFF(DAY, u.CreationDate, u.LastAccessDate) > 365;
GO 
SELECT COUNT(*)
FROM dbo.Users AS u
WHERE DATEADD(DAY, 365, u.LastAccessDate) <= GETDATE();
GO 
DECLARE @i INT = 22656
SELECT COUNT(*)
FROM dbo.Users AS u
WHERE u.Id = @i OR  @i IS NULL;
SELECT COUNT(*)
FROM dbo.Users AS u
WHERE u.Id = COALESCE(@i, u.Id);
SELECT COUNT(*)
FROM dbo.Users AS u
WHERE …
```
> Issue 1445

- sp_BlitzCache.sql
Fixes #1438 
- Roll up tempdb spills to stored procs
- Just like the other roll ups, this will attribute all the sub statements in a proc's tempdb spills to the calling proc
> Issue 1438

- sp_BlitzBackups.sql
Closes #1425
- Adds time zone to columns pushed across yada yada
- Be one of those crazy people centralizing backup information. Bask in the glory of your populated time zone column.
> Add time zone to inserts

- Documentation/sp_Blitz Checks by Priority.md
- Documentation/sp_BlitzFirst Checks by Priority.md
- sp_Blitz.sql
- sp_BlitzFirst.sql
- sp_BlitzWho.sql
Fixes #1459
- Adds checks for implicit transactions to Blitz, BlitzWho, and BlitzFirst
- While working on this, I found some mis-numbered CheckIds in Blitz and corrected those
- Took the opportunity to give BlitzFirst a semicolonoscopy. Used SQL Prompt. No manual labor here.
- See relevant demos in the issue - #1459
> Add checks for implicit transactions

- sp_DatabaseRestore.sql
Fixes #1181 
- The database to be restored may already exist, and be in-use.
- In my personal use case I have spammy 3rd party apps that run as db_owner.
- The safest way (for me) to ensure a restore is to drop, but other use-cases exist: single user and kill connections
This adds an option via paramater @existingdbaction to
- 0 do nothing
- 1 set single user
- 2 kill connections
- 3 drop database (implies kill connections)
- Try each flag
> Issue 1181 single kill drop

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Fixes #1457 .
The blitzcache check has been tested on (remove any that don't apply):
- Case-insensitive SQL Server instance
Unfortunately I don't have a server with querystore enabled to test this on
> add check for fast forward cursors

- sp_Blitz.sql
It's now "Always On" with a space for the marketing term, and the tech is called "Availability Groups", so I've pedantically made a pull request for this.
I'd be just as happy if this says "AG" if you're worried about string length, but we can't say "AlwaysOn" or "Always On" in CheckID 85.
> Renamed AlwaysOn to Availability Groups

- sp_Blitz.sql
SQL Server 2012 and higher has `SERVERPROPERTY('ProductUpdateLevel')`, and now that SQL Server 2017 doesn't use service packs anymore, it would be useful to know this value.
- Added `SERVERPROPERTY('ProductUpdateLevel')` to CheckID 85
> Added Cumulative Update value for CheckID 85

- sp_BlitzLock.sql
Fixes #1469.
- Count the number of distinct `event_date` values for each object, rather than the name (which will always be 1?).
- See this sqlfiddle: http://sqlfiddle.com/#!18/e26d5/1
> Fix sp_BlitzLock reports only 1 total deadlock for each object

- sp_Blitz.sql
For databases created in the last 2 weeks. Closes #1466.
Fixes # 1466.
- Check 68 (Last good DBCC CHECKDB over 2 weeks old) skips databases created in the last 2 weeks. This also includes newly restored databases.
- Create a database, and then run sp_Blitz. It should skip the priority 1 warning for "Last good DBCC CHECKDB over 2 weeks old" for that newly created db.
> #1466 sp_Blitz skip checkdb

- sp_Blitz.sql
- add a "!" mark to the end of a message
- CaPiTaLIzE "Instant File Initialisation"
- fix "thresholf" typo
Tested on
> sp_Blitz: Fix "thresholf" typo within "Bad Trace Flags enabled" check.

- sp_DatabaseRestore.sql
Updates to sp_DatabaseRestore to make key statements execute through sp_CommandLog
call sp_DatabaseRestore
Verify that all key restore statements are logged in the CommandLog table.
SQL Server 2017
> Update sp_DatabaseRestore for issue #1436

- sp_Blitz.sql
- sp_BlitzFirst.sql
For sp_Blitz, sp_BlitzFirst. Closes #1482.
Fixes #1482.
- In sp_Blitz @CheckServerInfo = 1, the wait stats checks now point to SQLskills (but not poison waits)
- In sp_BlitzFirst @ExpertMode = 1 or @SinceStartup = 1, the wait stats section links now point to SQLskills
- In sp_BlitzFirst's headline news result set, non-poison waits point to SQLskills
> #1482 point wait stats to SQLskills

- sp_Blitz.sql
Fixes #1483
- Adds CPU speed check info to power mode info
- Run on any ol' server
> Adds CPU speed to power mode check

- sp_DatabaseRestore.sql
I had some developers add a memory-optimized table which broke my automated restore operations using this wonderful tool.  Adding a new parameter and an extra WHEN ... THEN ... to the CASE statement which builds the @MoveOption string seems to solve the issue.
- Restore any database with a "FILESTREAM Data" File Type
Fixes #1480
> Add ability to move files of type 'S'

- sp_Blitz.sql
Fixes # 1497 .
- Add the line to filter LiteSpeed DBCC PAGE commands from being returned in the DBCC Events findings group.
- Execute a Litespeed backup and execute sp_Blitz, Litespeed events should disappear.
> Enhancement #1497

- sp_Blitz.sql
Fixes #1494
- Add DBCC AUTOPILOT to the list of ignored dbcc types.
- Well, you could run some dbcc autopilot commands, or run DTA. Neither one sounds fun.
> Ignore DBCC AUTOPILOT

- Documentation/sp_BlitzCache Checks by Priority.md
- sp_BlitzCache.sql
Fixes #1489 
- Puts certain checks under the `ExpertMode` parameter.
- Also made a few tweaks to checkids and priority numbers
- Adds a file of Checks to the documentation folder
- Default mode (Expert =0) should be a bit faster
- Running in Expert = 1 should, in some cases, give you extra warnings.
> Issue 1489

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Added updated syntax for create index scripts in sp_BlitzCache (lines 1369,1370) and sp_BlitzQueryStore (lines 930,931). I have tested this on 2008R2 thru 2016 instances.
> issue1505_js0505

- sp_Blitz.sql
Divides number of deadlocks by days uptime. Days uptime code was lifted from sp_BlitzIndex. Assuming it's cool to use here, too.
Fixes #1456 
- Divides number of deadlocks by days uptime.
- Run on a system with deadlocks, I suppose.
> Fixes #1456

- sp_BlitzIndex.sql
Fixes #1509
- Change `column_name` to `NVARCHAR(MAX)`.
- Be an absolute madman with more than 4k characters of column names in a stats object.
> Increase column length

- sp_BlitzIndex.sql
Fixes #1513
Makes sp_BlitzIndex unicode compatible.
- Makes stuff work with Unicode. 
```
CREATE DATABASE ಠ_ಠ
CREATE SCHEMA ಠ_ಠ
CREATE TABLE [ಠ_ಠ].[ಠ_ಠ] ([ಠ_ಠ] int)
CREATE INDEX ಠ_ಠ ON ಠ_ಠ.ಠ_ಠ (ಠ_ಠ)
EXEC dbo.sp_BlitzIndex @DatabaseName = N'ಠ_ಠ'
```
- Amazon RDS
- Azure SQL DB
> NVARCHAR-ification

- sp_BlitzWho.sql
Probably going to hell for this.
Fixes #1531 
- Add a column with a targeted free proc cache command. 
- f5 in Expert Mode.
> Add free proc cache column

- sp_BlitzCache.sql
Fixes #1522 
Fixes #1525 
- Change warnings table ordering
- Change wording for Busy Loops to match
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Issue 1522 1525

- sp_BlitzWho.sql
Fixes #1527
- Fix wait time aggregation bug
- Have normal looking wait stats
> Fixes wait time exaggeration

- sp_BlitzIndex.sql
It's the end of the case as we know it and I feel fine.
Fixes #1532 
- Move an end a little
- 
- 
- 
- Amazon RDS
- Azure SQL DB
> Fixes #1532

- sp_BlitzCache.sql
Fixes #1543 
- 2016 SP2 back ported a bunch of query plan stuff, like tempdb spills, stats used, and row goals. BlitzCache will collect those now.
- Be on 2016 SP2 and have some query problems, yo.
> Issue 1543

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Fixes #1544
- BQS will now throw all the same warnings, etc.
- Adds ExpertMode to BQS to match BC
- Tidies up code in some spots
- Accounts for bug with trivial plans and unmatched indexes
- Checks for > 3 executions before determining parameter sniffing
- BQS should be a lot faster and match what BC outputs
> BQS parity with BC

- sp_Blitz.sql
Fixes #1474
- Adds code to make sure memory nodes are unbalanced. By itself, auto soft numa might split things into odd numbers of cores.
- Have a really weird server.
> Add Joe's nonsense

- sp_Blitz.sql
Closes #1552
- Add `'sp_server_diagnostics session'` to the list of ignored XE sessions. I'm keeping both permutations in there because I have a feeling both exist out in the world. 
- Run Blitz, see if it correctly ignores system XE sessions.
> Fix session name list

- sp_Blitz.sql
This ~MHz key seems to be more consistent (between manufacturers) than the ProcessorNameString key
Fixes #1560.
- Add a space (for formatting) to the output of the CPU check
- Change registry key being read for processor speed from "ProcessorNameString" to "~MHz" in order for this check to display the right information for AMD processors as well as Intel
- Slightly changed the phrasing of what's displayed when you're in an unknown (customized) power mode
- I changed "...and is in Unknown!" to "...and is in an unknown power mode." just because I thought it read a little better.  I can change it back if needed
- run the updated sp_Blitz with the CheckServerInfo setting on PCs with both Intel and AMD processors
- Verify the Power …
> sp_Blitz AMD processor support

- sp_BlitzLock.sql
Since they are already reported in the object deadlock results
Fixes #1569.
- As the issue mentioned, this filters out index deadlocks on heaps from the final results (check id 2)
- Run `sp_BlitzLock` on a system with object deadlocks on a heap
- Observe that they are now filtered excluded from the final "index deadlock" results
- ~~Case-sensitive SQL Server instance~~
- ~~SQL Server 2014~~
- ~~SQL Server 2017~~
- ~~Amazon RDS~~
- ~~Azure SQL DB~~
Same deal here in terms of testing as on #1572 (since I was just updating a WHERE clause).  Here's a before and after from my system:
**Before:**  
**After:**
> Filter out heaps from index deadlock results

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
Fixes #1577
- Populate set options and variable info for statements
```
USE StackOverflow
CREATE INDEX ix_yourmom ON dbo.Users (Reputation, Age)
DBCC FREEPROCCACHE
DECLARE @sql NVARCHAR(MAX) = N'SELECT COUNT(*) AS records 
FROM dbo.Users AS u 
WHERE u.Reputation >= @Reputation
AND u.CreationDate >= @CreationDate
AND u.DisplayName LIKE @DisplayName';
EXEC sys.sp_executesql @sql, N'@Reputation INT, @CreationDate DATETIME, @DisplayName NVARCHAR(40)', 
@Reputation = 2, @CreationDate = '2016-01-01', @DisplayName = '%user%';
```
> Add info for statements

- sp_Blitz.sql
Closes #1583.
- In checkid 203, added '%DBCC%USEROPTIONS%' to the list of ignored events. 
> #1583 sp_Blitz ignore dbcc useroptions

- sp_BlitzFirst.sql
Fixes #1571 
A non-default-parameter call like this should not fail:
EXEC sp_BlitzFirst
@OutputDatabaseName = 'DBAtools'
, @OutputSchemaName = 'testschema'
, @OutputTableName = 'Blist'
, @OutputTableNameFileStats = 'BlitzFirileStats'
, @OutputTableNamePerfmonStats = 'Blist_PerfmonStats'
, @OutputTableNameWaitStats = 'Blirst_WaitStats'
, @OutputTableNameBlitzCache = 'Blithe'
> Fix hard coded value #1571

- sp_BlitzIndex.sql
0-3 NC indexes now called "Under-Indexing", 10+ called "Over-Indexing." Closes #1588.
> #1588 sp_BlitzIndex clearer aggression

- sp_Blitz.sql
To remove dupes of same schema/proc. Closes #1592.
> #1582 sp_Blitz adding DISTINCT

- sp_BlitzInMemoryOLTP.sql
Displays instance-level and database-level attributes related to In-Memory OLTP.
Fixes # .
- 
- 
- 
- EXEC sp_BlitzInMemoryOLTP
- 
- 
- Azure SQL DB
> Initial version of this script. Purpose is to report on the state of the memory-optimized environment.

- sp_BlitzCache.sql
Fixes `Warnings` column values generated by `sp_BlitzCache` so that they no longer start with space.
`SUBSTRING(warnings, 2, 200000)` in `sp_BlitzCache` right now only removes the initial comma, but we also want to remove the initial space so that the resulting value won't start with space as the first character. It's an easy to make mistake as the `SUBSTRING` function actually starts counting from 1 and not 0 (as usual in other languages).
- Change `SUBSTRING(warnings, 2, 200000)` to `SUBSTRING(warnings, 3, 200000)`.
> Fixed SUBSTRING on sp_BlitzCache Warnings

- sp_Blitz.sql
Changes the time comparison to minutes to avoid arithmetic overflow in `DATEADD`
Fixes #1600
- Change `DATEADD` to:
`DATEADD(MINUTE, (-1. * (@MsSinceWaitsCleared) / 1000. / 60.), GETDATE())`
- Run this on a machine with a lot of uptime where stats were cleared a long time ago, or something?
> sp_Blitz Arithmetic overflow line 59

- sp_BlitzInMemoryOLTP.sql
Fixes #1608 . 
Graceful exit for unsupported SQL versions.
- 
- 
- 
- EXEC sp_BlitzInMemoryOLTP
- 
- 
- Azure SQL DB
> Added graceful exit for unsupported SQL versions.

- sp_Blitz.sql
If Power Plan was set by group policy, the value is in a different registry key. Look for this one first.
Fixes #1620 .
- Grabs value from group policy registry location if it exists. Otherwise, grabs local.
GROUP POLICY LOCATION:
HKLM\SOFTWARE\Policies\Microsoft\Power\PowerSettings\ActivePowerScheme
LOCAL LOCATION:
HKLM\SYSTEM\CurrentControlSet\Control\Power\User\PowerSchemes\ActivePowerScheme
- Run against an instance that has a power plan of "high performance" set by GPO (Windows Group Policy), but "balanced" or "power saver" set locally. The fixed version will not tell you that you have a 'power saver' or 'balanced' plan when you have "high performance" set by GPO. 
SQL 2008 …
> Get Power Plan value from proper location in registry

- sp_BlitzQueryStore.sql
Fixes #1627.
- Alter ENGINEEDITION check for Azure SQL from <> 5 to NOT IN (5,8)
- EXEC sp_BlitzQueryStore on Azure SQL MI and return expected results instead of an error message when run on DB compatibility <= 130
- Case-sensitive SQL Server database
- Azure SQL Managed Instance
> Correct EngineEdition check for Azure SQL MI

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
If SqlServerVersions table is available. Closes #1631.
> #1631 sp_Blitz Cumulative Update check

- sp_BlitzFirst.sql
Fixes #1623 
- Added a WHERE clause to exclude Log Shipping Restore tasks from the procedure.
- Just run sp_blitzFirst.
- Case-sensitive SQL Server instance 
- SQL Server 2008 R2 - YES
- SQL Server 2012 - YES
- Amazon RDS
- Azure SQL DB
> issue 1623 #fix

- sp_BlitzIndex.sql
Get latch and io waits from op stats
Closes #1626
Adds to Mode 2 output. 
- page_latch_wait_count
- page_latch_wait_in_ms
- page_io_latch_wait_count
- page_io_latch_wait_in_ms
- Run BlitzIndex in Mode 2 for one or all databases.
> Add more columns from ops

- sp_Blitz.sql
Skipping extended stored procedure calls. Closes #1643.
> 1643 sp_Blitz Amazon RDS compatibility

- sp_DatabaseRestore.sql
Fixes # 1645
- Added the `@Execute` flag.  The default is `Y`
- Set `@Execute` to `N` and set `@Debug` to `0` or `1`.  At `0` the procedure will only print the commands needed to paste for the restore, dbcc and drop.  At `1` the procedure will print helpful debug info along with the restore commands.
> Issue 1645

- sp_DatabaseRestore.sql
Fixes #1657 .
Use CommandExecute not EXEC for @ExistingDBAction parameter
Run normally with @ExistingDBAction > 0
> Issue 1657 Use CommandExecute not EXEC for @ExistingDBAction parameter

- sp_Blitz.sql
Being stealthy. Closes #1664.
- in check 78 (alerting on procs with recompile), ignore procs that start with sp_AllNightLog.
- Have sp_AllNightLog installed on a server, run the old sp_Blitz. It'll complain about the recompile. Then run it with this new code, and those warnings will be gone.
> #1664 sp_Blitz ignore AllNightLog recompiles

- sp_BlitzCache.sql
Fixes #1666
- Adds SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; to queries that touch system tables or global temp tables 
- Oh just run the thing
> Adds read uncommitted

- sp_DatabaseRestore.sql
Fixes # 1673.
- Fix for @StandbyMode=1
EXECUTE [DBADB].[dbo].[sp_DatabaseRestore]
@database = 'SOURCE',
@RestoreDatabaseName = 'DEST',
@BackupPathFull = '\BACKUP\SQL\BLA\FULL',
@BackupPathLog = '\BACKUP\SQL\BLA\LOG',
@MoveFiles = 1,
@MoveDataDrive = 'F:\SQLData',
@MoveLogDrive = 'G:\SQLLog',
@ContinueLogs = 1,
@RunRecovery = 0,
@StandbyMode = 1,
@StandbyUndoPath = 'G:\SQLLogship',
@ExistingDBAction = 2,
@debug = 1;
> Fix @StandbyMode=1 (#1673)

- sp_BlitzFirst.sql
If CheckServerInfo = 0. Closes #1680.
- Adds new @CheckServerInfo parameter, defaulting to 1 (to mimic existing proc behavior.)
- Before returning results, if @CheckServerInfo = 0, delete #BlitzFirstResults table where FindingsGroup = 'Server Info'. (So no, it's not technically skipping the checks - but if someone wants to write a more robust way of doing this, they're welcome to.)
> #1680 sp_BlitzFirst skip server info

- sp_Blitz.sql
Changes code to not use old system view that is erroring when user has an id over smallint.
Fixes # 1695
-  stop using sysmembers system view in check 86
- Have a user with a id over 32,767
- run sp_Blitz
> Fix Arithmetic Overflow from old system view

- sp_BlitzFirst.sql
- sp_BlitzIndex.sql
Fixes # #1679
some tab to space adjustments
some reformatting
add a parameter @output parameter or the handling of a "NONE" value for this parameter
same as usual should give the same result as usual
set @OutputType to NONE alone will make it fail
set @OutputType to NONE with @OutputTableName to something will store the results to the output table
Case-sensitive SQL Server instance
SQL Server 2014
> Add sp_Blitz's parameter @OutputType to sp_BlitzIndex and sp_BlitzFirst BIS

- sp_BlitzFirst.sql
... Rather than a static list.
Closes #1708
- Check global temp table for ignorable waits rather than a static list.
- Should be transparent to end user.
> Use temp table waits

- sp_Blitz.sql
Fixing typo in "Tables in MSDB" check, closes #1719.
> sp_Blitz typo in MSDB table check

- Install-All-Scripts.sql
- sp_AllNightLog.sql
Fixes #1727 .
- uses ignore_database column in restore_worker table to filter out databases.
- Set ignore_database to 1 and verify that it does not get selected for restore.
> Actually use the ignore_database field.

- sp_BlitzWho.sql
Fixes #1721 .
- Added SQL Server 2017 (and future SQL Server versions) to the list of versions that return memory grant info.  No SP or CU level required.
- Run this on SQL Server 2017 and make sure memory grant information is properly returned
Has been tested on:
> sp_BlitzWho now returns memory grant info for SQL 2017

- Install-All-Scripts.sql
- Install-Core-Blitz-No-Query-Store.sql
- Install-Core-Blitz-With-Query-Store.sql
Install scripts had the right sp_Blitz contents, but just didn't include the new version number.
> Fixing version number on sp_Blitz

- sp_BlitzCache.sql
Fixes #1747  .
- Wrap MaxCompileMemory in a CASE statement to avoid those pesky DIV/0 errors
- Find a server that chucks errors on the pre-fix version and try this new one :)
> Divide by Zero Error Fix - BlitzCache

- sp_BlitzIndex.sql
Fixes #1739
Fixes # .
- Make mode 0 generally more useful to people
- Run in @Mode = 0, see important stuff that was missing before
> Make Mode 0 more useful

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Fixes #1753 .
- add a check for alerts that NEVER send out their event details via email/pager
EXEC msdb.dbo.sp_add_alert @name = N'DEBUG - No Event Details included :-('
,@message_id = 0
,@severity = 10 --harmless?
,@enabled = 1
,@delay_between_responses = 600 --seconds
,@include_event_description_in = 0 -- 0 = I do NOT want free Event Details in my error messages...
,@job_id = N'00000000-0000-0000-0000-000000000000';
--do we get a "Monitoring - Alerts Without Event Descriptions" line for the alert?
EXEC [dbo].[sp_Blitz] @IgnorePrioritiesBelow = 200, @IgnorePrioritiesAbove = 200
--remove your alert when done testing:
--EXEC msdb.dbo.sp_delete_alert @name=N'DEBUG - No Event Details included :-('
Has been tested on (remove any …
> sp_Blitz - new check for alerts that NEVER send out their event details via email/pager

- sp_BlitzIndex.sql
Also format numbers better.
Closes #1759
Fixes # .
- Increase length of casted integer, and apply some formatting to make long numbers easier to read.
> Fix length

- sp_Blitz.sql
Added read uncommitted to all of the sp_MSforeachdb calls. Fixes #1790.
> 1790 Blitz blocking - added read uncommitted to sp_MSforeachdb calls

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Changing recent-restart to checkid 221. Fixes #1785.
> #1785 sp_Blitz duplicate checkid

- sp_BlitzFirst.sql
Added ServerName to windowing functions and group by for multi-server repositories. Fixes #1789.
> #1789 sp_BlitzFirst delta views for multiple servers

- sp_Blitz.sql
New check 219 wasn't being skipped on RDS. Fixes #1801.
> #1801 sp_Blitz skip alerts on RDS

- sp_Blitz.sql
Update build number we look for for unsupported builds. Closes #1813.
> sp_Blitz - SQL 2012 SP3 is unsupported

- Documentation/sp_BlitzFirst Checks by Priority.md
- sp_BlitzFirst.sql
Improves compatibility with Azure SQL DB, plus adds new check 41 looking at sys.dm_db_resource_stats to tell you if you're being throttled due to your DTU level. Closes #1808.
- Azure SQL DB
> 1808 sp_BlitzFirst Azure SQL DB compatibility

- sp_ineachdb.sql
Fixes #1824.
- Fix typo in sp_ineachdb.sql where sp_foreachdb was being referenced.
- Run `sp_ineachdb.sql` on a server twice that does not contain `sp_foreachdb` - it will now run without error.
> Fix typo in sp_ineachdb.sql

- sp_BlitzWho.sql
Adds parameters for OutputDatabaseName, OutputSchemaName, OutputTableName. Might even work.
- SQL Server 2019
- Azure SQL DB
> 1773 sp_BlitzWho: add output to table

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Adds cpu, memory limits when CheckServerInfo = 1. Closes #1837.
- Azure SQL DB
> #1837 sp_Blitz add Managed Instance info

- sp_BlitzIndex.sql
Fixes #1846
- Grab some check constraint info, alert if the definition looks like a scalar valued function
- Create scalar udf, create check constraint based on it
> Add check constraint info

- sp_Blitz.sql
Closes #1853
- Ignore RedGate SQL Monitor
- You know...
- Amazon RDS
- Azure SQL DB
> Ignore SQL Monitor

- sp_BlitzFirst.sql
Closes #1849
- Ignore CLR waits
- CLR waits should no longer show up in sample
- Amazon RDS
- Azure SQL DB
> Re-ignore CLR waits

- sp_BlitzLock.sql
- sp_BlitzQueryStore.sql
BQS and BL now work better.
Fixes #1859 
- BQS skips sys.master_files queries
- BL throws a more helpful error.
- Use Azure/MI
- Amazon RDS
- Azure SQL DB
> Azure helpfulness

- sp_BlitzIndex.sql
Add check for filtered indexes missing filter definition columns
Closes #1880
- Add check for filtered indexes missing filter definition columns
- Create an index like this `
CREATE INDEX ix_whatever_filtered ON dbo.Users (Reputation) WHERE UpVotes > 0 AND DownVotes > 0;` and it should get picked up.
> Add check for filtered indexes missing filter definition columns

- sp_BlitzIndex.sql
Closes #1883
- Fix false positives on NC/PK
```
CREATE TABLE dbo.HeapsOfSadness (Id1 INT IDENTITY(1,1), CustomeRID INT, Stuffing CHAR(1000),
CONSTRAINT PK_Id1 PRIMARY KEY NONCLUSTERED ([Id1] ASC));
GO
--CREATE CLUSTERED INDEX [CLIX_CustomeRID] ON [dbo].HeapsOfSadness (CustomeRID);
GO
INSERT INTO dbo.HeapsOfSadness (CustomeRID, Stuffing)
SELECT 1, 'Stuff' /* Short */
FROM sys.messages;
GO
```
Toggle creating the CX.
> Fix false positive on NC PKs

- sp_BlitzIndex.sql
Closes #1877
- Add server and uptime info to results
- Run in any mode or examine a single table
> Add server and uptime info to results

- sp_BlitzFirst.sql
Closes #1869
- ignore xe dispatcher waits
- Nothing really
> Ignore XE wait

- sp_BlitzLock.sql
Closes #1876
- Add collation modifiers
- Should no longer error out when user databases have a different collation than tempdb.
> Add collation modifiers

- sp_foreachdb.sql
Fixes #1893 
- Properly close branch for @Help = 1
- Update help text to display correct description of the intended functionality of the stored procedure.
- exec sp_foreachdb @Help = 1; -- Should only show corrected Help info
- exec sp_foreachdb @command = 'select top 100 [name] from sys.tables;' -- Should only execute command
> Update Help Code Branching

- sp_BlitzIndex.sql
When @TableName is specified and sys.dm_db_stats_histogram is available. Closes #1900.
- SQL Server 2019
> 1900 sp_BlitzIndex add histograms

- sp_BlitzFirst.sql
Fixes # 1910.
- Add the same SQL Server version check as in sp_BlitzCache for the @BlitzCacheSortOrder parameter.
- If it fails the check, don't set @BlitzCacheSortOrder to 'memory grant'.
- Kinda tricky to test as you'd need an older SQL Server instance that can trigger CheckID 34.
> Issue 1910

- sp_BlitzIndex.sql
Dropping severity level from 16 to 0 since we're logging it in the result set anyway. Closes #1914.
> #1914 sp_BlitzIndex partition error severity

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Don't just rely on EC2 VM name to detect RDS. Also adds a new result noting that checks were skipped. Closes #1925.
- Amazon RDS
> #1925 sp_Blitz AWS RDS detection

- sp_BlitzIndex.sql
GetAllDatabases = 1 fails when it hits rdsadmin because they're referring to the resource db. Closes #1927.
> #1927 sp_BlitzIndex skip rdsadmin db

- sp_BlitzIndex.sql
Check for DaysUptime is null. Closes #1933.
- Azure SQL DB
> #1933 sp_BlitzIndez Azure SQL DB

- sp_BlitzFirst.sql
Fixes #1940 .
- changed three values to now display as decimals
- run sp_BlitzFirst @expertmode = 1
- check that batch requests/sec, waits per core per second both show as decimals now.
> sp_BlitzFirst - Decimals - Fixes #1940

- sp_BlitzLock.sql
Fixes #1950.
- Skip sysjobs query on Azure SQL DB Hyperscale.
- Azure SQL DB Hyperscale
> 1950 sp blitz lock azure sql db hyperscale

- sp_BlitzIndex.sql
Can only get stats if you're in the database you're analyzing. Closes #1947.
- SQL Server 2019
> #1947 sp_BlitzIndex stats for current db

- sp_BlitzIndex.sql
Fixes #1952 
- Move two columns in the INSERT query to the correct location based on the SELECT query
- Run sp_BlitzIndex with 
```SQL
exec master.dbo.sp_BlitzIndex @GetAllDatabases = 0, 
@Mode=2,
@DatabaseName = 'dba',
@OutputDatabaseName = 'dba', 
@OutputSchemaName = 'dbo',
@OutputTableName = 'T_BlitzIndex_Results',
@BringThePain = 1
```
> #1952 sp_BlitzIndex Fix INSERT query column order

- sp_BlitzIndex.sql
Fixes #1938  .
- modified the CREATE INDEX scripts to remove table name and fix capitalisation
- run sp_BlitzIndex in default mode (on a database that has high value missing indexes) and check the 'create tsql' column in the output, it should be IX_ColumnNames_Includes (if includes is applicable)
> sp_BlitzIndex - CREATE INDEX script modifications - Fixes #1938

- sp_AllNightLog.sql
- sp_AllNightLog_Setup.sql
- sp_Blitz.sql
- sp_BlitzBackups.sql
- sp_BlitzCache.sql
- sp_BlitzFirst.sql
- sp_BlitzInMemoryOLTP.sql
- sp_BlitzIndex.sql
- sp_BlitzLock.sql
- sp_BlitzQueryStore.sql
- sp_BlitzWho.sql
- sp_DatabaseRestore.sql
- sp_foreachdb.sql
- sp_ineachdb.sql
Fixes # .
- In sp_BlitzInMemoryOLTP => changed internal variable name from @Version to @MSSQLVersion
- In all stored procs, added @Version VARCHAR(30) as OUTPUT parameter
- In all stored procs, added @VersionCheckMode BIT which when set to 1 ends almost directly the SP
Call each SP as usual
Call each SP with @VersionCheckMode = 1
For instance:
DECLARE @BlitzCacheVersion     VARCHAR(30);
DECLARE @BlitzCacheVersionDate DATETIME2;
EXEC dbo.sp_BlitzCache @VersionCheckMode = 1, @Version = @BlitzCacheVersion OUTPUT, @VersionDate = @BlitzCacheVersionDate OUTPUT ;
SELECT @BlitzCacheVersion as BlitzCacheVersion , @BlitzCacheVersionDate as BlitzCacheVersionDate
- Case-sensitive SQL Server …
> Add Version Checking  for all SP

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Fixes #1943 
- Updates to sp_Blitz to include check 224 - Check for SSIS/SSRS/SSAS on box
- Updated documentation
- 
- find a box with either SSIS/SSRS/SSAS running (also needs xp_cmdshell enabled) and run sp_Blitz with @CheckServerInfo = 1. You should see a priority 200 - Performance message about this.
I didn't have a relevant link to supply on this so i've just left it as brentozar.com
> Fixes #1943 - sp_Blitz check if SSIS/SSRS/SSAS are running

- sp_BlitzCache.sql
Fixes #1945  .
- additional plural checks
- raised error level to 16 if an incorrect @SortOrder is used
- removed some redundant checks.
- run sp_BlitzCache @SortOrder = ''. you should get an error message 16 in the messages tab if you pass in an incorrect sort order. 
- It will also catch more plurals. Feel free to use the code below for a quick test.
```
DECLARE @SortOrder varchar(20) = 'avg'
SET @SortOrder = LOWER(@SortOrder);
SET @SortOrder = REPLACE(REPLACE(@SortOrder, 'average', 'avg'), '.', '');
SET @SortOrder = CASE 
WHEN @SortOrder IN ('executions per minute','execution per minute','executions / minute','execution / minute','xpm') THEN 'avg executions'
WHEN @SortOrder IN ('recent compilations','recent …
```
> sp_BlitzCache additional plural checks for @SortOrder

- sp_Blitz.sql
Fixes #1964  .
- fixed typo on RAISERROR to report correct check
- run sp_Blitz @CheckServerInfo = 1, look for check 153, the next one should be 222 rather than 114
> sp_Blitz - minor typo

- sp_Blitz.sql
SQL 2012 pre-SP4 is out of support. Closes #1967.
> #1967 sp_Blitz updating supported versions

- sp_BlitzIndex.sql
Skips the high/low benefit stuff. Closes #1991.
> #1991 sp_BlitzIndex simplify missing indexes

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Add warning for rows in sys.index_resumable_operations. Closes #2010.
> #2010 sp_Blitz paused online index operations

- sp_BlitzCache.sql
Instead of checking version numbers, look at sys.all_columns for the grant and spill columns. Closes #2015.
> #2015 sp_BlitzCache sorting in Azure SQL DB

- sp_Blitz.sql
Addresses #1994 
Tested on SQL Server 2008 R2 and 2014 with missing components.
I added the schema name in the equation because I'm transferring all the First Responder Kit objects to another schema (FirstResponderKit) with a custom PS script. 
It's possible, for instance for testing purpose, that objects resides in both 'FirstResponderKit' and 'dbo' schemas.
The main idea here was to generate the set of commands to be executed so that the overhead of adding a new object is minimal.
As I'm writing, it would also be easy to add to this check the capability to pinpoint depreciated components (like sp_BlitzTrace), but this would be the subject of another pull request.
> First responder consistency check

- sp_ineachdb.sql
The END for IF @Help = 1 was in the wrong place, making the procedure a no-op *unless* you also specify @Help = 1.
> Add END in the right spot for IF @Help = 1

- sp_BlitzLock.sql
Skips update stats with options that RDS doesn't support. Closes #2037.
> #2037 sp_BlitzLock support for AWS RDS

- sp_Blitz.sql
fixes #2047 
To test: install sp_Blitz and run
EXEC sp_Blitz @OutputType = 'XML'
It should run normally except the output is XML.
Tested on SQL Server 2014
> add @OutputType = 'XML' to sp_Blitz

- sp_DatabaseRestore.sql
Pull request for issue #2081 - sets the database owner after the restore has happened.
> Set DBOwner after restoring database

- sp_BlitzCache.sql
- sp_BlitzFirst.sql
Fixes #2072 
Temp table added (#ReadableDBs) this table is populated with all read intent database id's which is used to filter out these database when querying against dm_exec_requests or sessions with a cross apply against a plan cache function.
> #2072 - sp_BlitzFirst, sp_BlitzCache - Exclude Read intent secondary databases

- sp_BlitzIndex.sql
When saving columnstore definitions to table, trim them to 4000 characters to avoid an overflow. Closes #2076.
> #2076 sp_BlitzIndex columnstore to table

- sp_BlitzFirst.sql
Casting RAM as a BIGINT instead of INT. Closes #2060.
> @2060 sp_BlitzFirst 2TB RAM

- sp_BlitzCache.sql
This SQL 2019 & Azure SQL DB feature isn't ready yet, so disabling til Microsoft is ready. Closes #2022.
> #2022 sp_BlitzCache disabling air_quote_actuals

- .gitattributes
TSQL is being misclassified as PLpgSQL for repo:
Adding linguist overrides to `.gitattributes` file solve this issue but after editing one of the affected files to force a refresh.
See more details here https://github.com/github/linguist/issues/4622
> Add linguist overrides for correct syntax highlighting

- sp_BlitzFirst.sql
Filtering for sql_text not like %alter index%'. Closes #2062 with duct tape.
> #2062 sp_BlitzFirst false alarm on index reorgs

- sp_BlitzCache.sql
Fixes bug in AirQuoteActual plans, plus if plan cache is 75% new as of today, raise priority 1 warning. Closes #2052.
> #2052 sp_BlitzCache prioritization

- Documentation/sp_BlitzCache Checks by Priority.md
- sp_BlitzCache.sql
This will flag any select queries that have caused writes, with a few boundaries:
- They're not already flagged by the index spool check
- They're not already flagged as a "big spill" in 2016+ where supported
This should catch things discussed [here](https://dba.stackexchange.com/questions/191825/).
Some notes:
- Doc for BlitzCache was updated
- Also adds all the necessary warning-generation code
- This changes the `##BlitzCacheProcs`, so you'll have to update it in the collector
- I added placeholder URL to a dba.se question, but feel free to replace that if you'd like when local content is available
> Issue 2063 selects with writes

- sp_BlitzCache.sql
Grabs top 10 highest cpu consuming plans with highest count of query hashes (multiple plans), and runs BlitsCache to find them.
Some quick notes:
- Doesn't change anything for the collector
- Adds a new sort order! Documentation for `@Help` was updated to reflect
- Adds a GOTO 👎 
- I added a self-imposed query requirement to group by database id, to avoid queries with the same hash that run in multiple databases which may be parameterized, etc.
- The rest is pretty self-explanatory: BlitzCache is re-executed with all passed in parameters, and the list of query hashes gathered
- Sort order is not passed to the calling block to prevent an infinite loop 💯 💯 💯 
- Sort order defaults back to cpu, but I'm fine with that changing (or if you want a `@SecondarySortOrder` parameter)
> Issue 2051 query hash sort

- Uninstall.sql
Fulfills request #2080
Deletes all the FirstResponderKit procedures from the current DB or all DBs via parameter
> Added Uninstaller Script

- sp_BlitzCache.sql
If the AirQuoteActual plan is longer than the regular plan, use it. Closes #2109.
> 2109_sp_BlitzCache_AirQuoteActuals

- sp_BlitzIndex.sql
I have problem when I run sp_BlitzIndex on database with different collation to tempdb. And found problem on step that script casts int to nvarchar. Casting will create different collation to temp table, and it causes exception when sorting.
I fixed it by remove casting. int can be concatenated to nvarchar without casting.
> Fix Cannot resolve collation conflict between "Language_A" and "Language_B" in add operator occurring in ORDER BY statement column 3.

- sp_BlitzQueryStore.sql
I've added in a new parameter which sets the database ID to what it is in `sys.databases`, rather than using the result from `DB_ID`, as this can differ in Azure SQL DB and the docs advise using `sys.databases` for comparisons. (Documented [here](https://docs.microsoft.com/en-us/sql/t-sql/functions/db-id-transact-sql?view=sql-server-2017))
Comparisons for the check on whether or not query store is enabled are then done just using the DatabaseName and DatabaseID variables and comparing them with the values in `sys.databases`.
There are possibly other places those functions will be causing problems in Azure, but having tested this change I at least managed to get this working correctly and the script will now run on a readable secondary and return the query store results from the primary. …
> #2136 Fix BlitzQS DB Name Comparison for Query Store Check.

- sp_BlitzIndex.sql
Now ignores the old is_low column. Closes #2143.
> #2143 sp_BlitzIndex missing index sort

- sp_Blitz.sql
Unused heaps were reported as used.
See https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2149
> corrected fix for issue #2149

- README.md
To show sp_BlitzIndex support for OutputTableName is only for Mode = 2. Closes #2190.
> #2190 update readme

- sp_BlitzFirst.sql
Fixes bug where we were always repopulating WaitCategories. Closes #2208.
> #2208 sp_BlitzFirst repopulating WaitCategories table

- sp_Blitz.sql
Fixes #2221 (version checks for SQL Server 2008/2008 R2/2016 SP1).
Adds a pre-RTM check for 2019 (in line with the existing one for 2017).
Also includes syntax updates for support/supported, and only include minor version point ('.') when returning minor version number.
> Update unsupported version checks in sp_Blitz (#2221)

- sp_BlitzIndex.sql
Handles multiple rows in sys.dm_db_index_operational_stats for columnstore indexes that aren't partitioned. Fixes #2228.
> #2228 sp_BlitzIndex columnstore accuracy

- sp_BlitzWho.sql
If the server has >50GB RAM, add a 5% max grant hint. Working on #2238.
> #2238 sp_BlitzWho add max grant hint

- Documentation/sp_BlitzCache Checks by Priority.md
- sp_BlitzCache.sql
Making the warning names in the description result set match what we're showing in the Warnings column. Closes #2212.
> #2212 sp_BlitzCache matching warning names

- Documentation/sp_Blitz Checks by Priority.md
- sp_Blitz.sql
Adding check for database properties: is_broker_enabled and is_honor_broker_priority_on
Those 2 non default config database properties (and also database property is_trustworthy_on) are not set when restore a database or attach database (after detach).
> 2187 Adding checks for 2 non default config database properties

- sp_Blitz.sql
If you have 50+ databases, set the multiple plans warning threshold to be 2x the number of databases. Closes #2249.
> #2249 sp_Blitz multiple plans threshold

- sp_BlitzCache.sql
Setting output table constraint name to be the table's name rather than a newid. Closes #2252.
> #2252 sp_BlitzCache avoid plan cache pollution

- sp_BlitzFirst.sql
Removing a redundant line in a check. Closes #2218.
> #2218 sp_BlitzFirst typo

- sp_DatabaseRestore.sql
Dependencies for dbo.CommandExecute and dbo.DatabaseIntegrityCheck have been removed. Calls to these stored procedures have been replaced with sp_executesql and DBCC CHECKDB respectively. Closes #2269
> #2269 sp_DatabaseRestore Remove Ola Dependency

- sp_BlitzIndex.sql
This pull request SHALL HERETOFORE:
* Add a parameter to disinclude indexes with no reads OR writes, meaning they are totally inactive
* De-clutter the select list a little bit so it matches the rest of the statement
Totally inactive indexes will still be listed when:
* You override the default parameter value
* You're in mode 1, 2, or 3
* The `@TableName` parameter is not null
RE The last one: I figure if you're zooming in on a table, you want everything, and who knows? Maybe there's a filtered index on there that hasn't been touched at all?
Closes #2280
> Issue 2280: Skip 0 read, 0 write indexes

- sp_BlitzIndex.sql
Working on #2268. Uses decimal(38,0) for #IndexColumns.last_value, seed_value, and increment_value.
> @2268 sp_BlitzIndex giant last values

- sp_Blitz.sql
If they had it turned on, and databases have roundabort on, temporarily set it off while processing, then turn it back on when we're done. Working on #2302.
> #2302 sp_Blitz numeric roundabort

- sp_Blitz.sql
Changed `SERVERPROPERTY('EngineName')` to be `SERVERPROPERTY('EngineEdition')` on Line 876. As far as I can tell, "EngineName" is an invalid option that always returns `NULL`. This causes the `IF` condition to always use the `ELSE` portion, which should only be used for "Azure Managed Instance"s. According to the documentation for the "[SERVERPROPERTY](https://docs.microsoft.com/en-us/sql/t-sql/functions/serverproperty-transact-sql)" function, it's the "EngineEdition" option that returns "8" for "Azure Managed Instance". Changing this on my system gets this to work as expected.
> Invalid option for CheckID 1 of sp_Blitz

- sp_BlitzCache.sql
Add a check for USERSTORE_TOKENPERM if >30% of the plan cache is an hour or less old.
Compare the cache size to the size of the buffer pool.
If it's >10%, add a warning to the end results.
> Issue 2134

- LICENSE.md
In the license, fix "undre" because it was bothing tf out of me.
Also noticed two spots that list copyright year as 2019, even though main copyright statement is 2020. Fix that too.
> fix a typo ("undre") + update year in 2 spots

- Documentation/sp_Blitz_Checks_by_Priority.md
- sp_Blitz.sql
New check in sp_Blitz, warn if file has a logical name of master. Closes #2352.
> #2352 new rule for master files

- sp_BlitzFirst.sql
Skip sys.dm_exec_requests that are hitting fileproperty. Closes #2350. Don't judge me.
> #2350 sp_BlitzFirst reduce false positives for CHECKDB

- sp_BlitzCache.sql
Add link to /go/noplans when the plan is missing from cache. Closes #2347.
> #2347 sp_BlitzCache link for no plans

- sp_BlitzCache.sql
Now uses sys.dm_os_memory_clerks instead of sys.dm_os_buffer_descriptors. Closes #2345.
> #2345 sp_BlitzCache faster memory analysis

- sp_BlitzCache.sql
Moving to top of proc, making sure we don't run into problems with the variables not being declared in case we use 'em elsewhere. Anal retentive, I know. Related to #2372.
> #2372 sp_BlitzCache declares

- sp_BlitzCache.sql
Widen Finding column to 500 characters. Closes #2398.
> #2398 sp_BlitzCache error truncation

- sp_BlitzCache.sql
Fixing truncation warnings in sp_BlitzCache and making the single-use plan warning have a dynamic threshold. Closes #2398 with a bang.
> 2398 take two

- sp_BlitzFirst.sql
When updated-stats check fires, save the output in the HowToStopIt column since that's XML, allows for longer output. Closes #2413.
> 2413 sp_BlitzFirst stats readability

- sp_Blitz.sql
Don't throw a warning about the NAV license table in the master database. Closes #2426.
> #2426 sp_Blitz exclude NAV license table

- sp_BlitzWho.sql
Added a @Platform variable to determine 'Azure' or 'NonAzure' so it can be used in a CASE statement to provide "Program Name" in downstream code.  This fixes sp_BlitzWho and sp_BlitzFirst (which uses sp_BlitzWho) when run against an Azure SQL DB using @ExpertMode = 1.
> sp_BlitzWho - Add Platform to allow running against Azure SQL DB

- sp_BlitzFirst.sql
See long explanation in #2420 discussion.
The short version: row_count < estimate_row_count *10000 leads to alot of false positives, as for instance 7 < 5*10000 while 7 vs 5 is a completly okay estimate.
Also, since the DMV is populated on the fly, I do not see fixing the logic to do a cardinality estimate check in this "direction" as an option as row_count will in the beginning of the execution be very low(sometimes 0) which will then always cause an incorrect red flag, just because it has not had time to process yet. 
Row count > estimate_row_count*10000 is always an incorrect warning so that still makes sense.
Removing this section caused me to no longer be able to reproduce the blaming of sp_blitzfirst that the issue is about which I could before(on 2019).
> Removing incorrect logic from @Bad_Estimate check. Issue #2420

- sp_DatabaseRestore.sql
> sp_DatabaseRestore should still open the BackupFiles Cursor when @StopAT and @OnlyLogsAfter are specified - testing needed

- sp_BlitzCache.sql
Moved LOWER(@SortOrder) earlier in the proc so ensure that all comparions against @SortOrder are compared in lowercase.
> #2482 - Move LOWER(@SortOrder) earlier in the proc

- sp_BlitzWho.sql
Changed the wait_info column to check that the status is not not sleeping , if not sleeping return the wait time otherwise return NULL.
> #2465 Do not accrue wait time for sleeping spids

- sp_BlitzLock.sql
> 2452 Fixes sp_BlitzLock object names with periods

- sp_BlitzCache.sql
On older versions of SQL Server, the calculation was incorrect. Closes #2487.
> #2487 sp_BlitzCache USERSTORE_TOKENPERM

- sp_BlitzCache.sql
Our single use plan math wasn't quite right. Changed the source DMV and added a filter for just compiled plans. Closes #2480.
> 2480 sp_BlitzCache single use plan math

- sp_BlitzWho.sql
Version of the script
SELECT @Version = '7.97', @VersionDate = '20200712';
What is the current behavior?
If a session running a parallel query is blocked it does not show as being blocked.
If the current behavior is a bug, please provide the steps to reproduce.
/* Query window 1 , Blocking query*/
BEGIN TRAN
UPDATE Users
SET Reputation = Reputation +1
WHERE Id < 100
--ROLLBACK
/* Query window 2 , Parallel query blocked by Query window 1 */
SELECT Location,COUNT(*)
FROM Users
GROUP BY Location
/* Query window 3, run sp_BlitzWho and obeserve the blocking_session_id column */
EXEC sp_BlitzWho;
The blocking_session_id column will show as NULL for Query window two, now if you stop query two and replace it with:
(Single threaded query on my laptop)
SELECT TOP 1 *
FROM Users
run this and then …
> 2489 parallel blocked processes not showing a blocking session

- sp_BlitzIndex.sql
Having another go at #2227.
I've added 3 new columns to `#missingindexes` so you can list the columns with data types and columns without.
Also noticed it only works for SQL 2017+ (not 2016 as I previously thought) due to use of `STRING_AGG`.
I wouldn't mind having another crack at getting rid of `STRING_AGG` use `FOR XML PATH`. If it's not too hard, that'll make this compatible with 2016+.
If you have a simple `string_split` replacement then I can add that as well, but everything I've seen says to use a user defined function, which I don't think this script would want to do.
> Issue 2227- sp_BlitzIndex show datatypes on missing indexes

- sp_ineachdb.sql
Fixes #2507. Added `is_distributor` to the #temp table so we could filter out `distribution` as a system database. A couple other minor formatting edits.
> Add support to treat distribution as system db

- sp_BlitzIndex.sql
Because mode 0 isn't new anymore. Closes #2509.
> #2509 sp_BlitzIndex remove "new"

- sp_BlitzIndex.sql
Switched from NVARCHAR(4000) to NVARCHAR(MAX). Closes #2512.
> #2512 sp_BlitzIndex longer missing index datatypes

- sp_Blitz.sql
sp_validatelogins not allowed on Amazon RDS. Closes #2526.
> #2526 sp_Blitz skip validate logins on RDS

- Documentation/sp_Blitz_Checks_by_Priority.md
- sp_Blitz.sql
Fixes #2525 by adding a check for inconsistent metadata between master's is_query_store_on in sys.databases and the actual state of the query store according to the database-specific QS metadata. 
I was able to test with this hacky-AF approach:
```
CREATE DATABASE test_qs;
ALTER DATABASE test_qs SET OFFLINE;
--copy the mdf/ldf
ALTER DATABASE test_qs SET ONLINE;
ALTER DATABASE test_qs SET QUERY_STORE = ON;
ALTER DATABASE test_qs SET OFFLINE;
--restore the (old) mdf/ldf
ALTER DATABASE test_qs SET ONLINE;
--run sp_blitz and check for finding
DROP DATABASE test_qs;
```
(Also tweaked an outdent on an IF in the same check area)
> Add check (235) for inconsistent query store metadata

- sp_BlitzCache.sql
Changing unqualified join to a cross apply (as Microsoft data migration wizard complains about it "Starting with database compatibility level 90 and higher, in rare occasions, the 'unqualified join' syntax can cause 'missing join predicate' warnings, leading to long running queries.").  There may be more but there was an awful lot of "from"s to look through in the SP so only spotted this one.
> Update sp_blitzcache to remove unqualified join

- sp_BlitzFirst.sql
#2548 Within the CheckId 44 code block we now set lock timeout = 0 , in the foreachDB we Try/catch and if we get an error we report the error handling error 1222 (timeout) with a slightly different message and finally set lock timeout back to default of -1. we only show these rows when there are actually updated statistics to show as it is a priority 50 we don't want false alarms.
> sp_BlitzFirst - CheckID 44 gets blocked when an index operation is in progress

- sp_Blitz.sql
Resolves #2557
Using sys.dm_os_volume_stats, adds the extra information on all drives that have SQL Server files on them. Also adds the disk name if there is one. For versions before 2008R2 SP1, will just keep the current information provided by xp_fixeddrives.
- Changed the temp table structure
- Used Dynamic SQL for pre-2008R2 SP1 and Azure compatibility for the update
- Changed reporting to GB (to make it consistent with the Data Size check, and because GB seemed the proper disk size unit in 2020)
- Added number formatting for 2012+ to make large disk sizes more readable
Couldn't find a way to remove Master..xp_fixeddrives without using Powershell and that didn't feel like a better solution. One way would be to remove "non SQL Server" drives from sp_Blitz but thats for you to decide, …
> Sp blitz disk size

- sp_Blitz.sql
Does an existence check on a DMV rather than a version check, and fixes the available space bug, and only runs for <=100 files. Closes #2557.
> #2557 sp_Blitz drive space reporting

- Documentation/sp_BlitzFirst_Checks_by_Priority.md
- sp_BlitzFirst.sql
#2505 - Added a new check (CheckID 46) to check for running queries with a memory grant greater than x% with x being a new parameter @MemoryGrantThresholdPct which defaults to 15.00.
If a query is identified whilst running sp_BlitzFirst you will get a row per query with priority 100 which includes the Grant size, Percent , sql handle, sql text and xml query plan.
> sp_BlitzFirst - #2505 Warn when there are running queries with a memory grant exceeding x% of the workspace 

- sp_Blitz.sql
Take 2. Runs even if you didn't have snapshot backups because we might have a lot of small databases, under the 50GB threshold for check 178. Working on #2581.
> #2581 sp_Blitz too many snaps

- sp_BlitzIndex.sql
Visualize columnstore layouts in table-level output, include dictionary sizes. Working on #2584.
> #2584 sp_BlitzIndex columnstore

- sp_BlitzIndex.sql
Avoiding redundant result sets when a table has multiple indexes.
> #2584 sp_BlitzIndex columnstore visualization fixes

- sp_Blitz.sql
added in the 19 new database scoped configurations available in 2019.  Tested against a 2016 instance as well as 2019 and verified that the differences are found and returned in the sp_blitz output.
> #2573 add new 2019 database scoped configurations

- sp_ineachdb.sql
Change in database_list parameter block prevents runtime error `Invalid length parameter...`. 
Change repeated in exclude_list block for consistency; keep numbers CTE as short as it can be.
Change tested using: 
```
EXEC dbo.sp_ineachdb
@command = N'SELECT db = ''?'', COUNT(*) FROM sys.objects;'
,@database_list = 'master,[master],mister,SCRATCH,foobar,msdb,tempdb'
,@exclude_list = 'ping,pong,msdb'
;
```
(I have a SCRATCH database in my test environment but mister, foobar, ping, pong do not exist.)
> Debug evaluation of @database_list parameter #2621

- sp_BlitzFirst.sql
Include wait types that aren't in the ##WaitCategories table. Closes #2631.
> #2631 sp_BlitzFirst wait exclusions

- sp_BlitzLock.sql
This PR does the following:
- Adds a check to the initial XML grab to detect if the deadlock is from intra-query parallelism
- Adds a total count of parallel deadlocks to the roll-up
- Corrects missing logic from the inserts
- Attempts to grab object names for parallel deadlocks (we weren't before for some reason)
- Fixes the filtering for the results queries
- Fixes the outer applies to account for a `wait_type` that wasn't there before
Closes #2636
> Re-fix parallel deadlock stuff

- sp_BlitzWho.sql
Adding Parameter Details from Cached and Live Query Plans by stripping the data out from the XML. See Issue #2591
> Adding Parameter Details from Cached and Live Query Plans

- sp_BlitzFirst.sql
Only save the first 4000 characters of Details to the output table. Closes #2660.
> #2660 sp_BlitzFirst Details truncation

- sp_BlitzWho.sql
Padding the number of days of runtime with an extra digit. Closes #2652.
> #2652 sp_BlitzWho ordering ten day queries

- sp_DatabaseRestore.sql
We are experiencing serious slow down while restoring backups from distant datacenter, when having a lot of TRN files, because of `RESTORE HEADERONLY FROM DISK` calls on outdated TRN files.
Proposal for https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2644
This approach is naive, by filtering out TRN with names > to the last one registered in msdb.dbo.backupmediafamily.
> Adds optional @IgnoreAlreadyPresentInMsdb BIT setting

- README.md
Explaining that SlowlySearchPlansFor hits a SQL Server bug, and added new sp_DatabaseRestore parameter. Closes #2202.
> #2202 sp_BlitzCache documentation

- sp_Blitz.sql
Skip the Launchpad service. Closes #2664.
> #2664 sp_Blitz service account filtering

- sp_BlitzIndex.sql
The usage stats column currently returns misformatted data as:
`Reads: 0 Writes:0`
This will correct it to appear as:
`Reads: 0 Writes: 0`
> Add space after "Writes:" to match "Reads: " formatting

- sp_BlitzCache.sql
**Version of the script**
SELECT @Version = '7.9999', @VersionDate = '20201114';
**What is the current behavior?**
with longer tablenames script exceeds the 4k limit.
```
Meldung 102, Ebene 15, Status 1, Zeile 83
Falsche Syntax in der Nähe von ",".
```
**If the current behavior is a bug, please provide the steps to reproduce.**
```
exec sp_BlitzCache @sortorder = N'CPU', @OutputDatabaseName = N'rpinet_dbtools', @OutputSchemaName = N'dbo',
@OutputTableName = N'bc_base__cpu__20201116112511', @debug = 1
```
**What is the expected behavior?**
save data to output table
**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
* Version: 15.0.4063.15. Patch Level: RTM. Cumulative Update: CU7. Edition: Developer Edition …
> 4k limit exceeded

- sp_BlitzIndex.sql
I was not getting any columnstore visualization when running for non-default schema (by using `@SchemaName` param)
Steps to reproduce:
Create CCI table "MyTab" in "Test" schema and run 
`EXEC sp_BlitzIndex @SchemaName='Test', @tablename='MyTab'`
and you will not get any columnstore visualization
Fix:
Changed the queries to rely on `@ObjectId` which we already have instead of `OBJECT_ID(@TableName)`
> Address @SchemaName and column_id issues in sp_BlitzIndex 

- sp_BlitzIndex.sql
Issue #2693 Changed on 11/25/2020 to exclude IgnoreDatabases when counting # of databases
> sp_BlitzIndex: exclude IgnoreDatabases when counting # of databases

- sp_BlitzIndex.sql
I've changed the column order as it was suggested in #2694 
The results look ok now:
`The table [dbo].[Department] is a temporal table, with rows versioned in [dbo].[DepartmentHistory] on History columns [SysStartTime] and [SysEndTime].`
> Addressing 2694 - column order

- sp_DatabaseRestore.sql
sp_executesql was replaced by CommandExecute so there would be some logging in case of error.
> #2700 sp_DatabaseRestore added CommandExecute

- sp_ineachdb.sql
There's an insert missing from the latest version of this proc so we never actually populate #ineachdb
> Update sp_ineachdb - we forgot an insert

- sp_BlitzIndex.sql
As mentioned in the issue #2724 I'm seeing output such as this in the Drop_TSql column:
-ALTER TABLE [dbo].[TABLE] DROP CONSTRAINT [CONTRAINT_NAME];
When I paste that into SSMS its not commented. Only happens for heaps:
```
CASE 
WHEN i.is_primary_key = 1 AND i.index_definition <> ''[HEAP]''
THEN N''-ALTER TABLE '' + QUOTENAME(i.[database_name]) + N''.'' + QUOTENAME(i.[schema_name]) + N''.'' + 
```
I'd like to fix the missing - in the above. Sorry to log a bug then a PR here, not sure if that's correct proc or not. Danger will robinson: 100% newb to github.
> sp_BlitzIndex trivial typo (missing hyphen) in Drop_TSql output

- sp_BlitzWho.sql
using last_request_start_time was missing 00 padding
I believe this fixes the issue in #2721 while still sorting long sessions as expected:
> Fix issue reported in #2721 - 2nd case in COALESCE

- Install-All-Scripts.sql
- sp_BlitzIndex.sql
Encode column names for XML to prevent column names with characters that should be converted to entities from breaking the procedure.
> Encode column names for XML

- SqlServerVersions.sql
- sp_BlitzFirst.sql
Pushed @OutputTableRetentionDays to sp_BlitzWho call
> Fixes #2758 - @OutputTableRetentionDays is not applied for BlitzWho when saving BlitzFirst results to table

- sp_BlitzIndex.sql
Sort them by total rows descending instead of object name. Closes #2762.
> #2762 sp_BlitzIndex sort dupes

- sp_BlitzFirst.sql
Was looking for a minimum of 1,000 batch requests per second. Lowered that to 10 compilations, or more compilations than batch requests. Closes #2770.
> #2770 sp_BlitzFirst compilations threshold

- sp_AllNightLog.sql
Was hard-coded to 5 minutes, now pulls from the config table. Closes #2775.
> #2775 sp_AllNightLog rpo/rto

- sp_BlitzIndex.sql
From missing index DMVs in SQL Server 2019. Closes #2780.
> #2780 sp_BlitzIndex remove sample plan

- sp_Blitz.sql
Some firewalls specifically look for the string "xp_cmdshell" and terminate the connection.  Adding comments directly beside like "/**/xp_cmdshell/**/" seems to be enough to fool this behavior.
> added comments around xp_cmdshell since some firewalls block this string

- sp_BlitzFirst.sql
Only fire the compilation and recompilation warnings when we've had at least 75 compilations or recomps (because sp_BlitzFirst itself does around 50.) Working on #2770.
> sp_BlitzFirst compilations threshold

- sp_BlitzWho.sql
Related to: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2813
Change money to decimal 38,2 to resolve arithmetic overflow error when trying to read from this view when large values are involved.
> Update sp_BlitzWho to amend BlitzWho_deltas view

- sp_BlitzCache.sql
- sp_BlitzFirst.sql
Hi, 
There is a parameter in sp_BlitzFirst which tells not to out any data (@OutputType = NONE).
However, when sp_BlitzFirst calls sp_BlitzCache, then sp_BlitzCache starts generating outputs.
This pull request contains little changes to both procedures so that everything works like expected.
> Pass @OutputType = NONE from sp_BlitzFirst to sp_BlitzCache so that there is really no output

- sp_Blitz.sql
- sp_BlitzIndex.sql
This adds typically non-production databases to ignore lists in Blitz and BlitzIndex
#2787
> Add ignored databases

- Documentation/sp_Blitz_Checks_by_Priority.md
- sp_Blitz.sql
For active & inactive heaps in user databases. Low value, already visible in sp_BlitzIndex. Closes #2818.
> #2818 sp_Blitz remove checks 38 and 39

- sp_DatabaseRestore.sql
Change smallint to int to prevent arithmetic overflows. Closes #2839.
> #2839 sp_DatabaseRestore smallint

- sp_Blitz.sql
No arithmetic overflow even when your hard drive has just 8MB free. Closes #2837.
> sp_Blitz: handle 8MB free

- sp_BlitzCache.sql
In testing the scenarios mentioned in the open issue, I was able to get a correctly printed statement.
The main fix was converting the concatenated block of columns to an nvarchar(max), but I also took the opportunity to make all string assignment Unicode.
Note that the max length for object names seems to be 128 characters. If you try to use a table name that is 128 characters long, you'll get an error trying to create the primary key because it will be PK_ + 128 characters, which is over the limit.
It may also be worth changing the parameter data types for objects to sysname and adding some protection to the PK creation in case someone decides to max that out at some point.
@jeffchulg please test this to see if it solves your issue.
Closes #2816
(Hopefully)
> Fix for 2816

- sp_BlitzCache.sql
Setting the `starting_position` of the `(` found when retrieving the closing `)` will keep us out of the negative sub-string length if there is a preceding `)`.
**Test Case**
```
DECLARE @compile_time_value NVARCHAR(258) = N'1) (something)';
SELECT CHARINDEX('(', @compile_time_value) + 1 AS [SubString starting_position]
,CHARINDEX(')', @compile_time_value, CHARINDEX('(', @compile_time_value) + 1) - 1 - CHARINDEX('(', @compile_time_value) AS [SubString length]
,SUBSTRING(@compile_time_value, CHARINDEX('(', @compile_time_value) + 1, CHARINDEX(')', @compile_time_value, CHARINDEX('(', @compile_time_value) + 1) - 1 - CHARINDEX('(', @compile_time_value)) As compile_time_value;
```
SubString starting_position|SubString length|compile_time_value …
> #2847 sp_BlitzCache: Fix negative CHARINDEX result when ) precedes ( in compile_time_value.

- sp_BlitzWho.sql
#2870 Corrected casing for columns:
Query_Plan
Session_Id
cached_parameter_info
> #2870 sp_BlitzWho - Failing on case sensitive instances

- sp_BlitzWho.sql
Closes this: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2875
> Remove cached_parameter_info from insert column list on SQL2008R2

- sp_Blitz.sql
Some changes/enhancements to sp_Blitz that I found helped provide more information when running against Amazon RDS SQL Server, as well as an enhancement to check if Instant File Initialization is enabled for all versions of SQL Server. 
Changes include:
– added comments to RDS skipped checks to explain what they are and why they are skipped.
- modified code to run rdsadmin.dbo.rds_read_error_log instead of xp_readerrorlog when it’s running on an RDS server 
- commented out Insert to skip check 193 since the above code change allows it to run
- added additional query against sys.dm_server_services to confirm if instant_file_initialization is enabled if it can’t find it in the errorlog (possibly due to cycling of the errorlog)
> Update sp_Blitz.sql with minor fixes/enhancements for Amazon RDS

- sp_BlitzFirst.sql
#2876 fix timestamp ordering in the HowToStopIt column
> 2876 - Incorrect timestamp in the HowToStopIt column

- Uninstall.sql
Do not drop the table in any case but treat the table like the procedures.
Closes #2893
> Uninstall.sql - Treat the table SqlServerVersions like the procedures

- sp_BlitzWho.sql
Added 1 second lock timeout when gathering live query plans. Working on #2907.
> 2907 sp_BlitzWho lock timeout

- sp_DatabaseRestore.sql
Update sp_databaseRestore to correctly get Diff File to restore and to skip log files that need to be skipped
Fixes #2898 
I think I've cleaned up the logic to make it simpler in the future. As always, it works on my machine, but if someone could check over to make sure I haven't broken the functionality, that'd be great.
> Update sp_databaseRestore to correctly get Diff File to skip log files correctly

- sp_BlitzCache.sql
Counting plans should count plan hashes and not query hashes. We should also count items from the base view and not `##BlitzCacheProcs`
Closes #2900
> Fixes #2900

- sp_BlitzIndex.sql
This is for bug #2880 for sp_BlitzIndex.
Modified the char-based INCLUDED column definition to match how char-based key columns are displayed (i.e. {nvarchar 80} versus {nvarchar (40)}).
Added max size for non-char-based columns (i.e. {bigint 8}) for key, include, and secret columns.
> Update sp_BlitzIndex for #2880

- sp_BlitzWho.sql
Msg 102, Level 15, State 1, Procedure sp_BlitzWho, Line 1148 [Batch Start Line 3]
Incorrect syntax near ','.
Msg 102, Level 15, State 1, Procedure sp_BlitzWho, Line 1247 [Batch Start Line 3]
Incorrect syntax near ':'.
Msg 105, Level 15, State 1, Procedure sp_BlitzWho, Line 1268 [Batch Start Line 3]
Unclosed quotation mark after the character string ',
@CheckDateOverride;
END
GO
'.
> Fix error: Msg 102, Level 15, State 1, Procedure sp_BlitzWho, Line 1148 [Batch Start Line 3]

- sp_Blitz.sql
Updates check #94 to evaluate enabled jobs for failure emails regardless of whether or not there's a schedule defined. This also addresses the issue of sp_Blitz ignoring jobs with a schedule type of "Start automatically when SQL Server Agent starts".
Fixes issue #2905.
> Removed dependency on schedules for evaluating jobs w/o failure emails

- sp_BlitzIndex.sql
Resolves #2860.  Use @ShowPartitionRanges = 1 to see the new column.  Below is a summary of my testing.  Please let me know if you can think of anything else.
- int, bigint, smallint, tinyint
- date, time, smalldatetime, datetime, datetime2, datetimeoffset
- decimal, numeric
- money, smallmoney
- varchar, nvarchar
- CLUSTERED
- NONCLUSTERED
- COLUMNSTORE
- COLUMNSTORE_ARCHIVE
- Compatibility levels 100 to 150
- Partition counts from 50 to 5000
> #2860 Add partition ranges to columnstore visualization

- sp_Blitz.sql
Turning the IFI check into dynamic SQL to avoid errors on unpatched versions. Closes #2921.
> #2921 sp_Blitz Instant File Initialization

- sp_BlitzCache.sql
Change to `DECIMAL(9, 2)` to avoid overflows.
Closes #2932
> Fix #plan_usage definition

- sp_BlitzIndex.sql
Days uptime is now calculated from sys.dm_os_sys_info which works for AzureDB.  For older instances (<2008) we can fallback to create_date of tempdb.
#2933
> Fix @DaysUptime in sp_BlitzIndex for AzureDB

- sp_BlitzFirst.sql
#2941 - Added additional join clause to Check 1 so that the correct amount of backups running is shown when the database context of the backup command is ran from a user database.
> #2941 - sp_BlitzFirst Addresses incorrect number of backups running for CheckID 1

- sp_Blitz.sql
Changes which makes the sp_Blitz output table order the same as onscreen table:
`ORDER BY Priority , FindingsGroup , Finding , DatabaseName , Details`
> Update sp_Blitz.sql change order in output table same as onscreen

- Documentation/sp_Blitz_Checks_by_Priority.md
- sp_Blitz.sql
Adds a check when available (2012+) to see if target recovery interval is <> 60, and suggest setting it there.
Sure, it could be 61 or something, but I'm not going down that path.
I quoted out the current check for target recovery interval that looks to see if it's not 0 or 60, to not give seemingly conflicting advice.
Right now, the URL is to Aaron's post on the subject. @BrentOzar will need to go code it for uniformity.
I've also updated the documentation to reflect the new high check id, etc.
Closes #2938
> add target recovery interval check

- sp_Blitz.sql
Only alert for SQL Server 2016. Closes #2946.
> #2946 sp_Blitz query store rtm check

- sp_Blitz.sql
In the INSERT INTO #SkipChecks dynamic SQL statement, the WHERE clause includes:
ServerName = SERVERPROPERTY('ServerName')
This is false when the SkipChecks table is in a (linked) server with a different collation to the server on which sp_Blitz is being executed, because ServerName returns data in one collation (eg. Latin1_General_CI_AS) whereas SERVERPROPERTY('ServerName') returns data in (I believe) the current server or database collation (eg. SQL_Latin1_General_CP1_CI_AS).
Therefore, there is a need to include a COLLATE clause so that equality condition works, ie:
ServerName COLLATE DATABASE_DEFAULT = SERVERPROPERTY('ServerName')
> Fixed SkipChecks bug caused by collation mismatch

- SqlServerVersions.sql
Correct minor version number for SQL 2017 CU25 from 3410 to 3401 as indicated in https://support.microsoft.com/en-us/help/5003830
> Correct the minor version number for SQL 2017 CU25

- sp_BlitzIndex.sql
This adds `is_unique_constraint` from `sys.indexes` to a couple of the operating modes.
Note that this also adds the new column etc. to the remote server code for Mode 2 as well, and should be announced as a breaking change (of removed, whatever). I don't have a setup to test this part, but the code looks accurate.
This has been tested in modes 0-4, and I've verified that this column exists going back to at least SQL Server 2008.
Closes  #2950
> Add unique constraint awareness

- Install-All-Scripts.sql
- Install-Core-Blitz-No-Query-Store.sql
- Install-Core-Blitz-With-Query-Store.sql
- sp_BlitzWho.sql
These tests were done for the following stored procedures.
1. Should create procedure.
2. Should show new wait_resource column in both expert and non-expert modes.
3. Should add new wait_resource column and data to output table.
4. Should select new wait_resource column using BlitzWho_Deltas view.
1. Should successfully run BlitzFirst which executes BlitzWho to...
a. show new column.
b. add new column to the output table.
Are there other tests I should do to verify this change?
Tests were done on:
```
Microsoft SQL Server 2016 (SP1-GDR) (KB4458842) - 13.0.4224.16 (X64) Enterprise Edition (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: )
```
All versions of SQL Server should be good as the `wait_resource` column exists in SQL Server 2008 R2.
> Issue #2970 sp_BlitzWho - Add dm_exec_requests.wait_resource to report and output table

- sp_Blitz.sql
I was getting "This database setting is not the default" being reported for "Delayed Durability Enabled" on databases that were offline. On checking the code, I noticed that it was reporting any databases whose sys.databases.state was <> 1 (Restoring), and the state for an offline database is 6. Rather than change it specifically for offline databases (d.state NOT IN (1,6)), I thought that the code should only be reporting non-default values when the database is online (state = 0) - I hope you agree!
> Prevent DB non-default values msg for offline DBs

- sp_Blitz.sql
Reverts #3020 (rundate in markdown) because it is not needed as I found the root cause of the missing value.
Fixes #3018 (rundate in markdown) by adding COALESCE in SQL, which was the root cause.
Fixes #3022 (wrong indentation in markdown output) by adding an additional space on the second level.
Fixes #3021 (missing documentation details) by extending the parameter explanation.
> sp_Blitz - Fix issues with markdown output

- sp_Blitz.sql
In case the power plan is not managed by group policies, the tested registry key SOFTWARE\Policies\Microsoft\Power\PowerSettings is not found on the system, resulting in the message "RegOpenKeyEx() returned error 2, 'The system cannot find the file specified.'". To suppress this message, the very special parameter "@no_output = 'no_output'" can be used.
I have tested this on a system without group policies. I have not yet tested this on a system where the power plan is managed by group policies.
Fixes #2836.
> sp_Blitz: Suppress message if registry key not found

- sp_BlitzFirst.sql
Add a USE to the top of the dynamic SQL so it runs in every database. Closes #3075.
> #3075 sp_BlitzFirst stats check

- sp_Blitz.sql
Multiple log files on the same drive are OK if they're 2TB or larger. Closes #3081.
> #3081 sp_Blitz large log files are OK

- sp_BlitzFirst.sql
Avoid erasing & repopulating contents if there are MORE rows in the table than we expect. Closes #3092.
> #3092 sp_BlitzFirst WaitCategories table

- sp_DatabaseRestore.sql
Needed to change the check, as you can execute the blitz scripts from the context of another database, but the previous check would only check if the stored procedure existed in the database where the DatabaseRestore SP resided, and wouldn't check if it existed in the database you were currently using at execution (So it would fail even if the database you were using had it, as it was only checking if it existed where the toolkit was deployed).
Not sure if there was a better way to do this than dynamic SQL... But I've tested this and it resolves the issue I found at least. If there's a better method of doing this, would love to know though.
> sp_DatabaseRestore - add check for CommandExec in current database fix

- sp_DatabaseRestore.sql
Fixes one occurrence of BackUpFile instead of BackupFile that broke case-sensitive installs. Closes #3100.
> #3100 sp_DatabaseRestore BackUpFile typo

- sp_BlitzIndex.sql
Don't query missing index plans if there are over 1000. Closes #3085.
> #3085 sp_BlitzIndex too many missing indexes

- sp_BlitzCache.sql
Was dividing the max by the number of executions, instead of dividing the total. Closes #3120.
> #3120 sp_BlitzCache AvgMaxMemoryGrant

- sp_BlitzCache.sql
Using decimal(30) for total reads and writes instead of bigint. Closes #2980.
> #2980 sp_BlitzCache arithmetic overflows

- sp_BlitzQueryStore.sql
Currently @DatabaseName does not function on Azure MI as it is overridden as it is a SQL Azure product. This change allows this parameter to be used on Azure MI as it supports multiple databases.
> sp_BlitzQueryStore - Allow @DatabaseName to be used to Azure MI

- sp_BlitzFirst.sql
Retains checks for Azure SQL DB and tested to work there, but now enables it to work for Azure SQL Managed Instances as (I believe is) intended - also tested.
TLDR - looked for SERVERPROPERTY('Edition') =/<> 'Azure SQL' and updated to SERVERPROPERTY('EngineEdition') =/<> 5
> Fixes #3129 - sp_BlitzFirst in Azure SQL Managed Instances

- sp_Blitz.sql
- sp_BlitzLock.sql
This change will close #3140 if accepted and merged.
I made a very minor change to sp_Blitz and sp_BlitzLock and removed the check for ServerName because the ServerName can be changed on an RDS instance.
I tested this on 4 version of RDS and confirmed they it works after this change and confirmed on a regular EC2 instance version of SQL 2019 that it works.
> sp_Blitz and sp_BlitzLock Change so they work on RDS Instances with ServerName Changed

- sp_BlitzIndex.sql
Added missing "QUOTENAME" function around the "@Databasename" in the "USE" statement for the two statistics queries. Without it, DB names like 'my-stuff' will fail.
> sp_BlitzIndex statistics queries missing QUOTENAME in USE

- sp_BlitzWho.sql
Thanks for considering this change. The majority of the time we use sp_BlitzWho to identify blocking scenarios, and with this change these blocking chains will be easier to spot.
The code has a `@StringToExecute` where the `blocking_session_id` has been moved beside `session_id`. Since the INSERT INTO the storage table for BlitzWho also executes the statement in `@StringToExecute`, the column order in the INSERT had to be changed as well. The table schema definition remains unchanged.
```
Microsoft SQL Server 2016 (SP3-GDR) (KB5014355) - 13.0.6419.1 (X64)
May 29 2022 21:05:29   Copyright (c) Microsoft Corporation 
Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 
```
1. Verify results have new column order.
```sql
exec sp_BlitzWho;
exec …
```
> Issue #3159 - Move blocking_session_id in BlitzWho output beside session_id for easier block identification

- sp_BlitzFirst.sql
**What is the current behavior?**
When setting up sp_BlitzFirst in an agent job on a few dozen SQL 2019 with AGs, I was seeing very random periodic job failures caused by lock timeouts. I traced it down to the section where you SET LOCK_TIMEOUT 0 and then look for modified statistics.
You catch the lock timeout error inside the statistics section, but it turns out that sp_msforeachdb is also susceptible to exiting with a lock timeout. By wrapping that in a further try/catch block, I'm able to prevent the job step from failing unnecessarily.
This is nicer than having the job fail randomly, or having to set the job step to exit with success on failure.
**If the current behavior is a bug, please provide the steps to reproduce.**
I couldn't force the behaviour to happen, even wrapping …
> Prevent lock timeout thrown by sp_msforeachdb

- sp_BlitzFirst.sql
I've checked against mine and today[tm] the azure-style prefix is valid. e.g. it returns MSSQL$CCCCCCCCCCC which is a string of hex numbers.
This fixes issue #3184
> Update check for managed instances

- sp_AllNightLog.sql
Add validation check to exclude existing databases if they are not in a restoring or standby state.  Fixes known issue 'overwrites existing databases without warning.' 
Ensure ignore_database option is always respected by wrapping OR condition in brackets. 
#3187
> sp_AllNightLog - Exclude existing databases if they are not in a restoring or standby state

- sp_BlitzCache.sql
In SQL 2022 RTM when plan sensitive parameter optimization is in use, the query text for statements will be appended with (at least) one of two strings that contain the ObjectID of the parent stored procedure:
```
SELECT TOP 10000 *, dbo.UsersByReputation_Function(@Reputation) AS ReputationPlusOne  FROM dbo.Users  WHERE Reputation=@Reputation  ORDER BY DisplayName  OPTION ( PLAN PER VALUE(ObjectID = 1205579333, QueryVariantID = 2, predicate_range([StackOverflow2013].[dbo].[Users].[Reputation] = @Reputation, 100.0, 1000000.0)), USE HINT('DISABLE_TSQL_SCALAR_UDF_INLINING'))
SELECT TOP 10000 *  FROM dbo.Users  WHERE Reputation=@Reputation  ORDER BY DisplayName option (PLAN PER VALUE(ObjectID = 1157579162, QueryVariantID = 2, predicate_range([StackOverflow2013].[dbo].[Users].[Reputation] = …
```
> Add SQL 2022 RTM PSPO parsing

- sp_BlitzIndex.sql
Don't show inactive rowgroups on columnstore indexes. Closes #3189.
> #3189 sp_BlitzIndex hide tombstones

- sp_BlitzCache.sql
Save results to table if we have an unpredicted sort order. Closes #3160.
> #3160 sp_BlitzCache unused grant save

- sp_BlitzWho.sql
#3163 - Amended query_text column to get statement offsets from sys.dm_exec_requests instead of sys.dm_exec_query_stats
> sp_BlitzWho show statement text of stored procedure even when proc is executed for the first time

- sp_BlitzFirst.sql
- sp_BlitzLock.sql
SET LOCK_TIMEOUT 1000 when APPLY sys.dm_exec_query_statistics_xml to prevent mutex issues.  Set GitHub #3210
> sp_BlitzFirst SET LOCK_TIMEOUT 

- sp_BlitzFirst.sql
Check 45 looking for inaccurate query estimates was checking if the actual row count (row_count in dm_exec_query_profiles) was greater than estimate_row_count*10000. This was generating arithmetic overflow errors on queries containing estimates close to the bigint limit. Change the calculation to compare the row count/10000 to the estimate instead - same result but no overflow.
> Issue 3239: Fix dm_exec_query_profiles arithmetic overflow error in check 45

- sp_BlitzWho.sql
For invalid query start times that cause overflows. Closes #3243.
> sp_BlitzWho checking for 1900

- sp_BlitzFirst.sql
Only alert on queries running longer than 5 seconds. Closes #3253.
> #3253 sp_BlitzFirst estimation filter

- sp_DatabaseRestore.sql
Change outlined in #3262 to delete from FileList full backups that are unstriped, but also after the StopAt specified
> Remove nonstriped full backup files after @StopAt

- sp_BlitzLock.sql
Closes #3276 
Closes #3277
Closes #3279 
For #3277 
* Fixed begin/end issues
For #3277:
* Fixed (blame it on Vegas) `nvarchar(8000)` column
* Realized the max length of all concatenated values is <500 bytes
* Adjusted column and substring lengths to match
For #3279 
* Changed Azure identification method to differentiate between sqldb and mi
* Standardized xml parsing in where clauses to match (axis traversal not necessary)
* Opened up to using other xml deadlock reports
* Added debug mode plan generation in case of perf regressions for a couple queries
> sp_BlitzLock fixes for 3276, 3277, 3279

- sp_Blitz.sql
- Update script so that it considers SQL 2012 as unsupported [Microsoft Product Lifecycle SQL 2012](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2012)
- Update script so that it considers SQL 2016 < SP3 as unsupported [Microsoft Product Lifecycle for SQL 2016](https://learn.microsoft.com/en-us/lifecycle/products/sql-server-2016)
This also incorporates the change from PR #3271
> Update unsupported SQL Versions

- sp_BlitzLock.sql
Closes #3293
Adds a result set that goes out to the plan cache to look for query plans for queries involved in deadlocks.
> Get plans from cache

- sp_BlitzCache.sql
Omits query plans in the Resource database. Closes #3314
> Omit Resource DB from duplicate query plan checks

- sp_Blitz.sql
Add bracketing to compound logical condition to correct behavior for the Replication In Use check.
> Correct the SARG brackets for Replication In Use check in sp_Blitz

- sp_BlitzLock.sql
Closes #3305: Does all of the start and end date filtering to a single line
Closes #3306: Adds a check that the session name exists so you don't feel crazy if no results come back
Closes #3307: Makes event XML searches UTC-friendly for easier filtering to specific ranges
Closes #3311: Speeds up plan cache lookups of query plans for queries involved in deadlocks
> Issues 3305, 3306, 3307, 3311

- sp_BlitzCache.sql
Fixes #3314
We had similar issue where it was showing 3 million duplicate plans and the percentage was over 2000%
We originally looked at this because sp_blitzFirst was taking over an hour to run.
Adding this change to the procedure brings the time down to under 1 minute and the duplicate plan percentage went from 2400% to 93%.
Here are our findings.
So why is the query slow on the server, and why does it return query_plan_hashes in millions? 
That’s because of the LEFT JOIN between sys.dm_exec_query_stats and sys.dm_exec_procedure_stats ON sql_handle.
The left input table in the LEFT JOIN i.e., sys.dm_exec_query_stats has thousands of duplicate sql_handles, and so does the right input sys.dm_exec_procedure_stats. Therefore, for each matching sql_handle on the left, it returns every …
> #3314 sp_BlitzCache high percentage of duplicate plans

- sp_BlitzCache.sql
Was calling for spills, but saying the results were for memory grants.
> sp_BlitzCache all-sorts bug

- sp_BlitzCache.sql
For issue #3331.
After iterating over all sort sub procedure calls ... avoid going to OutputResultsToTable ... otherwise the last result (e.g. spills) would be recorded twice into the output table.
> Update sp_BlitzCache.sql for double-spill fix

- sp_Blitz.sql
Brent's comment from pull request #3335 
> @SkipModel is already a parameter for sp_Blitz, so this feels confusing.
> 
> We'd definitely welcome a pull request that lines up with your original issue notes, though:
My apologies I hadn't noticed the `@SkipModel` parameter.
Changed the code to use the `@SkipModel`  parameter and to the respect the `@SkipModel` value if the caller has set it to 1 by hand, as the old version of the code could override the passed value if we could access the objects in the model database. 
The rest stayed pretty much the same so in the permissions check we still check if we can access the model database and the objects within it.
If `@SkipModel = 1` check 29 will be added to the #SkipChecks table.
Fix for issue #3334
> Issue #3334: sp_Blitz Fails because of permissions

- sp_BlitzCache.sql
On testing #3342, it was failing with the Reanalyze param turned on, so moved those to different parts of the code to make sure the temp table exists.
> #3342 sp_BlitzCache concurrency

- sp_BlitzCache.sql
Changing the source from dm_exec_cached_plans to dm_exec_query_stats. Closes #3353.
> #3353 sp_BlitzCache single use plans

- README.md
- sp_Blitz.sql
#3348 No functional changes, just added some explanation for @debug in the help in sp_Blitz and updated Readme.md
> #3348 added explanation for @debug in help

- sp_Blitz.sql
Fix for issue #3350
The old code had an logical error in it:
```
Check 233 is not in #BlitzResults
Check 2 is not in #SkipChecks
Check 68 is in #SkipChecks
It became:
IF True (Check 233 not in #BlitzResults)
AND
(
True (Check 2 not in #SkipChecks)
OR
False (Check 68 in #SkipChecks)
)
```
So the IF returned true and the check fired.
Basically the OR needed to be an AND, this allowed the code to be simplified to:
```tsql
IF NOT EXISTS
(
SELECT	1/0 
FROM	#BlitzResults 
WHERE	CheckID = 223 AND URL = 'https://aws.amazon.com/rds/sqlserver/'
) AND NOT EXISTS
(
SELECT  1/0
FROM    #SkipChecks
WHERE   DatabaseName IS NULL AND CheckID IN (2, 68)
)
```
Easier to read as well.
> #3350 DBCC DBinfo fires incorrectly

- sp_Blitz.sql
#3356 Fix for sp_validatelogins
Rewritten the code so that the `#InvalidLogins` is created a little earlier and we attempt to fill the `#InvalidLogins` in the permissions check, if that fails we'll disable the check.
> #3356 Fix for sp_validatelogins

- sp_BlitzFirst.sql
Fix for #3370: Division by zero bug if pass 1 and 2 are to close to each other
In check 20 updated the DATEDIFF code with a small piece of code to replace the 0 (zero) with a 1
```tsql
ISNULL(NULLIF( ..., 0), 1)
```
Basically this will NULL the DATEDIFF result if this is a 0 (zero) and then set it to 1 if it is `NULL`
This leaves the function of this piece of code as it was in all other cases other than the scenario reported in issue #3370
> #3370 Division by zero in check 20

- sp_BlitzIndex.sql
Added drop if exists statements for two temp tables in order to make the contents of sp_blitzindex easier to run ad-hoc.
> Add missing drop if exists statements for temp tables

- sp_BlitzCache.sql
- sp_BlitzIndex.sql
Closes #3406 I updated the syntax of the debug SUBSTRING in sp_BlitzCache and sp_BlitzIndex to respect the syntax of the `SUBSTRING ( expression, start, length )` command.
> #3406 Fixed the Substring command to respect the command syntax

- sp_Blitz.sql
When users specify the parameter OutputType = 'markdown', they'll notice the following updates:
1) The column alias is now "Markdown". Achieved by using a slightly different method of retrieving valid XML.
2) When they click on the hyperlink, the markdown text starts on line 1 instead of line 2. Achieved using the STUFF function.
3) Consistent line spacing between a given heading and its subheadings. Achieved by adding a crlf to one of the CASE expression conditions.
4) Align item text in bulleted lists with its associated bullet (for some markdown viewers, including the MarkdownViewer++ plugin for Notepad++). Achieved by adding a single style tag at the end of the markdown text. Tested this on other markdown viewers and it didn't adversely affect the results.
> #3401 sp_Blitz: Improve Markdown output alias and spacing

- sp_Blitz.sql
Closes #3376
Added Informational message about skipping checks
```tsql
IF @sa = 0
BEGIN
INSERT INTO #BlitzResults
( CheckID ,
Priority ,
FindingsGroup ,
Finding ,
URL ,
Details
)
SELECT 223 AS CheckID ,
0 AS Priority ,
'Informational' AS FindingsGroup ,
'Some Checks Skipped' AS Finding ,
'' AS URL ,
'User ''' + @SUSER_NAME + ''' is not part of the sysadmin role, so we skipped some checks that are not possible due to lack of permissions.' AS Details;
END;
```
> #3376 Added Informational message about skipping checks

- sp_Blitz.sql
Fixes #3377
PR #3360 Didn't work as I had intended, xp_regread doesn't play nice with TRY CATCH, removed the permission check at the start and moved it back to check 211.
Added so informational message to the messages tab to inform the user that the errors can be ignored.
> #3377 Moved the xp_regread calls back to the check and add some messages to the user

- sp_Blitz.sql
Closes #3362 
A complete rewrite of Checks 192 and 193 basically merging the code to check if IFI is enabled or not into 1 piece of code and then switching the output to check 192 or 193 based on `@IFISetting`
It will first check the DMV using a sp_executesql within a TRY CATCH block. If that fails it will try and fall back on the error log, both for Amazon and regular SQL Servers.
Tested the code with and without sysadmin permission on a SQL2017 box.
To simulate the DMV using a sp_executesql within a TRY CATCH block you can use this code:
```tsql
DECLARE @Result int;
BEGIN TRY
EXEC sp_executesql N'CREATE TABLE #TestTable ([Col1] int);
INSERT INTO #TestTable ([Col1]) VALUES (1);
SELECT @Result = [Col1]
FROM #TestTable;'
,N'@Result int OUTPUT'
,@Result = @Result OUTPUT;
SELECT N'I …
```
> #3362 Rewrite of check 192 and 193

- sp_BlitzIndex.sql
This PR aims to remove extra junk output for the specific case of a columnstore index existing on a partitioned table with at least one other rowstore index.
Output prior to fix on latest version (8.18):
Output after fix applied:
I have tested this solution on SQL Server 2022 Developer Edition RTM, Azure SQL DB (as of 27/12/2023) and Azure SQL Managed Instance (CU9) and it has corrected it with no issues.
Test script used:
````
CREATE PARTITION FUNCTION TestBlitzIndexPF (CHAR(1))
AS RANGE RIGHT FOR VALUES ('A', 'B')
GO
CREATE PARTITION SCHEME TestBlitzIndexPS
AS PARTITION TestBlitzIndexPF
ALL TO ([Primary])
GO
CREATE TABLE TestBlitzIndex (
ID INT IDENTITY(1, 1) NOT NULL,
PartitionColumn CHAR(1) NOT NULL,
SomeColumn NVARCHAR(100),
CONSTRAINT [PK_TestBlitzIndex] PRIMARY KEY CLUSTERED …
```
> sp_BlitzIndex bug: Extra junk output from columnstore visualisation

- .github/workflows/integration-tests.yml
- tests/run-tests.ps1
- tests/sp_Blitz.tests.ps1
- tests/sp_BlitzAnalysis.tests.ps1
- tests/sp_BlitzBackups.tests.ps1
- tests/sp_BlitzCache.tests.ps1
- tests/sp_BlitzFirst.tests.ps1
- tests/sp_BlitzInMemoryOLTP.tests.ps1
- tests/sp_BlitzIndex.tests.ps1
- tests/sp_BlitzLock.tests.ps1
- tests/sp_BlitzQueryStore.tests.ps1
- tests/sp_BlitzWho.tests.ps1
Use GitHub Actions to provide automated testing for first responder kit stored procedures. 
#3418
> Add Automated Testing

- sp_Blitz.sql
Closes #3411
Adds a check if accelerated database recovery is enabled, It's skipped for MI and SQLDB because it is on by default there.
> Add ADR Check

- sp_Blitz.sql
> Skip xp_regread if we don't have sa perms

- README.md
- sp_DatabaseRestore.sql
Add `@FileNamePrefix` parameter to `sp_DatabaseRestore` - a prefix to add to the names of all restored files. Useful when you need to restore different backups of the same database into the same directory.
> Add FileNamePrefix parameter to sp_DatabaseRestore

- .github/workflows/integration-tests.yml
Supports #3418.
Saw the blog post, figured I'd try to help a little. :)
This should allow you to specify multiple versions and collations and have them all run as part of a build.
We're not demonstrating this here, but you can also specify specific pairs of values rather than all combinations, if that makes more sense. Happy to adapt according to your needs.
> (build) Add Matrices for SQL Server Version and Collation

- sp_Blitz.sql
Hi Brent,
On Azure SQL Managed Instance the following checks should be skipped:
- 92 - drive info/space usage 
- 224 - SSRS/SSAS/SSIS Installed
The errors they throw on MI:
- 92 
```
Running CheckId [92].
Msg 8115, Level 16, State 8, Line 1
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.
```
- 224 
```
Running CheckId [224].
Msg 40514, Level 16, State 45, Procedure xp_cmdshell, Line 1 [Batch Start Line 0]
'xp_cmdshell' is not supported in this version of SQL Server.
```
> Added checks 92 and 224 to skipped checks for Azure SQL MI

- README.md
The hyperlink for the table of contents for `sp_BlitzQueryStore` appears broken. This fixes it.
It may also be the case that the "Like BlitzCache, for Query Store" tagline needs changing, but I'm not sure if that or the section heading of "How Has a Query Plan Changed Over Time" should be used. My opinion is that the second of the two should be used. I find that `sp_BlitzQueryStore` will return the same query on multiple rows even if it only has one plan (and throw a "Multiple Plans" warning at the same time), whereas `sp_BlitzCache` never does. The "How Has a Query Plan Changed Over Time" heading is more faithful to this (because the extra rows are for different time intervals), but the very first line of the docs for `sp_BlitzQueryStore` advertises it as similar to `sp_BlitzCache` so …
> Update README.md - Fixed internal link for sp_BlitzQueryStore

- sp_BlitzQueryStore.sql
The old one seemed like an obvious copy and paste error. I have replaced it with my best guess at a useful summary.
> Updated warning text for "Non-SARGable queries"

- sp_BlitzFirst.sql
Clarifying warning that can also be caused by memory-optimized TempDB. Closes #3488.
> #3488 sp_BlitzFirst garbage collection

- sp_BlitzFirst.sql
If OutputResultSets didn't ask for BlitzCache. Closes #3492.
> #3492 sp_BlitzFirst hide plan cache

- sp_BlitzCache.sql
- sp_BlitzQueryStore.sql
While working on `sp_BlitzQueryStore`, I noticed that this was missing in `sp_BlitzCache`.
> Document the @Version parameters in sp_BlitzCache's and sp_BlitzQueryStore's @Help = 1 output

- sp_BlitzQueryStore.sql
Although it's sometimes considered a bad idea to turn on Query Store for these databases, that doesn't justify telling people that they haven't done so.
> Removed skipping of model and msdb in check for QS-enabled DBs

- sp_BlitzQueryStore.sql
This is just an effortless copy and paste job to close #3459 . The testing resource needed to confirm that this works is minimal.
> Remove "rn" column in sp_BlitzQueryStore output (closes #3459)

- sp_BlitzQueryStore.sql
As requested in #3458 , reopened this as a PR that only includes the missing `RAISERROR`. Empty lines aside, this is just a one-line change so there's no need to open an issue or ask for resources.
The check for parallel plans was the only _warning_ check that was missing a `RAISERROR`, so I have added it in for consistency. There are _pattern_ checks that have oddities around what they `RAISERROR`, but that is [a separate issues](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3449) that requires some discussion before writing any code.
> Added missing RAISERROR to the check for parallel plans

- sp_BlitzQueryStore.sql
Closes #3478
This is a trivial change. It's just adding/correcting comments.
> sp_BlitzQueryStore.sql: Add comments for non-commented temp tables.

- sp_Blitz.sql
Closes #3481
This is pretty much copy-paste from #3481, so no need to read again. I've added the info here for documentation's sake.
In attempts to fix permission related issues, people might end up adding the SQL Server and/or SQL Server Agent service account(s) to the local Administrators group or, even worse, set them to run as Local System or NT AUTHORITY\SYSTEM.
These types of shortcuts lead to news articles such as [this one](https://www.bleepingcomputer.com/news/security/microsoft-hackers-target-azure-cloud-vms-via-breached-sql-servers/).
**Adding the following 4 checks:**
- CheckId 258 Check if SQL Server is running as `Local System` or `NT AUTHORITY\SYSTEM`
- CheckId 259 Check if SQL Server Agent is running as `Local System` or `NT AUTHORITY\SYSTEM`
- CheckID 260 Check if SQL …
> sp_Blitz: New security-related checks for SQL Server and Agent running as privileged accounts

- sp_BlitzFirst.sql
More accurate startup time detection. Closes #3504.
> #3504 sp_BlitzFirst Azure SQL DB

- sp_BlitzFirst.sql
The headline news result set now shows the accurate number of seconds used for the wait stats sample. Closes #3507.
> #3507 sp_BlitzFirst wait stats seconds

- sp_BlitzIndex.sql
Corrected 3 typos
paritions vs partitions
sequental vs sequential
partioned vs partitioned
> Typos in the index script

- sp_BlitzIndex.sql
This will fail on a case-sensitive database
> Capitalised name column

- sp_BlitzIndex.sql
There is code to identify databases which can't be analysed that results in secondary_role_allow_connections_desc = 'NO', but these aren't excluded from the NumDatabases count
> NumDatabases includes those already marked as unreachable

- sp_BlitzIndex.sql
For consistency with the INSERT query above - DB_NAME should be used in both places
> Use of DB_NAME()

- Install-All-Scripts.sql
- Install-Azure.sql
- sp_BlitzIndex.sql
Fixing error if they can't query sql_expression_dependencies. Closes #3522.
> #3522 sp_BlitzIndex permissions

- sp_BlitzLock.sql
Adds DeadlockType parameter for filtering to regular or parallel deadlocks.
Closes #3525
> Adds DeadlockType parameter for filtering to regular or parallel deadlocks

- sp_Blitz.sql
Closes the original idea behind #3527 as well as its items numbered 1, 2, 3, and 4. **Items 5-8 remain open** and will require new sp_Blitz checks. The checks in this PR were all bolted on to check 74 because we already do the same thing for Trace Flags 834 and 8017.
This is my first PR for sp_Blitz, so it's quite likely that it's not perfect. It's passed the limited suite of tests that I've tried on my local instance.
> sp_Blitz: Add more detail to Query Store Trace Flag rows

- Documentation/sp_Blitz_Checks_by_Priority.md
- sp_Blitz.sql
Closes item 5 in #3527  Only items 6 and 7 are now awaiting PRs.
I've added this under the same check number as my other new check, because it's rude to assume that both will get merged.
I've made this a priority 200 issue under the 'Performance' header. This is the consistent with the check for having Query Store completely disabled.
I couldn't find a better URL than the one that I've given. One must surely exist.
This is my first new mutli-database check for `sp_Blitz`, so it's quite likely that it's missing something important. It's passed the limited suite of tests that I've tried on my local instance.
> sp_Blitz: Add check for Query Store Wait Stats being turned off

- README.md
- sp_DatabaseRestore.sql
Fixes #3532  by adding the ability to re-enable the service broker after restoring a database.
Additionally, capitalized a few data types for consistency and my VSCode settings trimmed trailing whitespace. I can roll these back if you want to keep the history of lines modified cleaner, otherwise I think its a good habit to remove these (~3kb smaller without them, including my additions)
> sp_DatabaseRestore: allow enabling service broker on restore

- Documentation/sp_Blitz_Checks_by_Priority.md
- sp_Blitz.sql
Closes item 7 in https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3527 . Only item 6 is now awaiting a PR. This change includes two new checks. Adding a check for Query Store not being in its desired state was such a natural follow-up from checking for READ_WRITE that I couldn't resist.
I've made this a priority 200 issue under the 'Performance' header. This is the consistent with the check for having Query Store completely disabled. After all, these two issues effectively disable Query Store.
The URL I've added is the best one that I know for this topic. Both checks have the same URL.
I've only been able to test the check for the READ_WRITE state. I've only ever seen Query Store leave its desired state on busy production databases. I'm unsure how to simulate it to …
> sp_Blitz: Added check for Query Store not being in READ_WRITE state and check for it not being in desired state.

- sp_BlitzIndex.sql
Add filter on database_id to speed processing and reduce chance of throwing errors. Closes #3556.
> #3556 sp_BlitzIndex missing index processing

- sp_BlitzLock.sql
> Fix for sp_BlitzLock @Debug=1 throwing an error when no plans found in plan cache - #3567

- SqlServerVersions.sql
Added:
- latest CUs for 2019 and 2022
- latest GDRs for 2016, 2017, 2019, and 2022
- some missing GDRs for 2016 and 2017
> SqlServerVersions - Added latest CUs and GDRs

- sp_BlitzLock.sql
Was throwing errors on SQL 2022, possibly others, due to synonym location. Closes #3566.
> #3566 sp_BlitzLock better qualify synonym

- sp_Blitz.sql
Fix for #3577 
Check for EXECUTE rights on sp_MSgetalertinfo. If missing set @SkipGetAlertInfo to 1, which skips the check completely.
> sp_Blitz: Fix checks 73 to work with sysadmin permissions

- sp_Blitz.sql
Fix for #3578 
With comment hopefully explaining why the check was added
> sp_Blitz: Check 191 avoid false positives in case user doesn't have permissions on sys.master_files

- sp_BlitzIndex.sql
When your lazy and do not want to fill in all parameters: @DatabaseName, @SchemaName and @TableName
Now you can *simply* do: `EXEC sp_BlitzIndex @ObjectName = 'schema.tablename'`
Or if you're **really** lazy do: `EXEC sp_BlitzIndex 'schema.tablename'`
> When your lazy and do not want to fill in all parameters... for: @DatabaseName, @SchemaName, @TableName

- sp_Blitz.sql
When I run a procedure with the following parameter "exec dbo.sp_Blitz @OutputType = 'Markdown'", I expected to see the output result in Markdown format. However, I received the following error instead:
_Msg 9421, Level 16, State 1, Procedure dbo.sp_Blitz, Line 10347 [Batch Start Line 0] XML parsing: line 63, character 37, illegal name character._
The issue is caused by an illegal character (&) in the description of the Finding column for CheckID = 162. To resolve this issue, update the description to replace & with and, ensuring XML compatibility.
> Replace illegal character & in sp_Blitz for Markdown output result

- sp_BlitzIndex.sql
Updated data type of reserved MB fields in [#dm_db_partition_stats_etc] to match similar fields in other temp tables.
BlitzIndex for a single table will now report "size" for indexes less than 1 MB.
> INT data type prevents reporting indexes < 1 MB

- sp_Blitz.sql
Fix for #3581. The idea here is to check ALTER TRACE permissions on server level and not ALTER on sys.traces itself.
Here is an extended script from the issue. Added third test for sp_Blitz with ALTER TRACE granted. With that we can see DBCC DROPCLEANBUFFERS reported (yeah added it there so no copy, paste, execute into production). It shows the check itself works.
```
USE master
DBCC DROPCLEANBUFFERS
CREATE LOGIN BlitzTest WITH PASSWORD = 'TestBlitz'
CREATE USER BlitzTest FOR LOGIN BlitzTest
GRANT EXECUTE ON sp_Blitz TO BlitzTest
GRANT VIEW SERVER STATE TO BlitzTest
GO
EXECUTE AS LOGIN = 'BlitzTest'
PRINT 'This works'
EXEC sp_Blitz
PRINT 'This worked'
REVERT
GO
ALTER ROLE db_owner ADD MEMBER BlitzTest
EXECUTE AS LOGIN = 'BlitzTest'
PRINT 'This does not works'
EXEC sp_Blitz
PRINT 'Doesn''t …
```
> sp_Blitz - correctly check permissions for sys.traces

- sp_Blitz.sql
Really, really big data files would overflow an NVARCHAR(10). Closes #3599.
> #3599 sp_Blitz overflow

- sp_BlitzCache.sql
Hi Brent!
This PR adds a new parameter `@KeepCRLF` BIT, default 0, that when set to 1 will stop sp_BlitzCache from stripping CR and LF from the query text. 
The way sp_BlitzCache treats tabs and multiple consecutive spaces will not be changed by this new parameter.
Users who have SSMS set to retain CRLF on copy-paste from the grid results* won't have to deal with any potential issues caused by line comments inside the query text.
`*`Tools>Options>Query Results>SQL Server>  Results to Grid> Retain CR/LF on copy or save.
Closes #3611
> sp_BlitzCache - added new parameter to retain CRLF in query text

- sp_Blitz.sql
Which broke Markdown output. Closes #3610.
> #3610 sp_Blitz remove ampersand

- Documentation/sp_BlitzIndex_Checks_by_Priority.md
- sp_BlitzIndex.sql
Added reports of resumable index operations to the mode 0 and mode 4 outputs, as well as the mode where you name one table. The priority set here is very high, but that seems correct. They can prevent DDL!
[Brent warned](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3609#issuecomment-2693163590) that I should check if the `sys.index_resumable_operations` honours `NOLOCK`, but as far as I can tell it's impossible to put a resumable operation in a transaction.
My production experience of resumable operations is very limited, so the warnings that I have given about them relied on either trusting the documentation or doing what I could easily verify. If there are much nastier things to warn of, then somebody should change my strings.
I think that this is my first …
> sp_BlitzIndex: Added reports of resumable index operations (closes #3609 )

- Documentation/sp_Blitz_Checks_by_Priority.md
- sp_Blitz.sql
- sp_BlitzIndex.sql
Added warnings in sp_BlitzIndex and sp_Blitz. Closes #3620.
> #3620 paused index operation

- Documentation/sp_BlitzIndex_Checks_by_Priority.md
- sp_BlitzIndex.sql
These cause MERGEs on the main table to fail. Also put #TemportalTables in the debug output. It was missing.
I had to make the table for the documentation wider, since the new URL was the widest yet.
Closes #3618 . All in all, the change seems pretty simple.
> Added warning for non-clustered indexes on history tables.

- sp_BlitzFirst.sql
To the left in result sets. Closes #3629.
> #3629 sp_BlitzFirst move avg ms

- README.md
- sp_BlitzCache.sql
Lets you query the plan cache on secondaries. Closes #3632.
> #3632 sp_BlitzCache readable replicas

- Documentation/sp_BlitzFirst_Checks_by_Priority.md
- sp_BlitzFirst.sql
To headline news result set. Closes #3631.
> #3631 sp_BlitzFirst add thread time

- Documentation/sp_Blitz_Checks_by_Priority.md
- sp_Blitz.sql
> #3635 sp_Blitz AG latency warning

- Documentation/sp_BlitzFirst_Checks_by_Priority.md
- sp_BlitzFirst.sql
Add warning if deadlocks are happening now. Closes #3637.
> #3637 sp_BlitzFirst deadlock warning

- sp_Blitz.sql
The model database always returns 1 for is_query_store_on in sys.databases in SQL 2022, so this will always show query store is in use even if no user databases have it enabled.
> Exclude Model Database From @QueryStoreInUse Check

- Install-All-Scripts.sql
- Install-Azure.sql
- SqlServerVersions.sql
- sp_Blitz.sql
- sp_BlitzAnalysis.sql
- sp_BlitzBackups.sql
- sp_BlitzCache.sql
- sp_BlitzFirst.sql
- sp_BlitzIndex.sql
- sp_BlitzLock.sql
- sp_BlitzWho.sql
- sp_DatabaseRestore.sql
- sp_ineachdb.sql
Adds units of measure, updates release dates and versions for 2025-07-04 release. Closes #3660.
> #3660 sp_BlitzFirst thread time

- sp_ineachdb.sql
Changes the default value of parameter @is_query_store_on from 0 to NULL to avoid excluding non-query store databases by default.
This resolves #3668 to make the addition of this parameter a non-breaking change.
> sp_ineachdb - Change @is_query_store_on Default Value to NULL

- sp_BlitzLock.sql
- **look for existing output table in sys.schemas** - closes #3667 
- **add explicit schema to synonym** - closes #3666
> #3666 and #3667 sp_BlitzLock fixes

- sp_Blitz.sql
some minor fixes to sp_Blitz, all mentioned in issue https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3673 
also, should resolve #3673 
- changed wildcard search in WHERE clause for Check IDs 260 and 261
- fixed minor bug in "piggyback" section of Check 261
- added support for German OS language for Checks 260 and 261
again, I'm not sure if the support for German OS language with regards to the xp_cmdshell call makes sense.
this may open "pandoras box" to add more language specific fixes.
Therefore I did more than one commit to pick the meaningful changes
> changes to sp_blitz - Edgecase fix #3673

- Documentation/sp_Blitz_Checks_by_Priority.md
- sp_Blitz.sql
Add warning about low memory recently. Closes #3690.
> #3690 sp_Blitz memory pressure

- sp_BlitzFirst.sql
When restoring a new database. Closes #3695.
> #3695 sp_BlitzFirst clarify restore name

- sp_BlitzWho.sql
On by default in 2022 & newer and Azure.
> #3694 sp_BlitzWho live plans

- Documentation/sp_BlitzIndex_Checks_by_Priority.md
- README.md
- sp_BlitzIndex.sql
Closes #3679 .
This was disturbingly easy. You will want to check over it very carefully. The only place where I really had to think was the dynamic SQL. I don't have super old versions of SQL Server hanging around, so I have not been able to test any branches other than the one that my 2022 Docker container hits.
The URL that I have given is the best that I could find. I cannot think of anyone who has spoken with the voice of experience about `PERSIST_SAMPLE_PERCENT`.
I might make an issue for us also not having incremental statistics, but the merge conflict will be a pain unless this is merged first.
> sp_BlitzIndex: Added warning for persisted sample rates.

- sp_BlitzIndex.sql
Continued work on #3680. Moves 200-priority down to Mode 4, throws error if they pass in an invalid stats sampling rate.
> #3680 sp_BlitzIndex stats sampling

- Documentation/sp_BlitzIndex_Checks_by_Priority.md
- sp_BlitzIndex.sql
Closes #3699. Everything went as I described there.
This takes more than 10 minutes on my machine, because partitioning the `Posts` table is slow.
```sql
/* On a fresh StackOverflow 2010 copy, there is nothing new here */
USE [StackOverflow2010];
EXEC sp_BlitzIndex @SkipStatistics = 0, @Mode = 0;
EXEC sp_BlitzIndex @SkipStatistics = 1, @Mode = 0;
EXEC sp_BlitzIndex @SkipStatistics = 1, @Mode = 4;
EXEC sp_BlitzIndex @SkipStatistics = 0, @Mode = 4;
/* Now let's partition */
CREATE PARTITION FUNCTION PfDates (DATETIME)
AS RANGE RIGHT
FOR VALUES
(NULL, '20070101', '20080101', '20090101',  '20100101');
GO
CREATE PARTITION SCHEME PsDates
AS PARTITION PfDates
ALL TO ([Primary]);
GO
ALTER TABLE [dbo].[Votes] DROP CONSTRAINT [PK_Votes__Id]
ALTER TABLE [dbo].[Votes] ADD  CONSTRAINT [PK_Votes__Id] …
```
> sp_BlitzIndex: Warn about partitioned tables that don't have incremental statistics

- sp_Blitz.sql
Lending @bmercernccer a helping hand here.
This resolves #3702 
Summary:
* Uses the previously established @IsWindowsOperatingSystem variable to determine if certain checks need to be run
* Adds a null check guard against the service account
For reference this is what the related `sys.dm_server_services` output looks like on SQL Server 2025 Preview on Ubuntu 24.04
> sp_Blitz: Linux quality improvements

- sp_BlitzIndex.sql
A few checks in sp_BlitzIndex were written to filter out tables created in the last 7 days or modified in the last 2 days, but the less-than/greater-than check was reversed.  This fixes them.
check_id 21: More Than 5 Percent NC Indexes Are Unused
check_id 29: NC indexes with 0 reads and < 10,000 writes
The relevant lines also had tabs where surrounding lines used spaces, so I fixed that too.
I verified the direction of all other newer/older checks in sp_BlitzIndex and they seem to be correct.  I searched the rest of the codebase for similar filters and found none.
> Correctly filter out new indexes
