sp_AskBrent.sql

Fixes 20160615/brent

---

sp_BlitzCache.sql

Even if you weren’t running it at the same time, you’d see someone
else’s summary data in your summary section.

#305 - sp_BlitzCache ##bou_BlitzCacheResults not filtered by sessionid

---

README.md

Master branch download might include changes that aren't stable

Use GitHub releases instead of branch tarball

---

README.md

Add img.shields.io badges

---

sp_Blitz.sql

Probably the world’s worst fix, but this used windowing functions and
ain’t nobody got time for that.

#324 sp_Blitz removed % of waits in details

---

README.md

Update some additional references to sp_AskBrent in README.md to use new sp_BlitzFirst name

Replace references to sp_AskBrent in README.md

---

sp_BlitzCache.sql

Blitzcache erik issue334

---

sp_BlitzCache.sql

Working fix for stored proc and statement level costs and row info

Blitzcache erik issue339

---

.editorconfig

Partial for #287
Autoconvert spaces to tabs, but no manual intervention for existing incorrect indenting levels

Chore: Add EditorConfig

---

sp_BlitzIndex.sql

Merged branch to fix issue with @Mode = 2 not ordering things properly
Adds partition level information  to table-detail
Fixes a couple logical errors around excluding recently created/modified tables, and filters them out of unused index warnings if they're been created in the last 7 days or modified in the last 2.

Blitzindex erik multiple

---

sp_BlitzFirst.sql

Fixes:
Filter out perfmon counters of 0
Include login_name in what's running
All reserved words are now upper case

Blitzfirst erik issue 356

---

sp_BlitzCache.sql

Blitzcache erik issue 358

---

sp_BlitzIndex.sql

Now orders by database name, schema name, table name, index id

Change order of @Mode=2 output

---

sp_BlitzCache.sql

Reverts BrentOzarULTD/SQL-Server-First-Responder-Kit#377

Revert "Changed "Downlevel CE" to "Legacy CE""

---

sp_Blitz.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzIndex.sql

Bumping dates/versions for release. Closes #382.

#382 Adding dates/versions

---

sp_BlitzCache.sql

sp_BlitzCache Typo "beend" -> "been"

---

sp_BlitzCache.sql

Blitzcache erik multiple

---

sp_BlitzCache.sql

Fix sorting by average memory grant

---

README.md
sp_Blitz.sql
sp_BlitzRS.sql

Fix time formatting
Update system xe sessions

Blitz erik 392

---

CONTRIBUTING.md

Change duplicate link for one global markdown link

---

sp_BlitzIndex.sql

Information wasn't aggregating correctly with getalldatabases = 1

Fix for issue 432

---

sp_Blitz.sql

Added the IFI check to sp_Blitz for 2014 SP2 and greater by reading the
Error Log.

#434 sp_Blitz added IFI check

---

sp_Blitz.sql

#420 sp_Blitz ignore Agent checks for Express

---

sp_Blitz.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzIndex.sql

For the September release, closes #440.

#440 updating version dates and numbers

---

.github/ISSUE_TEMPLATE.md

Fixes a link to a non relevant site .

Replace jsfiddle.net with sqlfiddle.com

---

sp_Blitz.sql

#460 sp_Blitz add WAIT_XTP_OFFLINE_CKPT_NEW_LOG to ignorable

---

sp_Blitz.sql

Affects checks 178, 180, 181. Closes #462.

#462 sp_Blitz - improves SQL 2005 compatibility

---

sp_BlitzFirst.sql
sp_BlitzIndex.sql

Reverting some bad code that got introduced by an oopsie commit. Closes
#464.

#464 sp_BlitzFirst and sp_BlitzIndex - backing out recent changes

---

sp_BlitzIndex.sql

#IndexSanity, #IndexSanitySize, and #MissingIndexes were being altered
dynamically if necessary, but the “if necessary” check wasn’t right.
Threw that out and just built the temp tables the right way from the
start. Closes #466.

#466 sp_BlitzIndex avoid dynamic altering of temp tables

---

sp_BlitzIndex.sql

When @GetAllDatabases = 1, not all result sets had a Database Name
column. Closes #467.

Issue 467/brent

---

README.md

Add Navigation section and Back to top links

---

sp_Blitz.sql

#86 sp_Blitz fixing typo in db_accessadmin

---

sp_Blitz.sql

Abandoned the variable concatenation approach and switched to FOR XML
PATH output. Great idea, props to Erik. Tested on 2005-2016. Closes #452.

Issue 452/brent

---

sp_Blitz.sql

Fixes # .
A check to see what account has been specified against the AG endpoint. Most times this has been set as a user account, which will cause similar issues to SQL agent jobs if the user leaves the company and account is disabled. I have tried setting the account as 'sa' and when it failed over, the database wouldn't come up and could see in the error log that the SQL Server service account didn't have connect permissions to the database. This was resolved by changing the endpoint account to match the SQL server service account.
CheckID and Error text will need to be changed to whatever you require
Checking for SQL versions greater than 11
Check to see is IsHadrEnabled is set to 1
Then comparing the accounts to see if they …

Update to sp_blitz (Issue #366)

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

Assigned a check number and tweaked the query to list the endpoints and
owners. Closes #366.

#366 sp_Blitz - tweaks to check 187 for endpoint owners

---

sp_BlitzIndex.sql

Closes #505, stabs it in the heart with a wooden stake, and sets the
corpse on fire.

#505 sp_BlitzIndex adding back in Erik's code

---

sp_Blitz.sql
sp_BlitzFirst.sql
sp_BlitzIndex.sql
sp_BlitzWho.sql

#516 Updating version/dates for 2016/10 release

---

sp_BlitzCache.sql

Blitzcache 543

---

sp_BlitzIndex.sql

Sp blitzindex 548

---

sp_BlitzCache.sql

#559 sp_BlitzCache fix varbinary conversion error

---

sp_Blitz.sql

Fixes #568 
- Show MAXDOP alert if setting is default and numa nodes > 1 or logical cores > 8
- Show Cost Threshold for Parallelism alert if default of 5
- Test on a server with > 1 NUMA node
- Test on a server with >8 cores
- Test on a server with default CTFP & MAXDOP
Feature request: add two separate alerts for:
Cost Threshold is at the default of 5
MAXDOP is at the default of 0, and the system has more than 1 socket, or more than 8 cores per socket

sp_Blitz - MAXDOP & Cost Threshold for Parallelism

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

CheckID 188, added more information about default settings, put it in
its own IF branch for #SkipChecks. Closes #568.

#568 sp_Blitz MAXDOP & CTFP check housekeeping

---

sp_BlitzCache.sql

Stop flagging queries that get the minimum grant

---

sp_BlitzIndex.sql

#566 
#567 
#571 
No version-specific changes were made. Tested against case sensitive.

Blitzindex 566

---

sp_BlitzIndex.sql

Fixes #577 
Change validation 
- Test on a SQL Server 2005 instance to ensure error message appears
Now validates for 2008+ rather than 2005+

sp_BlitzIndex - Update Version Check

---

sp_BlitzCache.sql

Blitzcache 495

---

sp_BlitzWho.sql

sp_BlitzWho #596

---

sp_BlitzCache.sql

Closes #617
Adds alert for when computed columns reference scalar UDFs

Closes #617

---

sp_Blitz.sql

Referenced in #620  relates to #615 .
- Add check in trace flags to see if trace 834 is being used alongside columnstore indexes
- Test on a server that contains columnstore indexes and also has trace flag 834 switched on. The alert will appear at Priority 200 - Informational - Trace Flag On
- Check on a server with no columnstore indexes to ensure issue doesn't appear
- Check on a server with trace 834 switched off to ensure it doesn't appear
- If the trace flag is switched on and no columnstore indexes are in use then it should show a generic text stating that this flag is on ('Trace flag 834 is enabled globally.') rather than the specific error message ('Trace flag  834 is enabled globally. Using this Trace Flag with …

sp_Blitz - Trace Flag 834 with Columnstore Indexes

---

sp_Blitz.sql

Tweaks to Rich Benner’s pull requests. Now checks all databases, not
just the current one. Closes #615.

#615 sp_Blitz - warn for trace flag 834 w/columnstore

---

sp_BlitzIndex.sql

sp_BlitzIndex -- stop counting hypothetical indexes in NC index info

---

sp_BlitzCache.sql

Somehow QueryPlanCost got dropped off the INSERT list when writing to a
table.

Emergency fix for #609

---

sp_BlitzCache.sql

Closes #653
--Session data read across executions 
Closes #633 
--Adds check for number of indexes modified
Closes #652
--Adds checks for scalar UDFs in filters

Blitzcache 633

---

sp_BlitzFirst.sql

Do a quick existence check in sys.dm_os_waiting_tasks before hitting a
bunch of DMVs. (This query has been commented out for a long time
because it caused 20-minute runtimes at Stack.) Fixes #656.

#656 sp_BlitzFirst rewrite long-running blocker check

---

sp_BlitzCache.sql

This works a bit faster. Less doodling around within xquery paths is a
good thing.
I still can't figure out the table valued join logic. Sometimes it shows
up and some times it doesn't. Issue #329 references this as well. I'd
love to rewrite it, but I'm half tempted to pull it out, too.

Break operator checks into smaller batches

---

sp_Blitz.sql

Adding TOURSTOP comments. Closes #299.

sp_Blitz #299 guided tour

---

sp_BlitzFirst.sql

Check for sp_BlitzWho in master

---

sp_BlitzIndex.sql

Adds csv list of column names in case of multi column stats
Closes #680

sp_BlitzIndex -- Stats columns collection

---

sp_BlitzCache.sql

We have @SortOrder = all and all avg

---

sp_BlitzCache.sql

Added a parameter to filter on a minimum execution count for all modes.

#459 sp_BlitzCache Added minimum execution count

---

sp_BlitzCache.sql

Adds check for RLS in 2016+

---

Documentation/Development/ReleaseProcess.md

Explaining how to do releases. Closes #690.

#690 adding release documentation

---

sp_BlitzIndex.sql

Fixes error with aggressive locking queries

---

sp_BlitzFirst.sql

Fixes some ignorable waits issues, also incorrect temp table name and adds more clear plan cache test when we're NOT checking the plan cache.

Sp blitzfirst ignorable waits

---

sp_Blitz.sql

Slapped recompile on the proc and in all the dynamic SQL. Closes #670.

#670 sp_Blitz recompiles to avoid plan cache bloat

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

#176 sp_Blitz setting links to HTTPS

---

sp_BlitzFirst.sql

Before, we were alerting if any backups were running. Now we only alert
if they’re taking more than 5 minutes, and we also include the username
running the backup. Closes #595.

sp_BlitzFirst #595 - only warning about >5 minute long backups

---

sp_Blitz.sql

#673 sp_Blitz adding database name to checks 28, 29

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

Check 151 was only looking at log files before. Tweaked the filter to
also look at slow data file growths too. Closes #478.

#478 - sp_Blitz look for slow data file growths too

---

Documentation/Development/_TestBed.sql
sp_BlitzFirst.sql

Had to make some other minor changes, and piggybacked a change to
_TestBed to make sure this works up in the lab.

Adds support for current database context check for sp_BlitzWho

---

sp_Blitz.sql

Fixes BPE warning wording

---

sp_Blitz.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzIndex.sql
sp_BlitzWho.sql

Standardizing version and versiondate output across relevant Blitzes

---

sp_BlitzIndex.sql

First stab at smarter index algorithm

---

sp_BlitzCache.sql

Tentative support for functions DMV in 2016

---

sp_Blitz.sql

#730 sp_Blitz changing "Recovery Mode" to "Recovery Model"

---

README.md

It turns out that other people won’t write your documentation for you.
What the hell, open source?!? Closes #280.

#280 - readme.md documentation for sp_BlitzCache

---

README.md

I hope I’m getting paid by the word for this. Closes #281.

#281 readme.md add sp_BlitzIndex documentation

---

DatabaseRestore.sql
LICENSE.md
README.md

Adding DatabaseRestore.sql, updating license.md and readme.md to
include notes. Closes #746.

#746 DatabaseRestore.sql and supporting files

---

sp_BlitzIndex.sql

Fix query error

---

sp_BlitzCache.sql

Not proud of this, but it works. Closes #700.

#700 sp_BlitzCache making ExportToExcel work with all sorts

---

Documentation/sp_BlitzFirst Checks by Priority.md
sp_BlitzFirst.sql

Alerting if over 100 per second. Closes #236.

#236 sp_BlitzFirst added check for forwarded records

---

sp_BlitzFirst.sql

Turned check 5 (long-running blocker) into dynamic SQL to avoid calling
master..sysprocesses. Closes #751.

#751 sp_BlitzFirst now Azure SQL DB compatible

---

Documentation/sp_Blitz Checks by Priority.md
Documentation/sp_BlitzFirst Checks by Priority.md
sp_Blitz.sql
sp_BlitzFirst.sql

Expands poison wait list for sp_Blitz, sp_BlitzFirst to include Azure SQL DB poison waits. Closes #754.

Issue 754/brent

---

sp_Blitz.sql

#756 sp_Blitz skip some checks on Express Edition

---

sp_BlitzCache.sql

Add spatial index flag

---

sp_BlitzIndex.sql

Improve flagging of scalar functions in computed columns

---

sp_BlitzIndex.sql

Index Hoarder: Unused NC index priority

---

sp_BlitzIndex.sql

Temporal table awareness

---

DatabaseRestore.sql

Renamed DatabaseRestore to sp_DatabaseRestore and made script idempotent
Fixes #773 and #786 #

Renamed DatabaseRestore

---

sp_BlitzCache.sql

Blitzcache 692

---

sp_BlitzCache.sql

Add support for finding index dml

---

sp_BlitzCache.sql

Add table dml warnings too

---

sp_BlitzCache.sql

We can get this by summing statement stuff the way we get other summed
info from statements in a proc.

Bubble up memory grant info

---

sp_BlitzCache.sql

One node down

---

sp_BlitzCache.sql

Closes #804
Adds warnings for long running queries with low cpu
Adds warnings for low cost queries with high cpu

Adds warnings for odd query data

---

sp_BlitzWho.sql

We shouldn't show these with sleeping SPIDs
Closes #806

Filters out background sessions

---

sp_BlitzWho.sql

Sp blitzwho 820

---

sp_BlitzCache.sql

Also fixing debugging strings while I’m in there. Closes #815.

sp_BlitzCache #815 divide-by-zero on Hekaton plans

---

Documentation/sp_BlitzFirst Checks by Priority.md
sp_BlitzFirst.sql

Added SQL 2014/2016 Perfmon counters and a few warnings. Cleaned up the
copyright date and wait stats sort while I was in there. Closes #817.

#817 sp_BlitzFirst warn on Hekaton activity

---

sp_BlitzFirst.sql

Fixes dynamic SQL issue with LRQ query

---

sp_BlitzIndex.sql

Some of the checks queries weren’t joining on database_id, so they
produced unpredictable results when objects in different databases had
the same object_id. Closes #711.

#711 sp_BlitzIndex adding joins on database_id

---

sp_BlitzIndex.sql

sp_BlitzIndex - widespread performance tuning, closes #827, although likely to introduce bugs.

Issue 827/brent

---

sp_BlitzIndex.sql

Erik’s fixes for #711 merged back into dev.

#711 - sp_BlitzIndex Erik's joins on schema

---

sp_BlitzIndex.sql

Redid the tuning after merging Erik’s schema changes. Closes #827.

#827 sp_BlitzIndex Tuning 2: Electric Tunaloo

---

sp_BlitzCache.sql

Improve speed of cost gathering

---

sp_BlitzCache.sql

Check for plans with >128 levels of nesting

---

sp_BlitzWho.sql

#845 sp_BlitzWho - use read uncommitted

---

sp_BlitzCache.sql
sp_BlitzWho.sql

Fixing slow performance issue (maybe?).
Works but needs testing under more load.
Closes #847

Table variables ftw

---

sp_BlitzWho.sql

Fixes issue with math overflow

---

sp_Blitz.sql

One source for trace file path

---

sp_BlitzCache.sql

Closes out minor items before adding QS support.

Sp blitzcache erikspecial

---

sp_BlitzIndex.sql

Sp blitzindex 825

---

README.md
sp_BlitzBackups.sql

Add sp_BlitzBackups to dev branch

Issue 866 erik

---

sp_BlitzBackups.sql

Bug fixes and performance improvements

---

sp_BlitzBackups.sql

If you don't have any data to move, StartDate can end up being NULL and
running forever.

Issue 866/continued

---

sp_BlitzCache.sql

Closes #881
Closes #862
Closes #861

Sp blitzcache vnexting

---

sp_BlitzCache.sql

Formatting

---

sp_BlitzBackups.sql

Closes #887
Stops flagging the most common backup operator name, and also dismisses user names who have only taken a single backup.

Closes #887

---

sp_BlitzBackups.sql

Also added check for MSDBname database existence. Closes #897.

Issues 897/brent

---

sp_Blitz.sql

Amazon RDS was skipping more checks than it should. Closes #877.

#877 sp_Blitz SkipChecks was excluding too many checks

---

sp_BlitzBackups.sql

Fixes some string prefix issues
Changes table creation method
Fixes issue in data mover

Sp blitzbackups review

---

sp_BlitzBackups.sql

This changes the queries we used to populate the #Recoverability table
- Use compressed backup size instead
- Standardize output to MB to match other tables
- Change column names and types (adds MB, changes to decimal) to
standardize output
- Respect passed in @StartTime parameter for calculations

Query changes to determine avg sizes/throughput etc

---

sp_BlitzBackups.sql

Fix the math behind big logs and big diffs

Sp blitzbackups 911

---

sp_BlitzWho.sql

Adds tempdb allocations

---

README.md

Issue 930/brent - Readme.md

---

sp_BlitzQueryStore.sql

Altered the version checks (both pre-execution of stored proc code, and within the stored proc) in `sp_BlitzQueryStore` to account for being created and executed on an Azure SQL database (PaaS).
As discussed [here](https://www.brentozar.com/archive/2017/06/introducing-sp_blitzquerystore/#comment-2419088).
- Alter the script to allow creating and executing `sp_BlitzQueryStore` on an Azure SQL Database (PaaS) database.
- Create & execute `sp_BlitzQueryStore` on an Azure SQL database.
- Azure SQL DB

Make stored proc compatible with Azure Database

---

sp_BlitzQueryStore.sql

Adds some comments in
Closes #940
Closes #934

Comments and fixes

---

sp_BlitzWho.sql

Adds debug option
Adds top session waits (when available) from `sys.dm_exec_session_wait_stats`.

Sp blitzwho 895

---

sp_BlitzFirst.sql

#928 sp_BlitzFirst PLE doesn't always show

---

sp_BlitzWho.sql

Add Resource Governor info

---

sp_DatabaseRestore.sql

Reverts BrentOzarULTD/SQL-Server-First-Responder-Kit#945

Revert "Fixes Issue #923"

---

README.md
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_DatabaseRestore.sql

Issue 936/brent

---

README.md

#955 readme.md documentation for sp_DatabaseRestore

---

sp_BlitzWho.sql

I made the extra join dynamic, but not the column in the select list.
Closes #963

Fixes an issue with additional session waits

---

sp_AllNightLog.sql

That's not a good idea.
Closes #966

There shouldn't be a space there.

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Adds detection and warnings for index spools

Sp bqs 969

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Validates the eagerness of the spool

Closes #972

---

sp_BlitzQueryStore.sql

Adds filtering on plan_id and query_id

---

sp_AllNightLog_Setup.sql

#985 sp_AllNightLog - fix date typo

---

sp_AllNightLog.sql

#992 sp_AllNightLog - warn if xp_cmdshell is disabled

---

sp_AllNightLog_Setup.sql

#992 sp_AllNightLog_Setup checking for xp_cmdshell

---

sp_AllNightLog.sql
sp_AllNightLog_Setup.sql

In both sp_AllNightLog and sp_AllNightLog_Setup. Closes #991.

#991 sp_AllNightLog - check for Ola's and sp_DatabaseRestore

---

sp_AllNightLog.sql

#993 sp_AllNightLog dynamic folder path support

---

sp_AllNightLog.sql

#997 sp_AllNightLog - terminate if jobs are not enabled

---

sp_AllNightLog_Setup.sql

New @EnableBackupJobs and @EnableRestoreJobs switches. Closes #988.

#988 sp_AllNightLog_Setup enable/disable jobs

---

sp_AllNightLog_Setup.sql

Preparing for skipping databases, doing full/diff backups/restores.
Also tweaks job start time to today. For #958.

#958 sp_AllNightLog_Setup - adding worker table fields

---

sp_AllNightLog_Setup.sql

See issue #1010 on this - the code diff doesn’t tell the full story.
Closes #1010.

#1010 sp_AllNightLog_Setup - wait for disabled jobs to stop

---

sp_AllNightLog_Setup.sql

#1014 sp_AllNightLog_Setup double jobs declare

---

sp_BlitzWho.sql

This fixes incorrect blocking information detailed in #1017

Closes #1017

---

sp_BlitzWho.sql

Sp blitzwho 1017

---

sp_BlitzWho.sql

Took the path of least resistance and gave the query ABS of steel.

Closes #1031

---

sp_Blitz.sql

Fixes undeclared N/VARCHAR lengths in queries. This pleases the
Bertrand.

Closes #1023

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Adds row variance checks to both stored procs
Closes #1030

Sp blitzcache querystore 1030

---

sp_BlitzQueryStore.sql

Closes #1034
Tested on CS 2016 and 2017

Add support for new columns in 2017

---

sp_DatabaseRestore.sql

Closes #977
Adds quote name and preserves correct results when restoring logs
Closes #1039
Fixes some fragile aspects of moving files during restore

Fixes two restore issues

---

sp_Blitz.sql

#1029 sp_Blitz only alert on CMEMTHREAD for multiple NUMA nodes

---

sp_Blitz.sql

#1042 sp_Blitz show # of objects with low fill factor

---

sp_Blitz.sql

#1041 sp_Blitz skip DBCCs from monitoring tools

---

sp_Blitz.sql

Add BEGIN/END to IF block that checks the number of memory dumps in the
past year.

Closes #1049

---

sp_BlitzWho.sql

Adds percent complete column to output

Closes #1021

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

#1082 sp_Blitz warn if CheckUserDatabaseObjects was disabled

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

sp_BlitzCache -- row estimate mismatch and forced serial issues

---

sp_Blitz.sql

Adds begin/end block to check proc cache.

Closes #1093

---

sp_Blitz.sql

This is not full support for SQL Server on Linux, but it does fix a couple of bugs that occurred when running on SQL Server 2017 RC2 on Ubuntu.
- Fixed path separator depending on operating system.
- Test for minimum value of `DATETIMEOFFSET` when casting to `DATETIME`.
- Detecting operating system version, using `sys.dm_host_info` if available.
Has been tested on:
- SQL Server 2017 RC2 on Ubuntu Linux 16.04 LTS
- SQL Server 2017 CTP2 on Windows Server 2016

Preliminary SQL Server on Linux support

---

sp_BlitzWho.sql

Fix issue with multiple rows showing up

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Adds Switch operator detection to BlitzCache and QueryStore.
This has no practical use other than academic interest.

Closes #976

---

sp_AllNightLog.sql

If the database doesn’t exist after the first full restore attempt, set
restore_worker.error_number = -1 to call for human attention. Related
to #1005 but doesn’t close the symptoms in the issue.

#1005 sp_AllNightLog - don't retry failed full restores

---

sp_AllNightLog.sql
sp_AllNightLog_Setup.sql

#1037 sp_AllNightLog - add backup encryption support

---

sp_AllNightLog_Setup.sql

If @EnableRestoreJobs = 1 but msdbCentral is restoring, try to bring it
online first. Closes #1016.

#1016 sp_AllNightLog_Setup recover msdbCentral if necessary

---

sp_AllNightLog.sql

If we need to escalate backups to fulls based on MSDB history. Closes
#1005.

#1005 - sp_AllNightLog pass ChangeBackupType to Ola

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

#1100 sp_Blitz add check for certs not backed up

---

sp_Blitz.sql

#1110 sp_Blitz filtering DBCC CHECKDB

---

sp_BlitzWho.sql

#1112 sp_BlitzWho add support for live query plans

---

sp_Blitz.sql

Fix XE session names we filter out

---

sp_BlitzQueryStore.sql

Corrects parameterization warning query

---

sp_BlitzQueryStore.sql

Fixes plan costing for stored procs

---

sp_BlitzQueryStore.sql

Drop threshold from 10000x to 100x
Closes #1122

Change parameter sniffing calculations

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Adds more help lines to the end output

Closes #1099

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Closes #1129
I still have to add the same for BQS, but I want to make a PR just in case anything catastrophic happens.

Adds implicit conversion info to sp_BlitzCache

---

sp_BlitzCache.sql

Removes pretty useless plan cache checks.

Closes #1141

---

sp_BlitzCache.sql

Moves Query Plan column in diaplyed results. Also adds in some missing
semicolons.

Closes #1146

---

sp_BlitzCache.sql

Adds debugging and maybe adds new bugs!

Closes #1140

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Accounts a bit for NULLs and adds new parsing to find column to column
implicit conversion.

Closes #1139

---

sp_BlitzIndex.sql

If there’s over 100 partitions and @BringThePain wasn’t set to 1, set
@SkipPartitions = 1. Closes #1132.

#1132 sp_BlitzIndex - skip >100 partitions

---

sp_BlitzCache.sql

Going after Brent's issues in #1159

An attempt was made

---

sp_BlitzCache.sql

For logging to table synchronized w/sp_BlitzFirst. Closes #1166.

#1166 sp_BlitzCache add CheckDateOverride parameter

---

sp_BlitzCache.sql

Adds time filtering

---

sp_BlitzCache.sql

#1167 sp_BlitzCache debugging logging to table

---

Documentation/sp_BlitzFirst Checks by Priority.md
sp_BlitzFirst.sql

#1169 sp_BlitzFirst - calling sp_BlitzCache, syncing to table

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Porting changes

---

Documentation/sp_BlitzFirst Checks by Priority.md
sp_BlitzFirst.sql

#1175 sp_BlitzFirst add LogMessage functionality

---

sp_BlitzQueryStore.sql

Jump around, etc.
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB

Closes #1178

---

sp_BlitzQueryStore.sql

Get in there.
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB

Closes #1182

---

sp_BlitzCache.sql

Adds count of plans to the percentages line
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB

Closes #1195

---

sp_BlitzFirst.sql

#1177 sp_BlitzFirst more reader-friendly CPU check 24 results

---

sp_BlitzFirst.sql

Need an additional convert to make these dates work.
Fixes #1200
Adds a convert to `DATETIMEOFFSET` to keep code from barfing.
Run with `@AsOf` parameter.
Will be tested for FRK release.

Closes #1200

---

sp_BlitzFirst.sql

#1213 sp_BlitzFirst delta views - skip collections in the same minute

---

sp_BlitzFirst.sql

If the output database/schema/table names weren’t passed in, try some
defaults. Add a return success message. Closes #1217.

#1217 sp_BlitzFirst LogMessage usability improvements

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

Also changed priorities & descriptions of a few of the new DBCC ones.
Closes #1205.

#1205 sp_Blitz deduping CheckID's

---

sp_Blitz.sql

Reflecting unsupported service packs on 2012/2014. Closes #1199.

#1199 sp_Blitz update unsupported build list

---

sp_BlitzCache.sql

#1230 sp_BlitzCache - @ExportToExcel had missing param in dyn SQL

---

sp_BlitzFirst.sql

Defaults to 7 days. Closes #1232.

#1232 sp_BlitzFirst add @OutputTableRetentionDays parameter

---

CONTRIBUTING.md
README.md

Since it’s not a diff-able file. Closes #1234.

#1234 documentation on how to contribute to Power BI

---

README.md
sp_BlitzQueryStore.sql

Fixes # .
Adds read me info for BQS.
It's just the readme
NA

Issue 1222

---

sp_foreachdb.sql

sp_foreachdb - handle database names the same way as sp_MSforeachdb #536

---

README.md

#1264 remove Azure SQL DB support references

---

sp_BlitzLock.sql

Fixes #1223 
Adds new proc: sp_BlitzLock
Run on a server experiencing deadlocks

Issue 1223

---

sp_BlitzLock.sql

Set nocount on
Set read uncommitted
Add recompile hints
Add version
Tidy up help
Add documentation
Fixes #1274
Set nocount on
Set read uncommitted
Add recompile hints
Add version
Tidy up help
Add documentation

Easy changes for release

---

sp_BlitzLock.sql

Database name
Object name
Stored procedure name
App name
Host name
Login name
Fixes #1273 
- Adds more filtering
Filter for any of those doodads

Add more filtering

---

sp_BlitzLock.sql

Distinct stuff.
Fixes #1285 
- Distinct-ify some data.
This is hopefully just defensive coding on my part. You should see little data duplication in the table results.

Fix duplication issues

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

Changing from 10 to 200. Closes #1281.

#1281 sp_Blitz changing Query Store alert priority

---

sp_BlitzIndex.sql

Didn’t test before/after performance, but looks legit. Closes #1149.

#1149 sp_BlitzIndex add clustered index on IndexColumns table

---

sp_BlitzLock.sql

That other stuff was dumb.
Fixes #1285 1275
Simplify reporting query at the end
Don't be dumb like me

Simplify reporting

---

sp_BlitzLock.sql

Fixes #1291 
- There's a bunch of stuff detailed in the issue
Run the proc, I guess.

Issue 1291

---

sp_BlitzLock.sql

Sigh
Fixes #1298
- Adds event date join because SQL REUSES PROCESS IDS
- Jump out a window

Fixes #1298

---

sp_BlitzLock.sql

YAY UNIQUENESS
Fixes #1300 
- Adds event date to all tables
- Your mom

Adds event date to all tables

---

sp_BlitzLock.sql

Fixes #1302 
- Buncha stuff
- Have deadlocks

Issue 1302

---

sp_BlitzLock.sql

Screw it
Fixes # .
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB

Pull early ejects

---

sp_BlitzLock.sql

Remove dumb parsing
Fixes #1307 
- Removes unnecessary string parsing to retrieve object names with addition of event date to tables and joins
- DUMB LUCK

Pre-FRK fixing

---

sp_BlitzWho.sql

Fixes #1188
- Adds expert mode
- Clarifies memory used origins
- Adds context info
- Run it, run it
I also overrode the product version to make sure the old sql block compiled.

Issue 1188

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Fixes #1322
- Increase data sizes for implicit conversion and variable info tables.
- Be @rossw99 and pass in some big variables 

Issue 1322

---

sp_BlitzCache.sql

Add schema prefix to proc and function names.
Fixes #1325 
- We'll get the schema prefix of stored procs now, too.
- Run and filter for stored procs `EXEC sp_BlitzCache @QueryFilter = 'proc'`

Closes #1325

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

your mom
Fixes #1331 
- Adds URLs to warning table
- New URLs should show up in rolled up warnings.

Adding URLs

---

README.md

Refer people to Slack first, then Github, then DBA.se. Closes #1335.

#1335 README.md clarification for how to get support

---

Documentation/sp_Blitz Checks by Priority.md

Include "Thanks!" result listing (for completeness)
Fixes #1363 .
- Added "thanks" findings group to documentation
- View https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/Documentation/sp_Blitz%20Checks%20by%20Priority.md
N/A (documentation fix)

Update sp_Blitz Checks by Priority.md

---

sp_BlitzCache.sql

Calling it quits on this for now, but may need to leave that issue open
if Erik wants to take another look.

#1349 sp_BlitzCache make warnings fire more consistently

---

sp_BlitzLock.sql

Fixes #1350 
- Fix XML parsing
-  Accidental support for parallel deadlocks
- Run it
- Run it on a server where you're unlucky enough to have parallel deadlocks

Issue 1350

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Also low-key tries to fix the truncation stuff. I got carried away.
Fixes #1370
- Add row goal info
- Maybe fixes the truncation errors
- Run to the hills

Closes #1370

---

sp_BlitzCache.sql

Reverts BrentOzarULTD/SQL-Server-First-Responder-Kit#1351

Revert "#1349 sp_BlitzCache make warnings fire more consistently"

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

For real this time!
Fixes #1349
- Make warnings fire more reliably
- 
- 
- 

Closes #1349

---

sp_BlitzCache.sql

Yeehaw!
Fixes Maybe 1376
- Add cdata tags to xml parsing, expand column defs.
- Test on a really weird server

Stab at fixing illegal XML chars

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Fixes #1410
- Add checks for MSTVFs with 1/100 row estimates
- Run on servers with MSTVFs

Issue 1410

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Yeehaw.
Fixes #1397
- Adds check for many to many merge joins
- Have some crappy merge joins

Issue 1397

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

For new SQL 2017 CU4 sys.dm_os_sys_info.container_type_desc. Closes
#1447.

#1447 sp_Blitz add container info

---

sp_Blitz.sql

#1481 sp_Blitz Managed Instance compatibility

---

sp_Blitz.sql

Frames it in dynamic SQL. Closes #1465.
- Check 215 used sys.dm_exec_sessions.database_id, but that doesn't exist on 2008 & R2. Framed it in dynamic SQL.
- Run sp_Blitz as-is in the current version, and it fails on 2008 & R2. It'll work with this fix.

#1465 implicit trans check on 2008

---

sp_BlitzLock.sql

This adds the new parallel deadlock columns to XML parsing and output tables.
Fixes #1496 
- Adds new parallel deadlock columns from 2017 CU5
- Doesn't add new Batch Mode ones yet 
- Limits the rows returned for a parallel deadlock to one
On 2017 CU5, run this:
```
EXEC DropIndexes;
GO
CREATE INDEX ix_posts
ON dbo.Posts ( OwnerUserId );
CREATE INDEX ix_badges
ON dbo.Badges ( UserId );
SELECT      TOP 10 p.OwnerUserId
FROM        dbo.Posts AS p
WHERE       NOT EXISTS (   SELECT   *
FROM     dbo.Badges AS b
WHERE    p.OwnerUserId = b.UserId )
ORDER BY    p.OwnerUserId
OPTION(MAXDOP 4, USE HINT('ENABLE_PARALLEL_PLAN_PREFERENCE'), MERGE JOIN, HASH GROUP, QUERYTRACEON 8688)
```
It will parallel deadlock like a summagun, then run …

Add new parallel columns

---

sp_Blitz.sql

Fixes #1484
- Add a high priority check for a reboot in the last 24 hours.
- Well don't run out and reboot your server. I did that so you don't have to.

Adds high priority reboot check

---

sp_BlitzFirst.sql

Fixes #1511
- Adds version dependent check on implicit transactions
- It will now not throw errors

Add version dependency

---

sp_BlitzIndex.sql

Dang.
Fixes #1513
- Covers some more unicode scenarios
- 
- Amazon RDS
- Azure SQL DB

Closes #1513

---

sp_Blitz.sql

Change wording if trace flag 8048 is already enabled. Closes #1537.
- Move CMEMTHREAD check to after the globally enabled trace flags check so #TraceStatus is already populated.
- Join to #TraceStatus, look to see if 8048 is on, and if so, change wording to say 'despite trace flag 8048 being enabled already.'
- Good luck with getting a server this big and generating CMEMTHREAD waits.

#1537 sp_Blitz CMEMTHREAD

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Closes #1526
AS [processing-instruction(ClickMe)] FOR XML PATH(''), TYPE )
- Use `processing-instruction` to handle XML oddities.
```
CREATE OR ALTER PROCEDURE dbo.TagSearch ( @Tag SQL_VARIANT)
AS
BEGIN
SELECT COUNT(*) AS records
FROM   dbo.Posts AS p
WHERE  p.Tags = @Tag;
END;
GO
EXEC dbo.TagSearch @Tag = N'%<sql-server>%'
EXEC master.dbo.sp_BlitzCache @StoredProcName = 'TagSearch', @Debug = 1;
```

Issue 1526

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Fixes #1562
Fixes #1563
- Add ANSI SET options to cached parameter column
- Move relop warning checks to expert mode
- Search for a stored proc with cached parameters, ANSI warnings should show up in the clickable
- Relop warnings should only fire under expert mode

SET options etc

---

sp_BlitzFirst.sql

Only alert on free memory over 20GB. Closes #1580.

1580 sp_BlitzFirst memory grants

---

sp_BlitzLock.sql

Fixes #1590. 
- As described in the issue
- Run `exec sp_BlitzLock` on an instance that has fresh and tasty deadlocks in the system_health event session

Add full deadlock graph to BlitzLock results

---

LICENSE.md
README.md

Updating readme, license for sp_BlitzInMemoryOLTP. Closes #1604.

#1604 readme & license for in-memory OLTP

---

sp_BlitzInMemoryOLTP.sql

Fixes # . Fixed bugs related to running instanceLeveOnly on Azure SQL DB.
- 
- 
- 
- EXEC sp_BlitzInMemoryOLTP
- 
- 
- Azure SQL DB

Fixed bugs related to instanceLevelOnly on Azure SQL db.

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Closes #1624
- Change XML conversion in update to MAX.
- Be @digitalohm 

Fix XML > string error

---

sp_Blitz.sql

Fixes #1633 
- Sum up amount of USERSTORE_TOKENPERM entries in dm_os_memory_cache_entries. If it's > 2 GB, warn about it with recent plan cache clearing.
- I have no idea how to get that cache entry to be really high, so I'm flying a little blind on this one.

Add userstore token

---

sp_Blitz.sql

Fixes #1633 
- Fix queries and maths.
- There's a repo in the #1636 

Issue 1633 redux

---

sp_BlitzCache.sql
sp_BlitzIndex.sql

Fixes #????
- Nothing to see here.
- You don't.
- Amazon RDS
- Azure SQL DB

Die hand die verletzt

---

sp_BlitzCache.sql

Fixes #1650
Fixes # .
- See #1650 for details
- See #1650 for details

Add executions to join

---

sp_DatabaseRestore.sql

Fixes #1653 .
- Use xp_dirtree instead of xp_cmdshell
- See original issue for the setup

Issue 1653 sp_DatabaseRestore xp_dirtree

---

sp_BlitzIndex.sql

Fixes #1610 
- Script renaming of DTA indexes rather than create scripts
- Run on a database with DTA indexes in them

Issue 1610

---

sp_Blitz.sql

Change from instances running to instances installed (since they might be off.) Closes #1669.

#1669 sp_Blitz instance stacking wording

---

sp_DatabaseRestore.sql

Fixes # 1671
Honor @StandyMode parameter for full and differential database restore
EXEC [dbo].[sp_DatabaseRestore]
@Database = 'MyDB',
@RestoreDatabaseName = 'Ariba_Vault',
@BackupPathFull = 'C:\SQL\MSSQL2016\Backup\MyDB\FULL', 
@MoveFiles = 1, 
@StandbyMode = 1,
@StandbyUndoPath = 'C:\SQL\MSSQL2016\Backup',
@ForceSimpleRecovery = 1,
@ExistingDBAction = 1,
@Debug = 0;
EXEC [dbo].[sp_DatabaseRestore]
@Database = 'MyDB',
@RestoreDatabaseName = 'MyDB',
@BackupPathDiff = 'C:\SQL\MSSQL2016\Backup\MyDB\DIFF',
@MoveFiles = 1,
@RestoreDiff = 1,
@StandbyMode = 1,
@StandbyUndoPath = 'C:\SQL\MSSQL2016\Backup',
@ForceSimpleRecovery = 1,
@ExistingDBAction = 1,
@Debug = 0;
The database should be restored to a Read Only/Stand By state.
Has …

Honor @StandbyMode paramter for full and differential database restore

---

sp_BlitzIndex.sql

Now 2 warnings for forwarded fetches and for deletes. Closes #1685.
How to test this code: see the repro code in the issue.

#1685 sp_BlitzIndex split heap warnings

---

sp_BlitzFirst.sql

Closes #1676
- Handle long strings betterer to avoid angering ther XML gods.
- Repro output is in the issue, user tested

Strings are hard

---

sp_Blitz.sql

Fixes something Brent has wanted to do for years, but has been too lazy. (This is Brent typing.)

Change tab to spaces

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Closes #1724
- Parse out index spools to make missing index requests.
- Have an index spool

This is a triumph

---

sp_BlitzCache.sql

Fixes #1352
- Fixes weighting column percentages
- Nevermind the Spoolocks
- 
- The "Weight" columns should be correct and tally up to close to 100%

Weights should be correct now

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

If you liked Men Without Hats, you'll love Statistics Without Histograms. Closes #1757.

#1757 sp_Blitz - checking for statistics

---

sp_BlitzIndex.sql

Fixes #1712
- Filter dupe checks for size in both applicable places
- Create two indexes with the same key columns, but different includes, so that one is < 250MB, and one is > 250MB. Run `@GetAllDatabases = 1`, watch one show up and the other not.

Dupe check fix

---

sp_Blitz.sql

Fixes #1762 .
- Add a new parameter to sp_Blitz that allows the caller to pass a "UsualDBOwner" to be used in CheckID 55 (for organizations where "sa" is not typically the database owner on user databases)
- Create some databases owned by 'sa' and some owned by whatever other account
- Run `EXEC dbo.sp_Blitz @UsualDBOwner = 'TheOtherAccount';`
- Verify the databases owned by 'sa' are reported in the results of CheckID 55

Add parameter for the usual DB owner

---

sp_Blitz.sql

#1775 sp_Blitz skip growth checks on read only dbs

---

sp_Blitz.sql

Clearing out some false alarms for Azure Managed Instances. Closes #1796.
- Azure SQL DB Managed Instances

#1796 sp_Blitz Managed Instances support

---

.github/bug_report.md
.github/feature_request.md

See details here https://blog.github.com/2018-05-02-issue-template-improvements/

Update and separate github issue templates to modern version

---

sp_BlitzCache.sql

Closes #1811
Fixes # .
- Fix some substring and formatting issues with the implicit conversion XML.
- BRING THE PAIN

Fix some dumb things

---

sp_BlitzFirst.sql

Fixes # 1804
- 
- 
- 
- 
- 
- 
- Amazon RDS
- Azure SQL DB

Issue 1804

---

sp_BlitzCache.sql
sp_BlitzQueryStore.sql

Closes #1818
- Differentiates between cursor and non-cursor plans
- Also brings some lagging parts of BQS up to BC 'standards'
- Watch them skip or analyze cursor plans?

Fixes some cursor stuff

---

sp_BlitzFirst.sql

Changing wait type list, adding ntile. Closes #1835.
- Azure SQL DB

#1835 sp_BlitzFirst startup times in Azure

---

sp_BlitzCache.sql

Closes #1850
- Check for row goal info in plan XML

Row goals in 2014 XML

---

sp_BlitzCache.sql

Closes #1863
- use dm_exec_function_stats to get function names
- 2016+

Naming the function

---

sp_BlitzLock.sql

Closes #1862
With some help from @jobbish-sql
- Restructure XML parsing queries to speed things up
- Just run it!

PERFORMANCE ENHANCING

---

sp_BlitzLock.sql

Closes #1865
- Collect Agent Job info from deadlock XML
- Have Agent Jobs involved in deadlocks.

Add Agent Job Info

---

sp_Blitz.sql

Closes #1874.
- Fixed capitalization in sp_Blitz.
- Run sp_Blitz
- Check spelling
- Drink beer
Ain't nobody got time for that, I'm in front of a live studio audience.

1874 - fixing capitalization in sp_Blitz

---

sp_DatabaseRestore.sql

Fixes #1854 
- @MoveFiles defailt now 1
- Suppress MOVE option for identical files
Unsure

Issue 1185 move file tweak

---

sp_Blitz.sql

Adding filter for that app name. Closes #1903.

#1903 sp_Blitz SQLServerCheckup

---

sp_BlitzIndex.sql

Nothing against BOU, just don't need it in that particular place. Closes #1905.

#1905 sp_BlitzIndex remove BOU link

---

LICENSE.md
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql

Ah, the glamour. Closes #1908.

#1908 Update copyright dates

---

sp_Blitz.sql

#1916 sp_Blitz ignore backup on TempDB drive

---

sp_Blitz.sql

1919 sp_Blitz ignoring a few checks for Managed Instances

---

sp_BlitzIndex.sql

Joined output query to #IndexCreateTsql to retrieve the CreateTsql already generated earlier in the script.  Created Drop TSQL based on evaluating what type of index was present.
Fixes # .
For @mode = 2, add columns for Drop Index and Create Index, populated with the commands to drop and recreate separately.
--Query to return the results to SSMS or Azure Data Studio.
EXEC dbo.sp_BlitzIndex @DatabaseName = N'',  --Define index review database
@Mode = 2
--Query to test outputting the results to a table on your instance.
EXEC dbo.sp_BlitzIndex @DatabaseName = N'',  --Define index review database
@Mode = 2,
@OutputDatabaseName = '', --Define the database to write results to
@OutputSchemaName = 'dbo',
@OutputTableName = …

BrentOzarULTD#1921 Sp_BlitzIndex Add Drop and Create Columns to Output

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

For new SSAS/IS/RS check. Closes #1943.

#1943 adding URL

---

sp_BlitzCache.sql

Azure SQL DB compatibility and removing bou from global temp table names. Closes #1935.

#1935 sp_BlitzCache Azure compatibility

---

sp_BlitzIndex.sql

#1973 sp_BlitzIndex truncation error

---

Documentation/sp_Blitz Checks by Priority.md

203 and 224 were swapped in the documentation. Closes #1966.

#1966 fix sp_Blitz check IDs

---

sp_BlitzFirst.sql

Fixing error when calling sp_BlitzCache. Closes #1983.

#1983 sp_BlitzCache sort order

---

sp_DatabaseRestore.sql

Included check for StopAt when ContinueLogs = 1

Issue #1986 @StopAt Ignored.

---

sp_Blitz.sql

Only run Check 93 if @IsWindowsOperatingSystem = 1
This is in regards to BrentOzarULTD/SQL-Server-First-Responder-Kit#1995

Update Check 93

---

sp_BlitzCache.sql

#2000 sp_BlitzCache add SearchSlowly parameter

---

sp_DatabaseRestore.sql

Set @DiffLastLSN in case no DIFF backup files are found, otherwise the logs won't get restored

#1998 sp_DatabaseRestore

---

sp_Blitz.sql

#2005 sp_Blitz version numbers

---

sp_BlitzQueryStore.sql

Changed alias on a temp table to match other nearby aliases. Closes #2024.

#2024 sp_BlitzQueryStore s.is_cursor error

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

Changed wording from "consistency check" to "version check," updated check IDs, removed mandatory scripts. Closes #1994.

#1994 sp_Blitz version checking

---

sp_BlitzIndex.sql

Adds new IgnoreDatabases parameter, and skips databases with >100 partitions. Closes #1944.

#1944 sp_BlitzIndex ignore databases

---

sp_BlitzCache.sql
sp_BlitzFirst.sql

Use SkipAnalysis = 1, SortOrder = all when calling sp_BlitzCache. Closes #2009.

#2009 sp_BlitzFirst call BC differently

---

sp_BlitzCache.sql

#2026 sp_BlitzCache show multiple plan count

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

#2017 sp_Blitz Evaluation Edition expiration check

---

sp_BlitzCache.sql

Changing MONEY on totals to BIGINT. Closes #2018.

#2018 sp_BlitzCache arith overflow

---

sp_BlitzCache.sql

#2019 sp_BlitzCache air_quote_actual plans

---

sp_DatabaseRestore.sql

To resolve Issue 2036, moved SQL header syntax build outside of if block so that it is constructed when the full backup path is null.

Moved SQL header build outside of If block

---

sp_Blitz.sql
sp_BlitzFirst.sql

Clarify warnings in sp_Blitz, sp_BlitzFirst. Closes #2042.

#2042 implicit transaction troubleshooting

---

sp_Blitz.sql

fixes #2055 
simple typo fix.
Tested on SQL Server 2014

sp_Blitz - correct invalid hyperlink

---

sp_BlitzCache.sql

ignore readable secondaries in sp_blitzcache

---

sp_DatabaseRestore.sql

#2067 Updating directory "/" fixing to work with URLs

---

sp_BlitzIndex.sql

Strip out CR/LF from @IgnoreDatabases, trim spaces afterwards. Closes #2053.

#2053 sp_BlitzIndex ignoring databases

---

sp_Blitz.sql

Adds Windows 10's new Ultimate Performance Power Mode, whatever that is. Closes #2044.

#2044 sp_Blitz new power mode

---

sp_DatabaseRestore.sql

Change from uppercase to lowercase for case-sensitive systems. Closes #2097.

#2097 sp_DatabaseRestore sysname caps

---

sp_BlitzIndex.sql

Breaking this up into #temp tables has made it much faster on servers with many partitions.

Fix compression query perf

---

sp_BlitzCache.sql

Cleans up the documentation, closes #2111.

#2111 sp_BlitzCache missing union all

---

sp_BlitzCache.sql

Closes #2114 
Semicolon throws syntax error.

Remove stray semicolon

---

sp_BlitzCache.sql

Closes #2113 
Where clause should only look at flagged lines.

Fix roll up where clause

---

sp_BlitzFirst.sql

Not really about BST, heh, but just using the wrong date/time format. Closes #2096.

#2096 sp_BlitzFirst BST compatibility

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_foreachdb.sql
sp_ineachdb.sql

Bumping version numbers, dates, install scripts. Closes #2119.

#2119 2019-09 release prep

---

sp_BlitzQueryStore.sql

Fixes version check against Azure SQL DB. Closes #2124

#2124 Fix BlitzQueryStore Edition Check Comparison

---

sp_DatabaseRestore.sql

Issue 2127/fvanderhaegen

---

sp_Blitz.sql

Added new SkipBlockingChecks parameter. Closes #2130.

#2130 sp_Blitz blocked due to DMV bug

---

sp_BlitzFirst.sql

#2135 sp_BlitzFirst log message dates

---

sp_Blitz.sql

#2141 sp_Blitz UNC backup check

---

README.md
sp_BlitzCache.sql

Can now sort by query hash plus a second sort field, and avoids calling the proc again. Closes #2156.

#2156 sp_BlitzCache query hash sorting

---

sp_BlitzLock.sql

Filters & displays local time instead of UTC. Closes #2147.

#2147 sp_BlitzLock in local time

---

sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzWho.sql

Fixes a few different related bugs - see the issue for details. Closes #2159.

#2159 sp_BlitzFirst calling sp_BlitzWho

---

sp_BlitzFirst.sql

Passes BlitzCacheSkipAnalysis parameter to sp_BlitzCache. Closes #2155.

#2155 sp_BlitzFirst adding SkipAnalysis param

---

sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzWho.sql

#2162 add JoinKey columns to output tables

---

sp_BlitzWho.sql

Create the table, THEN alter it, you moron. Closes #2166.

#2166 sp_BlitzWho alter table order

---

sp_BlitzCache.sql

Now works with SortOrder = 'all'. Closes #2168.

#2168 sp_BlitzCache MinutesBack

---

SqlServerVersions.sql
Uninstall.sql
sp_BlitzFirst.sql

Various Typo Fixes

---

sp_BlitzIndex.sql

To table-level output. Closes #2177.

#2177 sp_BlitzIndex add drop T-SQL

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

Bumping version numbers, dates, building combined installer script. Closes #2203.

#2203 prepping 2019_12 release

---

Documentation/sp_BlitzCache Checks by Priority.md
sp_BlitzCache.sql

#2214 sp_BlitzCache add URL for plan cache information

---

Documentation/sp_Blitz Checks by Priority.md
sp_Blitz.sql

#2211 sp_Blitz add more info query for DBCC

---

sp_BlitzIndex.sql

#2229 add sp_BlitzIndex Debug parameter

---

sp_BlitzWho.sql

Dropping hint to 1%, plus throwing in an option recompile hint to foil Tara's monitoring. Closes #2238.

#2238 sp_BlitzWho memory grant fixes

---

sp_BlitzFirst.sql

Account for long-running sp_BlitzWho processes when setting start/finish sample times. Closes #2244.

#2244 sp_BlitzFirst sample times

---

Documentation/sp_BlitzCache Checks by Priority.md
sp_BlitzCache.sql

I AM A SCRUM MASTER

---

sp_BlitzFirst.sql

To help troubleshoot HADR_SYNC_COMMIT. Closes #2246.

#2246 sp_BlitzFirst added AG Perfmon counters

---

sp_BlitzFirst.sql

Look for temp tables with high forwarded fetches. Closes #2248.

#2248 sp_BlitzFirst tempdb forwarded fetches

---

sp_BlitzCache.sql

To keep sp_BlitzCache out of the plan cache. Closes #2253.

#2253 sp_BlitzCache query needs recompile

---

sp_BlitzIndex.sql

Running in Mode 3 for all databases even when BringThePain = 0. Closes #2255.

#2255 sp_BlitzIndex ignoring BringThePain

---

sp_BlitzLock.sql

For this: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2225

sp_BlitzLock: add output tables

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
LICENSE.md
README.md
SqlServerVersions.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

#2262 2020-01 Release

---

Documentation/sp_Blitz_Checks_by_Priority.md
sp_Blitz.sql

#2265 sp_Blitz data size check

---

sp_BlitzCache.sql

Gets the query hash from the plan XML, also changes the join semantics to make sure the rows matched have writes associated with them.
Closes #2290

Issue 2290: Select with writes bug

---

sp_Blitz.sql

Now only SP3 and newer are supported. Closes #2293.

#2293 sp_Blitz 2014 support builds

---

SqlServerVersions.sql

With 2019 CU2 and 2017 CU19. Closes #2295.

#2295 Update SqlServerVersions builds

---

sp_BlitzIndex.sql

#2280 sp_BlitzIndex fixing inactive filter

---

sp_BlitzIndex.sql

Had a fix in one part of the code, but not everywhere. Closes #2285.

@2285 sp_BlitzIndex fixing datatype sizes

---

sp_BlitzIndex.sql

From index creation suggestions. Closes #2292.

#2292 sp_BlitzIndex remove IX prefix

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
README.md
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

Updating dates, build scripts. Closes #2301.

#2301 2020-02 release prep

---

sp_BlitzLock.sql

#2286 - Show all parallel deadlocks

Show all parallel deadlocks

---

Uninstall.sql

Now works on case-sensitive collations. Closes #2307.

#2307 uninstall case sensitive

---

sp_BlitzFirst.sql

Was trying to insert strings into a database ID, hahaha. Working on #2311.

#2311 sp_BlitzFirst FilterPlansByDatabase

---

sp_BlitzLock.sql

Works with Express Edition on RDS. Closes #2317.

#2317 sp_BlitzLock on Amazon RDS

---

sp_BlitzWho.sql

Shows accurate milliseconds counts. Closes #2321.

#2321 sp_BlitzWho milliseconds

---

Documentation/sp_BlitzCache_Checks_by_Priority.md

Sorting by priority, adding new check 69 for userstore_tokenperm cache. Working on #2134.

sp_BlitzCache documentation update

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
SqlServerVersions.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

Setting dates, updating installation scripts.

2020_03 release prep

---

sp_BlitzFirst.sql

#2320 sp_BlitzFirst handle inaccurate server names

---

sp_BlitzIndex.sql

I was so excited to get Github working in Azure Data Studio that I forgot to test my code, so of course it was broken. Closes #2314.

#2314 sp_BlitzIndex add forwarded fetches to @Mode = 2

---

Documentation/sp_Blitz_Checks_by_Priority.md
sp_Blitz.sql

Adds new CheckID 233 for USERSTORE_TOKENPERM >= 10% of overall memory. Working on #2134.

#2134 sp_Blitz USERSTORE_TOKENPERM check

---

sp_Blitz.sql

Leftover from live session. Working on #2134.

2134 - sp_Blitz typo extra %

---

sp_BlitzFirst.sql

#2336 sp_BlitzFirst rounding wait times

---

Documentation/sp_Blitz_Checks_by_Priority.md
sp_Blitz.sql

Making it easier to point folks to the default trace. Closes #2338.

#2338 sp_Blitz add DBCC links

---

sp_BlitzFirst.sql

This is for issue #2342 
Let me know if you need me to make any changes.
Nick

Add OutputType = 'Top10' branch

---

sp_BlitzFirst.sql

Only gets Top10 wait types, sets SinceStartup = 1, also accepts Top 10. Closes #2342.

#2342 sp_BlitzFirst Top10

---

sp_BlitzWho.sql

#2328 replaced job_id in program_name with job_name from msdb instead

2328 sp blitz who display job name

---

sp_BlitzCache.sql

Added Remove Plan Handle from Cache column to default output. Closes #2346.

#2346 sp_BlitzCache add column

---

sp_BlitzCache.sql

Skip checking Azure SQL DB Managed Instance. Closes #2353.

#2353 sp_BlitzCache Managed Instances

---

sp_BlitzIndex.sql

Fully qualify drop/create scripts for easier multi-database performance tuning. Closes #2357.

#2357 sp_BlitzIndex fully qualify drop/create scripts

---

sp_BlitzIndex.sql

#2340 sp_BlitzIndex add URL for serial forcers

---

sp_BlitzCache.sql

Switching to dynamic SQL for clerks query. Closes #2372.

#2372 sp_BlitzCache 2008 compat

---

sp_Blitz.sql

#2373 removing non-readable character in sp_Blitz

---

sp_Blitz.sql

#2378 sp_Blitz unprintable characters

---

sp_BlitzCache.sql

About buffer_pool_memory_gb. Closes #2383.

#2383 sp_BlitzCache throwing error

---

Documentation/sp_BlitzFirst_Checks_by_Priority.md
sp_BlitzFirst.sql

Check for recently updated statistics. Working on #2386.

#2386 sp_BlitzFirst new check for stats

---

sp_BlitzCache.sql

Fixes long finding warnings by moving them into details, and more fixes for the buffer_pool_memory_gb variable not being declared. Closes #2390.

2390_sp_BlitzCache_warnings_truncated

---

sp_BlitzCache.sql

#2396 sp_BlitzCache isn't saving QueryPlanHash

---

sp_BlitzFirst.sql

#2401 sp_BlitzFirst get plans for cardinality misestimations

---

sp_BlitzCache.sql

Add it to the table automatically if it doesn't exist. Adds to #2377.

#2377 sp_BlitzCache new LastCompletionTime

---

sp_BlitzFirst.sql

Now goes into one line in the results, with all the stats listed individually in the details. Closes #2386.

#2386 sp_BlitzFirst stats update warning

---

Documentation/Development/_TestBed.sql
Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
SqlServerVersions.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

#2405 2020-06 release prep

---

sp_BlitzFirst.sql

bug fix for issue 2409

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql

Bumping version numbers & dates & installation scripts. Closes #2415.

#2415 20200606 release prep

---

sp_Blitz.sql

Updated and simplified descriptions of Windows versions

Fixes #2418

---

sp_BlitzWho.sql

Handles longer database, schema, and table names. Closes #2421.

#2421 sp_BlitzWho longer table names

---

sp_BlitzFirst.sql

Removes any output when @OutputType = 'NONE' for sp_BlitzFirst

---

Documentation/Development/Merge Blitz.ps1

For each of the 3 scripts to be generated:
Check if SqlServerVersions.sql exists and if so append source to script

Update Merge Blitz.ps1

---

Documentation/Development/Merge Blitz.ps1

Fixing bugs in prior pull request. Closes #2429.

#2429 add SQLServerVersions to build scripts

---

Documentation/sp_BlitzFirst_Checks_by_Priority.md
sp_BlitzFirst.sql

PLE is an outdated metric. Closes #2433.

#2433 sp_BlitzFirst remove PLE warning

---

sp_BlitzLock.sql

Changes Database_Name to database_name on line 219, closes #2440.

#2440 sp_BlitzLock case sensitivity

---

sp_BlitzCache.sql

Possibly fixes possible arithmetic overflow thanks to Santi Swarup Choudhury in Twitch. Closes #2425.

#2425 sp_BlitzCache Arithmetic Overflow

---

sp_BlitzFirst.sql

When server has >20 databases. Closes #2439.

#2439 sp_BlitzFirst skip stats check

---

sp_ineachdb.sql

Fix sp_ineachdb description text

---

sp_DatabaseRestore.sql

#2180 
Only works if using Ola Hallengreen's maintenance solution

2180 : restore database from multiple backup paths - testing needed

---

Documentation/sp_BlitzFirst_Checks_by_Priority.md
sp_BlitzFirst.sql

#2134 sp_BlitzFirst check for UserStore_TokenPerm leak

---

README.md
sp_BlitzIndex.sql

Adds a little Hekaton support, documents support levels for other indexes. Closes #296.

#296 sp_BlitzIndex add a little Hekaton support

---

sp_BlitzIndex.sql

#2447 sp_BlitzIndex Removed code that creates drop index for disabled index.

---

sp_BlitzIndex.sql

Fixing a couple of old typos while I reviewed the code in #2447.

#2447 sp_BlitzIndex typos

---

README.md

#2452 sp_BlitzLock object names with periods

---

sp_BlitzIndex.sql

Sets a 1 second lock timeout when populating temp tables. Closes #2176.

#2176 sp_BlitzIndex skip blocking

---

README.md

Into the readme.md. Closes #2458.

#2458 add installation instructions

---

sp_BlitzFirst.sql

Fixes #2463 
This change returns the functionality for @ExpertMode = 1.

Re-adding @ExpertMode check to ensure it returns wait stats

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
SqlServerVersions.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

#2469 2020-07-12 release

---

README.md

#2476 add sp_Blitz documentation

---

CONTRIBUTING.md

Fix link in Contributing.md
Just replaced the %20 with _ and it now works (at least, I think it's going to the right place).

Fix link in Contributing.md

---

Documentation/sp_Blitz_Checks_by_Priority.md
sp_Blitz.sql

Reprioritize checks so that I can say with a straight face, you should be seriously concerned about priorities 1-50. Closes #2492.

#2492 sp_Blitz reprioritize

---

README.md
sp_Blitz.sql

Checking for empty spaces, adding Ns in front of strings. Closes #2496.

#2496 sp_Blitz tweaking SkipChecksServer implementation

---

sp_BlitzIndex.sql

Add a new Parameter `@ShowAllMissingIndexRequests` to sp_BlitzIndex. When set to true (1) it will display all missing indexes, regardless of the expected benefit.
Fix for issue #2498

Add @ShowAllMissingIndexRequests

---

sp_BlitzIndex.sql

2227 sp_BlitzIndex missing index data type tweaks

---

Uninstall.sql

Drop table SqlServerVersions on uninstall

---

sp_BlitzCache.sql

Adds to ExpertMode and to the output table. Adds the column if it doesn't exist. Closes #2514.

sp_BlitzCache add plan_generation_num

---

sp_BlitzCache.sql

Works in SortOrder = all. Closes #2513.

#2513 sp_BlitzCache query_hash in default output

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
SqlServerVersions.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

Bumping dates & versions, fixing sp_BlitzIndex for SQL 2008. Closes #2518.

#2518 2020-08 release

---

sp_BlitzIndex.sql

Finishing off the fix for #2533 
Existing error in sp_BlitzIndex where #missingindexes was limiting equality/inequality/included columns to nvarchar(4000). As suspected on the live stream, that has been like that since day 1 of open sourced code. I've bumped that up to nvarchar(max).
Also a bunch of CASTs to make sure the columns are not truncated when inserting in there..

Stop truncating columns

---

sp_BlitzCache.sql

Implementation of #2528 
Tested on SQL Server 2019 CU6 Enterprise:
local server for regular table in DBATools DB without linked server
local server for regular table in DBATools DB with linked server
local server on ##BlitzCacheResultsTemp table
target server on DBATools DB using linked server
for each case with table existing and not existing.
only tested changing @Top parameter for now to make sure the sp_execute for insertion worked properly with parameters.
One know case where the procedure breaks is if existing table already exists on target and was created locally, and thus having one columns in XML and not NVARCHAR(MAX) format (same as sp_Blitz).
Will continue testing next week to validate all parameter settings, just in case.

sp_BlitzCache remote

---

sp_BlitzCache.sql

World's worst fix for when the number is over 100%. Closes #2532.

#2532 sp_BlitzCache many duplicate plans

---

sp_BlitzFirst.sql

Added nolock and a lock timeout hint on there to get us started. Working on #2548.

#2548 sp_BlitzFirst nolock on stats query

---

CONTRIBUTING.md

Linking to Rob Sewell's intro to github.

Updating readme for github

---

sp_BlitzIndex.sql

#2552 sp_BlitzIndex index name cap at 128

---

sp_Blitz.sql

Related to #2569
Fixed the cross apply risk by reducing greatly the number of lines coming back from sys.master_files (1 per disk).

sp_Blitz-Drive-Space v2.1

---

SqlServerVersions.sql

Add extended properties to SqlServerVersions table

---

SqlServerVersions.sql

#2576 SqlServerVersions update

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

#2578 202009 release

---

Documentation/sp_Blitz_Checks_by_Priority.md
sp_Blitz.sql

#2581 sp_Blitz check for too many VSS snaps

---

sp_BlitzIndex.sql

Handling partitioned columnstore indexes.

#2584 sp_BlitzIndex columnstore partitioning

---

sp_Blitz.sql

Functionality has been coded and tested to allow for local creation of results table with NVARCHAR(Max) QueryPlan column.  This will allow one table to be used for remote and local writes to a permanent table.

Update sp_Blitz.sql to allow functionality in Issue-2601

---

sp_BlitzFirst.sql

Stop eliminating ze rows!
Close #2609

Change cross apply to outer apply

---

sp_BlitzCache.sql

This will add a filter to remove rows with 0 values for the chosen sort order.
Closes #2174

Add filtering based on sort order

---

sp_BlitzLock.sql

#2613 sp_BlitzLock ExportToExcel param

---

sp_BlitzIndex.sql

Many DMVs were missing database prefixes that made the script not work correctly from other database contexts.
Closes #2616

Add database prefixes in to DMV queries

---

sp_BlitzIndex.sql

Re-based version of modification counter addition

---

sp_BlitzIndex.sql

Continuing on with Mr. Darling's excellent work in 2616, and this time fixing cross-database bugs in the columnstore visualization. Working on #2616.

#2616 sp_BlitzIndex database prefixes

---

sp_BlitzWho.sql

Add more sort options and work on case sensitive servers. Closes #2603.

#2603 sp_BlitzWho add more sort options

---

sp_BlitzIndex.sql

Add SortOrder parameter. Closes #2619.

#2619 sp_BlitzIndex add SortOrder param

---

Documentation/sp_Blitz_Checks_by_Priority.md

Updating max checks for newly added database-scoped config checks. Closes #2573.

#2573 sp_Blitz documentation

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
SqlServerVersions.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

Bumping version numbers and dates. Closes #2626.

#2626 2020-10 release

---

sp_BlitzIndex.sql

Adds a sample query plan to Mode 3 out put and table-level output. Working on #2185.

#2185 sp_BlitzIndex missing index plans

---

sp_BlitzWho.sql

Reverts BrentOzarULTD/SQL-Server-First-Responder-Kit#2639

Revert "Adding Parameter Details from Cached and Live Query Plans"

---

sp_DatabaseRestore.sql

Fix use of @StopAt parameter in order to apply it for full backups

#2600 fixed @StopAt parameter for full backups

---

sp_BlitzCache.sql

Barely tested, working on #2646.

#2646 sp_BlitzCache unused grant sort

---

sp_BlitzIndex.sql

Don't show reads/writes for spatial indexes or disabled indexes since they're not tracked. Closes #2650.

#2650 sp_BlitzIndex spatial

---

sp_Blitz.sql

issue link
https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/2640

Added check for backups to NUL, checkID is 256

---

Documentation/sp_Blitz_Checks_by_Priority.md
sp_Blitz.sql

Adding documentation in checks list, tweaking wording. Closes #2640.

#2640 sp_Blitz log backups to nul

---

sp_BlitzIndex.sql

#2651 sp_BlitzIndex SortDirection

---

sp_BlitzCache.sql

#2655 Altered the definition of the PlanCreationTimeHours computed column in the output table only.
**Old definition:** DATEDIFF(HOUR, PlanCreationTime, SYSDATETIME())
**New Definition:** DATEDIFF(HOUR,CONVERT(DATETIMEOFFSET(7),[PlanCreationTime]),[CheckDate])
Create table statement updated and a new statement added to check the computed column definition, if this differs from the expected then the column is dropped and recreated.

2655 Computed column PlanCreationTimeHours definition change

---

Documentation/sp_BlitzIndex_Checks_by_Priority.md
README.md
sp_BlitzIndex.sql

Using the DEATH Method. Closes #2662.

#2662 sp_BlitzIndex reprioritize findings

---

sp_BlitzCache.sql

Add DatabaseName to group by and join.
Also discovered that this particular update was running twice, so remove the second one. This marks the first time BlitzCache has ever gotten shorter.
Sorry if that screws up any metrics for you 😃
Closes #2653

Fix multiple plan query

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

Bumping version numbers and dates.

2020_11 release

---

sp_BlitzLock.sql

Adds a having clause to checkid 13 to prevent 0 count rows from being inserteded.
Fixes #2682

having mercy

---

sp_BlitzLock.sql

Correctly identifies batch mode parallel deadlocks.
Closes #2686

Stinkin batches

---

sp_BlitzLock.sql

Adjusted conversion of TimeZone that won't match with the join criteria in "Check 6"
#2674

sp_BlitzLock - TimeZone convertion

---

sp_BlitzLock.sql

Added on Check 2 summary filter that shows only index locks
#2676

sp_BlitzLock - filter includes non-index locks

---

sp_BlitzLock.sql

Implemented changes discussed with @erikdarlingdata in #2691

sp_blitzLock results in excessive memory grant

---

sp_BlitzFirst.sql

#2697 sp_BlitzFirst ignore FT_IFTSCHC_MUTEX

---

sp_BlitzFirst.sql

Show 20 files instead of 5, and sort them by stalls. Closes #2707.

#2707 sp_BlitzFirst more files

---

Documentation/sp_BlitzCache_Checks_by_Priority.md
Documentation/sp_BlitzFirst_Checks_by_Priority.md
Documentation/sp_Blitz_Checks_by_Priority.md
sp_BlitzFirst.sql

Went through the code and updated documentation to match the code. Also updated comments to mention check IDs where missing.
I did remove documentation for checks in sp_Blitz that I could not find in code - not sure if this is the way to do it or if we should mark them as retired, happy to update as needed.

Documentation updates

---

sp_BlitzFirst.sql

Fixes typo and clarifies percentage

Update sp_BlitzFirst check 46 wording for #2732

---

sp_ineachdb.sql

Tweaking "F" CTE for case sensitivity support. Closes #2737.

#2737 sp_ineachdb case sensitivity

---

sp_BlitzFirst.sql

Show table variables differently named than temp tables. Closes #2742.

#2742 sp_BlitzFirst forwarded fetches

---

sp_BlitzFirst.sql

Now only shows the number of forwarded fetches during this collection, not cumulatively. Closes #2743.

#2743 sp_BlitzFirst forwarded fetch accounting

---

sp_Blitz.sql

sp_Blitz - Offline databases show up in auto-shrink and page verification checks #2750

---

sp_BlitzLock.sql

When user runs without sysadmin or db_owner permissions sp_BlitzLock fails reporting '#t' cannot be found. Added try/catch
to skip line if fails for 1088 error. If any other error is returned, it throws as normal.
Tested on SQL 2014/2019.
Assumed OK to use THROW since proc is locked to 2012+ anyway.

sp_BlitzLock: Add error check for update stats on temp table, skip if fails

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql

2021-01 release

---

sp_Blitz.sql

Add more trace flags to the list. Closes #2766.

#2766 sp_Blitz trace flags

---

sp_BlitzIndex.sql

By lock wait time descending. Closes #2768.

#2768 sp_BlitzIndex: sort aggressive indexes

---

sp_BlitzCache.sql

Removing minimum threshold when sort order is recent compilations. Closes #2772.

#2772 sp_BlitzCache recent compilations

---

Documentation/sp_BlitzFirst_Checks_by_Priority.md
sp_BlitzFirst.sql

Updated documentation and sp_BlitzFirst. Blog post is scheduled for February 4th, so that link won't work yet.
Closes #2776

Check for >20% runnable queries

---

sp_Blitz.sql

Now only runs when CheckUserDatabaseObjects = 0. Closes #2779.

#2779 sp_Blitz CHECKDB

---

sp_Blitz.sql

Changing BrenOzar to BrentOzar. Closes #2786.

#2786 sp_Blitz typo

---

sp_ineachdb.sql

#2790 sp_ineachdb Azure SQL DB compat

---

README.md
sp_BlitzAnalysis.sql

#2713 Create sp blitz analysis   query information logged from sp blitz first output tables

#2713 Create sp blitz analysis   query information logged from sp blitz first output tables

---

sp_BlitzCache.sql

Added PlanGenerationNum to @expertmode=0 call for sp_BlitzCache

Added PlanGenerationNum to output for @expertmode=0

---

SqlServerVersions.sql
Uninstall.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzAnalysis.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

Also adding sp_BlitzAnalysis to uninstall script, adding new updates to SqlServerVersions.sql.

2021_02 release - bumping version numbers

---

sp_BlitzFirst.sql

Resolution for issue #2738
Change log:
splitted command `sp_MSforeachdb <string>` to string creation then call to `sp_MSforeachdb` with variable

Updates sp_BlitzFirst - Solves #2738

---

sp_DatabaseRestore.sql

Added option to move FullText Catalog files during restore

#2805 sp_DataBaseRestore FullText Catalog restore

---

Documentation/sp_BlitzCache_Checks_by_Priority.md
Documentation/sp_BlitzFirst_Checks_by_Priority.md
Documentation/sp_Blitz_Checks_by_Priority.md
sp_Blitz.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzQueryStore.sql

Fix for issue 'Need to rationalize 'brentozar.com' #2803'

Rationalized brentozar.com

---

sp_BlitzFirst.sql

Avoids calling sp_MSforeachdb. Closes #2819.

#2819 sp_BlitzFirst in Azure SQL DB

---

sp_BlitzFirst.sql

In Azure SQL DB, use sys.dm_db_wait_stats. Closes #2821.

#2821 sp_BlitzFirst Azure waits

---

Documentation/Development/_TestBed.sql
Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
SqlServerVersions.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzAnalysis.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

2021-03 installer scripts

---

sp_BlitzLock.sql

Removed the text described in #2849

Changed sp_BlitzLock help text #2849

---

sp_Blitz.sql

Remove advisory language. Closes #2854.

#2854 sp_Blitz service account

---

sp_Blitz.sql

Fix USERSTORE_TOKENPERM calculation

---

sp_BlitzIndex.sql

Issue 2851:  Amended sp_BlitzIndex to only show the columnstore index visualisation details of a table. 
- Added new parameter @ShowColumnStoreOnly bit, default value of 0.
- Setting parameter value to 1 will skip the majority of the "Step 3 - diagnose the patient" section of the procedure and only execute the Columnstore Index checks.
- Parameter is only checked if the @TableName is not null. Otherwise it's never used.
- If parameter is set to 1 and table does not have a columnstore index, then the existing no columnstore index information is shown, as normal, instead of the columnstore visualisation data.

Issue 2851:  sp_BlitzIndex - Only show Columnstore Index Visualisation details.

---

sp_BlitzIndex.sql

Closes #2845
Add the ability to Sort by Create and Modify Date columns in Mode 2.
The Sorting experience had to be rewritten a bit for data types not to clash, but hey.

Add dates to sort order option

---

sp_BlitzIndex.sql

More accurate missing index plans

---

sp_BlitzWho.sql

Adds new cached_parameter_info and live_parameter_info to existing tables. Closes #2842.

#2842 sp_BlitzWho params to table

---

Documentation/Development/Merge Blitz.ps1
Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzAnalysis.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

Bumping dates and version numbers.

2021-04 installer scripts

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql

Including sp_BlitzWho fix for 2870.

---

sp_Blitz.sql

Skip check for Instant File Initialization. Closes #2879.

#2879 sp_BlitzFirst on RDS

---

sp_BlitzFirst.sql

#2878 Corrected CPU HowToStopIt ordering

CPU HowToStopIt ordering

---

SqlServerVersions.sql

FixedBuildNumFor2016CU17

---

sp_BlitzLock.sql

Add bigint conversion to sums

---

sp_BlitzCache.sql

Hopefully fixes the plan cache count calculations.
Closes #2909

Issue 2909

---

sp_BlitzFirst.sql

Initial attempt!
Reference #2913

Add thread time to wait stats views

---

SqlServerVersions.sql

New 2019CU11, 2017CU25
Added versions for 2 new CU's

New 2019CU11, 2017CU25

---

sp_BlitzIndex.sql

fix for issue 2954

---

sp_DatabaseRestore.sql

sp_DatabaseRestore: fix trailing slash for root drives

---

sp_BlitzFirst.sql

Remove USE

---

Documentation/sp_BlitzIndex_Checks_by_Priority.md
sp_BlitzIndex.sql

Purely informational. Nothing else to do here now.
Closes #2963

Add optimize for sequential key

---

Documentation/sp_BlitzIndex_Checks_by_Priority.md
sp_BlitzIndex.sql

Check is just a slight variation on the current check for FKs with cascading actions.
Closes #2964

Add check for unindexed foreign keys

---

sp_BlitzWho.sql

If the output table already exists and it doesn't have the wait_resource column, add it. Closes #2970.

#2970 sp_BlitzWho add column

---

sp_Blitz.sql

Add 1204 to TF list

---

sp_BlitzFirst.sql

Use sysprocesses instead

---

sp_Blitz.sql

Added cluster info in sp_blitz

Adding code in sp_blitz to show cluster node information.

---

SqlServerVersions.sql

AddedCU14For2019

---

sp_DatabaseRestore.sql

1. we now check that it is a valid datetime
2. add extra log file to restore (that contains transactions up to @StopAt)
3. add STOPAT parameter to the RESTORE LOG command

Changed the way the @StopAt param is used.

---

sp_BlitzIndex.sql

Fixes BrentOzarULTD/SQL-Server-First-Responder-Kit#3053.

Add `total_forwarded_fetch_count` to output table of sp_BlitzIndex

---

sp_DatabaseRestore.sql

Fixes #3061 
Unrelated to #3049

sp_DatabaseRestore: Fix backup file selection for @StopAt and non-split diff backups

---

sp_Blitz.sql

Fixes #3063
Tested on large size and growth database of > 2TB.

#3063 sp_Blitz Arithmetic Overflow Error Check 158

---

SqlServerVersions.sql

Added 2017 CU29

---

SqlServerVersions.sql

Added 19 CU16

---

sp_BlitzCache.sql

Making Row Estimate Mismatch and Calls X Function(s) consistent. Closes #3096.

#3096 sp_BlitzCache capitalization

---

sp_BlitzLock.sql

For spid and wait_resource to the output table if they don't already exist. Closes #3101.

#3101 sp_BlitzLock add columns

---

sp_Blitz.sql

For procs in system databases. Closes #3119.

#3119 sp_Blitz ignore recompile

---

sp_BlitzIndex.sql

Oops! Almost missed the last minute addition from @paulneering. Closes #3085.

#3085 sp_BlitzIndex Output Param

---

sp_BlitzFirst.sql

Add database name to end of file stats output. Closes #3118.

#3118 sp_BlitzFirst filestats dbname

---

SqlServerVersions.sql

Added 2019CU17

---

sp_BlitzFirst.sql

Remove extra USE statement. Closes #3138.

#3138 sp_BlitzFirst Azure USE

---

sp_Blitz.sql

Include modules listed here:
https://learn.microsoft.com/en-us/troubleshoot/sql/performance/performance-consistency-issues-filter-drivers-modules 
#3147

sp_Blitz - Update Dangerous Third Party Modules

---

SqlServerVersions.sql

Added the last CU 2017 before it drops into extended support;

Added 2017 CU31

---

sp_Blitz.sql

Modified check ID 2 to reference data from DBCC DBINFO (dbi_LastLogBackupTime field).
Required pulling the population of #DBCCs out of check 68 to enable the two checks (and other futures) to use the data.

Check ID 2 refer DBCC DBINFO data for log backup

---

sp_Blitz.sql

To detect sqlmaggieAntiVirus_64.dll (malware) or anything else labelled AntiVirus. #3149

sp_Blitz - Update Dangerous Third Party Modules for AntiVirus

---

sp_Blitz.sql

Fix date conversion, so it works in all languages

---

sp_BlitzQueryStore.sql

To avoid embarrassing odors. Closes #3155

Switch to TRY_CAST

---

sp_BlitzIndex.sql

Implemented output support for remaining modes (0,1,3,4) in sp_blitzIndex, implementing #2774

Implemented output support for remaining modes in sp_blitzIndex

---

sp_DatabaseRestore.sql

Adds new undocumented columns. Fixes #3190.

#3190 sp_DatabaseRestore SQL Server 2022

---

README.md

Updating to clarify which versions are supported.

Readme - supported versions

---

sp_BlitzLock.sql

Closes #3215 
3rd time's the charm.

Fix for #3215

---

sp_BlitzWho.sql

#3174 - Sorry about that, I had made a commit on my branch that was ready to go just didn't create a pull request.

3174 sp_BlitzWho - Include tempdb internal allocations

---

sp_BlitzCache.sql

#3172 Add Pattern column for BlitzCache Output Table

Add Pattern column for BlitzCache Output Table

---

sp_BlitzLock.sql

#3206 sp_BlitzLock truncation

---

Documentation/Development/Merge Blitz.ps1
SqlServerVersions.sql

Changing the Merge Blitz.ps1 to run on my Mac, and updating SqlServerVersions.sql with the latest GDR.

2023-02-15 release prep 1

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
sp_AllNightLog.sql
sp_AllNightLog_Setup.sql
sp_Blitz.sql
sp_BlitzAnalysis.sql
sp_BlitzBackups.sql
sp_BlitzCache.sql
sp_BlitzFirst.sql
sp_BlitzInMemoryOLTP.sql
sp_BlitzIndex.sql
sp_BlitzLock.sql
sp_BlitzQueryStore.sql
sp_BlitzWho.sql
sp_DatabaseRestore.sql
sp_ineachdb.sql

Bumping version numbers and dates, building install scripts.

2023-02-15 release prep 2

---

sp_BlitzFirst.sql

To prevent startup problems with Hekaton. Closes #3237.

#3237 sp_BlitzFirst Remove @@ROWCOUNT

---

sp_DatabaseRestore.sql

Tested on SQL 2019 CU#19.
Very open to feedback, this is my first pull request.
Thanks!

Added @FileExtensionDiff param. Fixes #3234.

---

SqlServerVersions.sql

SqlServerVersions.sql

---

sp_BlitzFirst.sql

New OutputResultSets param lets you skip output sets. Closes #3255.

#3255 BlitzFirst optional output sets

---

sp_DatabaseRestore.sql

Implements issue #3267
Fix database_principals that do not match server_principals after a cross-server restore.

sp_DatabaseRestore: Add @FixOrphanUsers option

---

sp_Blitz.sql

Show alerts in all databases, and also fixed a bug in the unsupported version checks. Closes #3278.

#3278 sp_Blitz TDE alerts

---

SqlServerVersions.sql

And change CU1-3 to use the KB ID numbers. Closes #3275.

#3275 add 2022 CU4

---

sp_DatabaseRestore.sql

Add the KEEP_CDC option to the RESTORE DATABASE ... WITH RECOVERY command.

Add @KeepCdc parameter

---

sp_DatabaseRestore.sql

Matching Microsoft's documentation. #3190

#3190 sp_DatabaseRestore data types

---

sp_Blitz.sql

Closes #3292
This feels like a somewhat naïve set of checks. I don't know a ton about security. It may clash when someone uses `EXECUTE AS` or signs the procedure for execution for lower-privileged users. I just don't have the chops to test all that to a satisfactory degree.
It's also incomplete at the moment, because I need to round up commands that touch other databases we may not have read permissions in and exclude those. 
I fully expect this to get rejected, but it got me error-free runs in a tightly locked down SQL Server environment.
If anyone has feedback, I'm happy to take it.

Add some permissions checks to sp_Blitz

---

sp_DatabaseRestore.sql

Creating this to fix issue 3320

Fixing output message to show correct parameter

---

sp_BlitzQueryStore.sql

This should resolve both issues documented in the [related bug](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3312).
The first commit adds a block to detect if the database config setting for PARAMETER_SENSITIVE_PLAN_OPTIMIZATION is present and enabled. 
If PSPO is enabled and the filter for @StoredProcName is used, we will include queries whose object_id = 0, but have a parent query that is related to the object matching @StoredProcName.
The second commit adds a block that attempts, if PSPO is enabled, to update #working_metrics.proc_or_function_name with the name of the parent query's object for any rows where proc_or_function_name IS NULL. The proc_or_function_name section does not depend on whether @StoredProcName is used; there may be variant queries in the …

PSPO fix for object_id issues in sp_QueryBlitzStore

---

sp_Blitz.sql

Issue #3326 
Added Check 106 to #SkipChecks when @SkipTrace = 1

Issue #3326 sp_Blitz fails on sys.traces

---

sp_BlitzCache.sql

Adds @SortOrder = 'duplicate'. Closes #3345.

3345 sp blitz cache sort by duplicates

---

sp_BlitzCache.sql

Second attempt at adding sort order for duplicate plans in the cache. Working on #3345.

#3345 sp_BlitzCache duplicate plans 2

---

sp_Blitz.sql

Fix for issue #3355 
Add a check to see if we have access to the MSDB database, and if we don't, we'll disable the checks that fire on the MSDB database.

#3355 Added permissions check for MSDB

---

sp_BlitzCache.sql

#3368 updated all instances of `@minimumExecutionCount` to `@MinimumExecutionCount`

#3368 Case issue with @MinimumExecutionCount

---

Install-All-Scripts.sql
Install-Core-Blitz-No-Query-Store.sql
Install-Core-Blitz-With-Query-Store.sql
sp_Blitz.sql

Fixing wrong variable name introduced in recent changes.

sp_Blitz power savings

---

sp_Blitz.sql

Fixes #3377
The msdb permission check was too broad and didn't work as intended, one can see the objects in the database but may not query the dbo.sysjobs, dbo.sysalerts, and/or dbo.sysoperators
I split the `@SkipMSDB` into 2 separate variables
```
@SkipMSDB_objs
@SkipMSDB_jobs
```
And expanded the check to a general objects check, if that one passes we can view the user tables.
The `@SkipMSDB_jobs` is set to 1 if we can't query `msdb.dbo.sysjobs`
If `@SkipMSDB_jobs = 1` then we'll skip check related to jobs

#3377 Expanded msdb permission checks

---

sp_Blitz.sql

Implemented Brent's desired column check using all_columns in the hope of pleasing the Mighty Ozar.
Sorry, couldn't resist myself.
Closes #3409

#3409 Implemented a different check for the 'instant_file_initialization_enabled' column

---

sp_ineachdb.sql

sp_ineachdb run only for writable copy of an AG database To achieve this I added a param, @is_ag_writeable_copy, bit with default value of 0. In the existing section, from Andy Mallon, for testing if an AG is present, I added an IF block to remove database that are not the writable copies in an AG if the above param is set to 1.
modified:   sp_ineachdb.sql

#3399 modified sp_ineachdb to generate scripts only for writable databases in an AG

---

sp_Blitz.sql

Fixed with every DBA's favorite T-SQL component, DISTINCT. Closes #3402.

#3402 sp_Blitz AG duplicate rows

---

CONTRIBUTING.md

Telling people not to touch the install files. Closes #3432.

#3432 contributing guide

---

SqlServerVersions.sql

SqlServerVersions - adding CUs

---

sp_BlitzCache.sql

It's a typo fix.  Thanks for making my job easier. Whiskey and Yoga

Update sp_BlitzCache.sql - Typo fix

---

sp_Blitz.sql

Fixing outdated instructions in sp_Blitz. Closes #3446.

#3446 contribution instructions

---

SqlServerVersions.sql

Had 2023 instead of 2024 on release date.

SqlServerVersions 2019 CU25

---

sp_BlitzIndex.sql

Closes #3461
This dumps the mode 2 results into a temp table, and then either returns the contents or some situational details about the execution and instructions to use BringThePain when required.

Closes #3461

---

sp_BlitzFirst.sql

Closes https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3483
This is a trivial change. It's just updating to the correct URL

sp_BlitzFirst.sql: Updated URL for Slow Data File Reads - Bug #3483

---

sp_BlitzQueryStore.sql

Closes #3472. Also removes a very small number of unneeded spaces in the proper code.
I could have waited until the issue had some discussion on it, but I already had the code ready from an old PR so there was no reason to not just throw this PR in.

sp_BlitzQueryStore.sql: Fixed various spelling/grammar issues, mosty double spaces.

---

sp_BlitzQueryStore.sql

Closes #3476. Very simple change.
I could have waited until the issue had some discussion on it, but I already had the code ready from an old PR so there was no reason to not just throw this PR in.

sp_BlitzQueryStore.sql: Switch TOP X with TOP (X)

---

sp_BlitzIndex.sql

Revert a few performance tuning changes for SQL Server 2014 RTM compatibility. Closes #3452.

#3452 sp_BlitzIndex 2014 compat

---

Documentation/sp_Blitz_Checks_by_Priority.md
sp_Blitz.sql

Updated links on new alerts, added documentation. Closes #3481.

#3481 sp_Blitz security docs

---

CONTRIBUTING.md
README.md

Clarifying that we only support versions that Microsoft currently supports. Closes #3468.

#3468 updating supported versions

---

Documentation/sp_BlitzFirst_Checks_by_Priority.md
sp_BlitzFirst.sql

Add warning when open connections is higher than max worker threads. Closes #3491.

#3491 sp_BlitzFirst max worker threads

---

sp_BlitzIndex.sql

The URL column doesn't end up with an URL - which makes me think that the field order and value order has become incorrect

Insert statement column order don't appear correct for the URL column

---

Deprecated/readme.txt
README.md

For deprecated scripts. Closes #3537 and #3529.

3537 removing readme references

---

sp_DatabaseRestore.sql

This is the ~~18+~~ 28+ month-later analogue to #3062, because this time I had to go back before the most recent full backup

sp_DatabaseRestore: fix backup file selection for @StopAt and non-split full backups

---

Documentation/sp_Blitz_Checks_by_Priority.md
sp_Blitz.sql

#3586 - adding target & total memory counters to server info section. Closes #3586.

#3586 - adding target & total memory counters to server info section. Closes #3586.

---

SqlServerVersions.sql

Adding latest SQL Server 2022 and 2019 builds.

2025-04-07 sqlserverversions

---

sp_BlitzFirst.sql

#3643 - sp_BlitzFirst RDS Restores

---

sp_BlitzLock.sql

Closes #3640
Fixes hardcoded table and column names
Fixes #dd temp table not populating when not in "table" mode.

Issue 3640

---

sp_Blitz.sql

Adds new database scoped configurations. Closes #3646.

#3646 sp_Blitz 2025 db scoped

---

sp_Blitz.sql

Adds preview_features database_scoped_configuration. Closes #3655.

#3655 sp_Blitz add 2025 dsc

---

SqlServerVersions.sql

Fix 2019 CU31/32 swap, add new GDRs. Closes #3677.

#3677 versions updates

---

sp_Blitz.sql

to set your default SA user.
I did not use @UsualDBOwner you do not have these the same. Amend

Added @UsualOwnerOfJobs to be used in CheckID 6 Jobs Owned By Users
